from pathlib import Path
import json,hashlib,sys,os,yaml
sys.path.insert(0,'tools');from source_resolver import resolve_source_house
P=Path(__file__).parent;R=Path.cwd();old=Path('working/p2-enrichment/snapshots/T21-private-language-law-nation-centralisation-2026-09-08/external');law=Path('submission-package/essay/symbolon/episteme/histories/places-and-peoples/language-law-nation-centralisation/DEVELOPMENT.md');sha=lambda b:hashlib.sha256(b).hexdigest()
assert json.loads((P/'effects-result.json').read_text())['returncode']==0
prior=json.loads(Path('working/p2-enrichment/receipts/T22-language-law-consumer-private-source-read.json').read_text());hashes={Path(r['path']).stem:r['sha256'] for r in prior}
rows=[dict(id='reich-1935-citizenship-law-first-regulation',domain='political-theory-institutions',author_dir='german-reich',authors=['German Reich'],title='The Reich Citizenship Law (15 September 1935) and First Regulation (14 November 1935)',year=1935,kind='legal-instruments',stem='reich-citizenship-1935',exts=['pdf','txt'],url='https://germanhistorydocs.org/en/nazi-germany-1933-1945/the-reich-citizenship-law-september-15-1935-and-the-first-regulation-to-the-reich-citizenship-law-november-14-1935.pdf',anchor='branch-vii-germany',scope='Two complete instruments in the GHI English translation; three PDF pages including source credits. No German facsimile collation. Editorial introduction remains distinct from statutory text.',identity='The selected witness is German History in Documents and Images, document1523, a three-page English PDF. Its credit identifies Nuremberg staff translation, edited by GHI staff, from Nazi Conspiracy and Aggression, volumeIV (Washington, DC: US Government Printing Office,1946), documents1416-PS and1417-PS, pp7–10. GHI separately identifies the German originals in Reichsgesetzblatt1935I, p1146ff and p1333. Those German originals and the1946 volume have not been independently collated in this admission.',cards=[('Citizenship and political standing','PDF pp1–2, instrumentI, §§1–3,15September1935','The law distinguishes state subjecthood from Reich citizenship. It reserves citizenship to a subject classified as German or kindred blood who meets its conduct requirement; only Reich citizens receive full political rights. The implementing office is empowered to issue legal and administrative decrees. This records the statute’s racialising categories, not valid biological classifications or cancellation of every form of nationality.'),('Classification and implementing authority','PDF pp2–3, instrumentII, §§1–7,14November1935; particular use §§2–5','The regulation assigns provisional citizenship and administrative withdrawal, defines classifications through ancestry and Jewish religious-community membership, and states further conditions for persons assigned two Jewish grandparents. It excludes persons classified as Jews from Reich citizenship, political voting and public office, while specifying transition, pension and other exceptions. Sections6–7 retain additional classification rules and exemption authority. The English legal prescription does not establish enforcement in every case.')]),
dict(id='us-1946-paperclip-policy-frus448',domain='political-theory-institutions',author_dir='united-states-government',authors=['Dean Acheson','United States government'],title='Interim Exploitation of German and Austrian Specialists under Project Paperclip — FRUS1946V, document448',year=1946,kind='memorandum-and-policy-enclosure',stem='paperclip-1946',exts=['html','txt'],url='https://history.state.gov/historicaldocuments/frus1946v05/d448',anchor='branch-xi-postwar',scope='Cover memorandum, enclosure2a–b and editorial approval note89; navigation excluded. No complete personnel archive or compliance audit.',identity='Office of the Historian, Foreign Relations of the United States,1946, The British Commonwealth, Western and Central Europe, volumeV, document448, file862.542/9–346. The cover is Dean Acheson’s top-secret memorandum as Acting Secretary of State to President Truman, Washington,30August1946. The enclosure states interim policy. Editorial note89 records the handwritten approval dated3September1946. The selected object is the institutional HTML transcription, not a newly collated original signed memorandum.',cards=[('Cover, expansion and approval','Document448, cover memorandum30August1946 and editorial note89 recording approval3September1946','Acheson recommends expanding the existing Paperclip programme to secure the services of German and Austrian specialists, with family movement, modified custody and possible later immigration status. The cover identifies agreement among State, War and Navy. The editorial approval note identifies Truman’s3September approval. Recommendation, approved policy and a particular person’s later appointment are distinct objects.'),('Contract, custody and screening rules','Document448, enclosure2a(1)–(7) and2b(1)–(3); internal page marker691 falls within2a(6)','The enclosure prescribes contracts, movement of specialists and families, temporary limited military custody, return where necessary and biographical/security records. Clause2a(5) excludes more-than-nominal Nazi Party participation or active support for Nazism or militarism. Scientific or technical honours alone do not disqualify a specialist; doubtful cases may receive further screening in the United States. Clause2b distributes continuing information and screening duties. These are stated rules, not evidence that screening or every appointment complied.')]),
dict(id='nara-2000-gehlen-disclosure',domain='political-theory-institutions',author_dir='national-archives',authors=['National Archives and Records Administration'],title='CIA Intends to Release Records on Cold War Spymaster',year=2000,kind='archival-announcement',stem='gehlen-records',exts=['html','txt'],url='https://www.archives.gov/iwg/about/press-releases/cold-war-spymaster-records.html',anchor='branch-xi-postwar',scope='Complete6-paragraph institutional announcement dated5October2000, with title/date/contact context; not the released intelligence archive or personnel files.',identity='National Archives, Nazi War Crimes Interagency Working Group announcement, College Park, Maryland,5October2000. The page’s later review date15August2016 is website maintenance metadata, not the announcement date. The saved HTML and extraction preserve the institutional notice read in the prior law packet.',cards=[('Acknowledgement and intended release','Announcement5October2000, opening paragraph and closing Holtzman/IWG paragraph','The notice reports a CIA affidavit acknowledging an intelligence relationship with Reinhard Gehlen, possession of related records and a commitment to process them for release under the Nazi War Crimes Disclosure Act. The IWG coordinates release and public notification. A commitment to process records is not a claim that this admission has read the archive.'),('Postwar institutional relationship','Announcement5October2000, third through fifth body paragraphs','The notice describes Gehlen’s former wartime intelligence role and a postwar network with Nazi and collaborationist backgrounds. It distinguishes the initial Army Intelligence relationship from subsequent CIA responsibility continuing until1956, and identifies the IWG’s postwar-use remit. The notice is an institutional disclosure witness; it does not establish each individual’s conduct, screening history or appointment compliance.')]),
dict(id='perdomo-et-al-2020-performative-prediction',domain='computer-science-ml',author_dir='perdomo',authors=['Juan Perdomo','Tijana Zrnic','Celestine Mendler-Dünner','Moritz Hardt'],title='Performative Prediction',year=2020,kind='conference-paper',stem='perdomo-2020',exts=['html','txt'],url='https://proceedings.mlr.press/v119/perdomo20a.html',anchor='branch-xii-computation',scope='Publisher proceedings abstract and bibliographic metadata only; no full article, supplementary material, proof or field-trial reading.',identity='Juan Perdomo, Tijana Zrnic, Celestine Mendler-Dünner and Moritz Hardt, “Performative Prediction,” Proceedings of the37th International Conference on Machine Learning, Proceedings of Machine Learning Research119 (2020):7599–7609. The selected witness is the unpaginated proceedings landing-page abstract and its bibliography, not the article PDF. The article page range identifies the work; it is not used as a locator for a passage not read.',cards=[('Prediction changes its target','PMLR119 proceedings page, unpaginated Abstract; article metadata7599–7609 is bibliographic only','The abstract defines predictions as performative when decisions based on them influence the outcomes predicted. It introduces performative stability relative to future outcomes resulting from acting on predictions and describes a risk-minimisation research framework. The abstract reports convergence results, but no theorem, assumptions, proof, experiment or full article is independently admitted by this bounded reading. The stated problem supplies a technical neighbour for institutional feedback, not proof of every social feedback mechanism.')])]
manifest=[]
for row in rows:
 sid=row['id'];assert resolve_source_house(R,sid) is None,sid
 assert sha((old/(row['stem']+'.txt')).read_bytes())==hashes[row['stem']]
 home=Path('submission-package/essay/symbolon/episteme/sources')/row['domain']/row['author_dir']/sid/'SOURCE.md';raw=Path('working/sources-texts-references/primary-texts')/row['author_dir']/sid
 assert not home.exists() and not raw.exists();raw.mkdir(parents=True);copies=[]
 for ext in row['exts']:
  src=old/(row['stem']+'.'+ext);dest=raw/src.name;b=src.read_bytes();assert b;dest.write_bytes(b);copies.append({'origin':str(src),'path':str(dest),'sha256':sha(b)})
 md={'title':row['title'],'source_id':sid,'primary_domain':row['domain'],'record_type':row['kind'],'node_type':'source-house','ownership':'canonical-source-house','schema_version':1,'author':row['authors'],'title_full':row['title'],'year':row['year'],'source_role':['selected-institutional-witness'],'metadata_status':'verified','edition_status':'selected-local-witness','citation_status':'selected-scope-ready','quote_status':'paraphrase-only','chicago_ready':False,'local_copy':copies[0]['path'],'url':row['url'],'passage_surface':'#passages','main_source_for':[],'consumed_by_histories':[str(law)+'#'+row['anchor']]}
 link=os.path.relpath(law,home.parent)+'#'+row['anchor']
 t='---\n'+yaml.safe_dump(md,sort_keys=False,allow_unicode=True)+'---\n# '+row['title']+'\n\n## Bibliographic identity and selected witness\n\n'+row['identity']+'\n\n## Reading scope and consumption\n\n'+row['scope']+' Full named scope was read in the T21 law development; the text hash matches the later T22 consumer-source receipt. This admission reuses that reading and rechecks the exact passages, not a new whole-book or archival investigation. No direct quotation is admitted.\n\nThe [language–law–nation history]('+link+') consumes the bounded witness in its existing situated branch. Historical claim, legal prescription, authorial comparison and implementation evidence retain separate standing.\n\n## Provenance\n\nInstitutional origin: [selected witness]('+row['url']+'). Local acquisition is preserved byte-for-byte from the prior private packet. Verified2026-09-08.\n\n'
 for c in copies:t+='- `'+c['path']+'`: SHA-256 `'+c['sha256']+'`; original acquisition `'+c['origin']+'`.\n'
 t+='\n<a id="passages"></a>\n## Admitted passages\n\n'
 for i,(title,loc,body) in enumerate(row['cards'],1):
  q=sid+f'-q{i:03d}';t+=f'<a id="{q}"></a>\n## Passage card — `{q}` — {title}\n\n> **Paraphrase (not a quotation):** {body}\n\n- **Locator:** {loc}.\n- **Status:** paraphrase-only.\n- **Source relation:** Paraphrased.\n- **Verification:** exact named scope read in the prior law packet; saved witness and extraction hashes rebound2026-09-08.\n- **Provenance:** institutional witness and immutable local-copy hashes above.\n- **Use boundary:** {row["scope"]}\n- **Consumer:** [owning historical branch]({link}).\n\n'
 home.parent.mkdir(parents=True);home.write_text(t.rstrip()+'\n');manifest.append({'source_id':sid,'path':str(home),'sha256':sha(home.read_bytes()),'copies':copies,'read_scope':row['scope'],'cards':len(row['cards']),'original_url':row['url'],'law_anchor':row['anchor']})
(P/'admissions.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print('Admitted4actualwitnesses, scopedcards',sum(r['cards'] for r in manifest))
