from pathlib import Path
import re,os,json
root=Path.cwd();b=Path('working/p2-enrichment/snapshots/T20-private-taylor-authored-images-2026-09-08');home=Path('submission-package/essay/symbolon/mytheme/worlds/frank-taylor/taylor-authored-images/WHOLE.md');home.parent.mkdir(parents=True,exist_ok=True)
source=Path('submission-package/essay/symbolon/episteme/sources/internal-corpus/taylor/taylor-2026-personal-poetry-corpus/SOURCE.md')
def link(p,a=''):return os.path.relpath(p,home.parent)+(('#'+a) if a else '')
S=link(source);E='../../../../episteme/'
comments=[
"The voice moves from being here to being everywhere and nowhere, reaches checkmate, then asks for another game. Staying in knowing and setting another going belong to one invitation: the other can come again. The final repetition of play opens what the apparent ending had closed. Its address to you is part of that reopening; the poem would lose its return if reduced to an assertion that everything is one.",
"The first turn gives the Unknown a relative knowability and removes final possession from the Known. The husk is what comes back when knowing fixes exclusively on its object. The last two lines restore the act and its participants: Known and Knower are held in a conjugal relation whose joy belongs to Knowing. Mystery therefore deepens as the relation becomes articulate; accumulating an inventory of unknown things would miss the poem's change of focus.",
"The familiar saying passes through three changes of case and agency. One recognises another; the One knows the One; knowing then takes the separate claimant through no-one. The final line lets the repeated word keep several offices without allowing the individual knower to retain possession of them all. Its commas and capitals perform those turns. A uniform spelling of one would remove the differences through which this recognition proceeds.",
"The single breath distinguishes the whole One at 0 from the enumerated All at 1, then releases the latter's claim to finality through none and once and for all. The wit depends on the Two Ones retaining different offices. This is Taylor's numerical poetic expression; its symbolic use of number travels back to the native derivation rather than supplying an independent arithmetic proof.",
"Field becomes way and way becomes field before either can close into an object. The first stanza makes disclosure a movement through vistas and paths. The second gives the seal an opening office, then lets sight become flight in the wind. Real returns as re-All: the poem re-enters the field of particulars from the reality they disclose. Its sound pattern carries the transition through yield, veil, entail and portrayal; none of those words alone substitutes for the passage.",
"Searching changes from a question about where the clue lies to a question about who knows. What ever was and what is ever anew meet within the same Truth. The final movement releases the secret from exclusive custody: it flies for the many as much as the few. The capital I and the play on Time belong to this turn from seeking outward to making what is known available.",
"The first stanza makes humanisation and spiritualisation reciprocal tasks, with the possibility of seeking itself at stake. The second gives that reciprocity an institutional demand. Humanity both made and makes the institution; the present tense prevents an originating act from becoming an exhausted historical credit. An institution that consumes this continuing humanity devours its own constitution. The poem's dream is an expressed aspiration with a social consequence.",
"The first line raises the expectation of an account of awakening and brings it down to getting tired. The second names what exhausts the speaker. The shortness matters: the poem offers no ladder of superior attainments after that exhaustion, and its final word declines the decorum through which the same evasion could continue.",
"Freedom begins under examination: how could it remain free while being bound by law and contingency? Rule changes its office when the poem passes from a rule to itself to the Rule of The Self. The house of liberation then meets rain at its window. By the end, wind, eye and message pass beyond the pigeonhole that would classify their arrival. This is a movement in the experience of freedom, not a legislative claim that every particular action is exempt from consequence.",
"The opening pair gives Knowing and Being parallel releases from defence and pretence. The following pair pursues what each release makes possible: war loses its occasion in one, while slighting cannot soil sense in the other. The last line tests its claim in sound, letting slighting approach slightly without letting injury acquire the final authority to determine what is real.",
"Both routes begin with two. The first resolves the poles as opposed signed ones and cancels them to zero. The second retains 0 and 1, generates their four ordered pairings, and keeps the generating two alongside the four: 4+2. The printed rows are the entire numerical poem. Their difference is the fate of relation under the two operations, not a preference for one decorative numeral over another.",
"The shared root enters where binary computation and thinking meet their stated limits. Two recognise it, and our powers grow: the ending moves into the first-person plural. Following the numerical fork, this small poem makes the increase of power dependent on a relation that the isolated poles could not supply. Its claim remains in the native and poetic register; it reports no benchmark about computing machines.",
"Life leads and flows while words alternately transfix and slip. When language stays, understanding frays; language must then cave to lay the way bare. Cave changes from a possible enclosure into an enacted yielding. The last line crosses the edge beneath the lips, bringing the physical place of speech into the release of speech. Its own words accomplish the approach to their limit.",
"The prepositions carry the fork: two goes to two opposed ones in the opening stanza, and through the Two Ones in the second. Differentiation is playful and productive here. Contrast projects two upon itself while retaining its generating pair, then love turns the six toward recollection. The children's ring ends by falling through the loop. The ending changes the meaning of perfection: completing the figure makes return possible rather than enthroning a finished enclosure.",
"The poem opens with an issue in our age and turns one into One before widening the scene through panes, air, planets, bodies and weather. Two makes the bond perceptible; time can divide for a shared future. The critique of severance then gives three reasons: the cutting mind is derived, its measure limits the sky, and its definitions seal each side away from the other. Humility enters as a prerequisite of precision. Read with P3, this preserves productive differentiation while exposing the cut that forgets its bond; the open sky at the end answers the blocked frame at the beginning.",
"God moves from a proposed object of dispute into a word whose pointing exceeds the place words can occupy. Left and right master a span together; symbolic number enters the account, and the account includes its own release. The close turns an injunction to silence through three small pauses, so, to, speak. Those pauses make finding the limit an act of language. The historical duration and doctrinal polemic inside the verse remain Taylor's utterance; quoting the complete poem does not turn them into independently established history.",
"Horror and everyday normality occupy the same four-line field. Façade on veneer doubles the thinness of what remains dear, but the ending does not give the speaker the comfort of abandoning its inhabitants. Love is spoken alongside my hatred and their fear. The pronouns keep that difficult implication personal. In the journal this arrives after Taylor's pressure that nothing changes while all is change, and the admission that the next move remains possible without predicting its outcome.",
"The attempt to understand manufactured desire is itself swallowed by the need for soothing. The speaker's knowledge does not spare him the capture he describes. Kid and sin become two hearts in one breast; the opened door and the firing of a vessel then make a different use of the same forces imaginable. The later distinction between speaking from distress and speaking to it changes the speaker's office. Time, breath and the bitter pill bring that change toward a choice between soothing sleep and entrainment. Even after this choice appears, stagnation returns. The last movement explicitly seeks no eradication: reconciliation of the brothers within must make the speaker capable of becoming a right light to others. The final revised witness preserves this aftermath, which an excerpt ending at the kiln would lose.",
"The referent is withheld while seven clauses disclose what depends upon it. Beyond consequence does not mean inconsequential; residence remains within journey, and movement through time does not displace what presides. The final clause locates the mind's foundation beyond the mind's finding. Taylor explicitly resisted replacing the withheld referent with atman or witness: naming either draws it into the distinctions the poem is traversing. The journey through such distinctions is necessary and self-negating.\n\nA later authorial instruction in the same conversation places the context clause before the silence clause, so that context carries #4, silence #5, and the final mind clause the 5→0 return. The complete quotation above preserves the canonical compilation's two-line witness, which still has silence before context. The revised order is stated here as Taylor's instruction, not silently substituted for the verse. His further demand is to derive the positions from the primary determinations, rather than assign an already finished poem to six slots. **Human-amplified: yes** for this withheld-referent and sequence correction.",
"Taylor calls these four clauses the preceding poem's encapsulation. The notion grows through difference and depends upon inference for presence, yet speaks plainly and branches without requesting consent. This short work has its own beginning, cadence and end even in that close relation to FT-P19. Keeping both complete allows the encapsulation to gather the longer movement without replacing it.",
"The sentence first makes a differential field from the infinite and infinitesimal, then follows four first-person clauses: being the same, knowing difference, having that knowledge, and seeking sameness. The repetitions and changes of verb matter as much as the two opening quantities. Taylor's subsequent correction requires both a static and a processual reading: a thing and its thinging, definite identity and the activity through which it is specified. Multiplication carries expansive plenitude together with precise differentiation.\n\nHe then calls for a second, divisional reading. The first passage must complete 0/1, its 4+2 field and 5→0 return before the inversion to 1/0 opens a full 4′+2′ and 5′→0′ passage back to 0/1. Division does not replace the original word multiplied in the verse, and the inverse half cannot be compressed into the first return. This authorial reading restores the ordered movement around the sentence; it does not declare an indeterminate product or quotient a valid calculus identity. Independent mathematical claims require the native matheme's derivation and their own mathematical conditions. **Human-amplified: yes** for the two-pass, noun/verb correction.",
"Feeling first takes in and undergoes. The sea's plaything and captain of the mine offer two positions inside that experience; the winds still pass through the one who quakes. Taylor's explicit correction identifies the boots through quaking in my boots. Relating to the one in them means becoming able to relate consciously to one's own emotions and to the feeler who undergoes them. An earlier conversational gloss made the relation primarily one to a brother; Taylor rejected that reading.\n\nThe dawning movement consequently changes how feeling is lived, rather than promising that feeling will disappear. Venus holds and unfolds intuition; Sophia and the martian occur in a field capable of kindness, boldness, chilling solidity and mellifluous warmth. These changing tonal offices complete this poem. They do not license the separate, still-unmined Venus–Lucifer–Christ genealogy. **Human-amplified: yes** for the self-relation and boots correction; no additional doctrinal identity is asserted for its named figures.",
"A purchase carries aeons and a surface carries layers, but the shoe that fits must still be returned. Sole, phew, eternal rule and the quiet worthless stone place value under pressure from the poem's sounds. Residing beneath sense then permits sense-making, while what flies cannot be possessed by attending only to its passage. The final stanza names Blake and the fleeting joy before closing on bones. Making a fixed claim risks becoming what has been fixed. Blake remains the poem's named poetic allusion; no additional Blake quotation or textual attribution is manufactured here."
]
head=f'''---
title: "Taylor — Poetry and Authored Images"
record_id: mytheme-taylor-authored-images
record_type: whole-mytheme
register: mytheme
claim_status: Argued
source_relation: Extracted / Argued from
textual_status: developed-draft-awaiting-parent-T22
poem_units: 23
admitted_image_units: 14
---

# Taylor — Poetry and Authored Images

<a id="taylor-authored-images-whole"></a>
## #0 — A word that can return to its speaker

A game reaches checkmate and asks to be played again. A definition lets air through its panes. A speaker who has understood capture discovers himself seeking its soothing once more. Taylor's poems give these returns different bodies. Their sounds, intervals, pronouns and endings let the relation be lived before an account collects it. The poems remain twenty-three individual works within this authored whole; a shared philosophical field gives them relations without making them fragments of an unwritten master poem.

The [Personal Poetry Corpus]({S}#complete-poems) **sources** the complete texts below. It distinguishes ten undated earlier works, the six-work P0→P5 composition, and seven dated journal works from March–June 2026. The order here is that compilation's order; it does not pretend that the June sequence chronologically preceded the March poems. Bracketed first-line titles are indexes where no authorial title was found. Each quotation retains the compilation's exact wording and lineation. Subsequent authorial corrections are stated beside their own poems so that text, revision instruction and commentary remain distinguishable.

This is Taylor's situated authorial world. The language is English; the dated journal encounters and June composition supply particular occasions of production. No birthplace or geographical route is inferred from a file location. [Neumann's shared archetypal ground](../../../archetypal-ground/neumann-images/WHOLE.md#neumann-round) carries the structuration of genesis, world-parent relation, opposition, differentiation, separation and renewed interplay. That common morphology remains distinct from the geography of particular tellings and from the order and duration of their transformations. It makes relations comparable without converting Taylor's dated works into stages of a universal cultural chronology. The psychological morphology and Taylor's native derivation also keep distinct source offices.

The native field is complete before a local image receives a formal reading: `/ = −/−`, `0/1`, `?/!`, `−/+`, `X/x`, `AM/IS`, `∞/dx`, `1/0`. The slash and inverted parent enclose neither a miscellaneous list nor a one-way ladder. Each parent opens its full four-and-two articulation, and return permits the inverse passage. Being at 0/1, Becoming at 2/3, and Knowing/unKnowing at 4/5 give the sequential harmonics; Essence at 0+5, Constitution at 1+4, and Text/Texture at 2+3 give a different, complementary reading. The [core source]({E}sources/internal-corpus/taylor/taylor-2026-core-theorems-pithy/SOURCE.md) **sources** that authorial field. Its `X/x` is Taylor's notation. Neither Neumann nor a poem supplies its derivation retrospectively. The sixfold of this page follows the corpus's own changing forms; it does not distribute all twenty-three works among six prefabricated meanings.

The prose immediately following a poem describes its words and complete movement. Symbolic amplification is identified separately: **human-amplified: yes** where the authored programme or a precise correction supplies the relation; additional interpretive extrapolation remains **human-amplified: no**. Reading a complete work is not permission to assign every bird, vessel or god-name a fixed cross-story identity.

## #1 — Play, knowing, and the humanity that makes its forms

The earlier works move among address, recognition, institutional desire and release. Their lengths matter: the two-line fatigue of waking and the extended rain against the window of freedom do different work. Each begins again in its own voice.

'''
parts=[head]
blocks=[]
for n in range(1,24):
 m=re.search(r'<a id="taylor-2026-personal-poetry-corpus-q%03d"></a>\n(.*?)(?=\n<a id=|\n## Provenance and exclusions|\Z)'%n,source.read_text(),re.S);s=m.group(1);title=re.search(r'^#{3,4} (.+)$',s,re.M).group(1);quote=re.search(r'(^>.*?)(?=\n\n- \*\*Locator:)',s,re.M|re.S).group(1)
 if n==11:parts.append('## #2 — Two roads, six works, and the return through the loop\n\nThe P0→P5 order belongs to this composition. P3 and P4 are a consequential pair: one unfolds the productive play of distinction, the other addresses its severing misuse. Their complementary lean is **human-amplified: yes** in the authored six-route programme. A return through the sequence does not create a seventh poem.\n\n')
 if n==17:parts.append('## #3 — Dated encounters and the speaker changed by speaking\n\nThe journal poems return to a speaker who undergoes what he can articulate. March gives contradiction a social and bodily pressure; May develops the unnamed referent, difference and feeling; June lets a fitting form be returned. The changes happen within particular works and dates, not in an imposed developmental ranking.\n\n')
 parts.append(f'<a id="taylor-ft-p{n:02d}"></a>\n### {title}\n\n{quote}\n\n[Complete source witness]({S}#taylor-2026-personal-poetry-corpus-q{n:03d}) · Extracted authorial poem.\n\n{comments[n-1]}\n\n')
 blocks.append({'id':f'FT-P{n:02d}','anchor':f'taylor-ft-p{n:02d}','source_anchor':f'taylor-2026-personal-poetry-corpus-q{n:03d}','quote':quote})
(b/'poem-blocks.json').write_text(json.dumps(blocks,ensure_ascii=False,indent=2)+'\n')
home.write_text(''.join(parts))
print(home)
