from pathlib import Path
import json,re,hashlib,datetime,collections,urllib.parse
B=Path('working/p2-enrichment/audits/T21-current-reconciliation'); d=json.loads((B/'current-row-audit.json').read_text()); loc=json.loads((B/'current-fragment-locators.json').read_text()); L={r['row_id']:r for r in loc['rows']}; root=Path.cwd()
P='working/p2-enrichment/snapshots/T22-private-E19-reciprocal-closure-2026-09-08/E19-actual-graph-semantic-proof.json'; proof=json.loads(Path(P).read_text()); PR={r['record_id']:r for r in proof['rows']}
def paras(path):
 p=Path(path)
 if not p.is_file():return []
 ls=p.read_text().splitlines(); out=[]; start=0
 for i,l in enumerate(ls+['']):
  if not l.strip():
   if i>start:out.append(dict(path=str(p),start_line=start+1,end_line=i,text='\n'.join(ls[start:i])))
   start=i+1
 return out
def witness(path,needle):
 return [p for p in paras(path) if needle.lower() in p['text'].lower()]
def targets(p):
 out=[]
 for q in paras(p):
  for v in re.findall(r'\]\(([^)]+)\)',q['text'])+re.findall(r'\[\[([^]|]+)',q['text']):
   v=urllib.parse.unquote(v.split('#')[0]);v=v.strip('<>')
   if not v or re.match(r'\w+://',v):continue
   dst=(root/v if v.startswith(('submission-package/','working/')) else root/Path(p).parent/v)
   if not dst.suffix:dst=dst.with_suffix('.md')
   try:rel=str(dst.resolve().relative_to(root))
   except ValueError:continue
   out.append((rel,q))
 return out
cache={}
def links(p,t):
 if p not in cache:cache[p]=targets(p)
 return [q for dst,q in cache[p] if dst==t]
carrier={
'history-ancient-philosophy':('B51 opposed pulls, Aristotle focal predication, different distributive/corrective/exchange measures and reconstruction of cycles retain different preserved relations.','Ethics/Politics comparisons keep unequal household and merit criteria explicit; Freeth abstract/model is not full recovered mechanism. Detienne/Vernant chapter10 and Greek zero-table evidence remain tasks.'),
'history-indian-philosophy':('Witness/instrument, exclusion, finite Śaiva capacities and recognition supply different operations and retain the positive native ontology independently.','Selected Dyczkowski material is bounded; Dharmakirti secondary reception, specific Buddhist passages and Vāk/recognition textual and translation tasks remain separate.'),
'history-language-law-nation-centralisation':('Twelve branches distinguish incorporation, transmission, literary/administrative participation, racial law, transregional belonging and computational recurrence; historical naturalisation is examined through named acts.','The twelve child rows carry documentary deficits. Update Aion paragraph83 to actual consulted-carrier passage maps without promoting quotation or selected-printing equivalence.'),
'history-language-symbol-dialogue':('Qualified reference, saying/showing versus later practice, situated Lacanian address, dialogical suspension, attention weights and selected index retain different operations.','Lacan1972/Price2017/Darmon1992/later reception are distinct; Rotman chapter2, Bohm book-specific passages and particular selected-edition collation remain tasks.'),
'history-mathematics':('Zero acquires permissions; ordinal succession, exceptional division, re-entry, iterant shift, covering displacement and octave completion preserve different laws.','No unrestricted zero cancellation; Dutta reconstruction not ordinary field division. Native 9/8 completion differs from comma; full Freeth article and any physical confinement claim remain distinct tasks.'),
'history-myth':('Harmonia retains Fear/Panic; Homer distinguishes capture, bride-gifts, fine and contingent surety; Huayan gives the simile its own limit; subsequent Nietzsche/Gebser/Taylor receptions retain their dates and offices.','Jung1921 function/attitude recovery is now in dossier: replace blanket missing-recovery claim at90 with SOURCE-admission/edition tasks. Cleary English collation, Phillips venue/date, Detienne/Vernant chapter10 and Jorjani chapters remain tasks.'),
'history-process-systems-science':('Finite determination, duration/occasion, formal recurrence, biological production and participating instrument supply distinct ways an achieved form conditions a further act.','Scoped Bergson/Whitehead/Maturana/Varela admissions are acquired. Flasch, Blind Spot book passages, Van Eenwyk copied quotations and literal dynamical/implementation claims retain independent tasks.'),
'history-psychology':('Ego/Self, symbolic change of interpreter, institutional jurisdiction and model dynamics are distinguished; psychic recognition alone does not redistribute coercive power.','Selected Pauli/Jung material is bounded; Atmanspacher conjecture is not experiment. Van Eenwyk, empirical basin models and historical/institutional outcome claims need their named evidence.'),
'history-technology-politics':('Source of a measure, inference/training, instituted classification and actual local reference differ; returned labour cost must reach permission or commission.','Do not retain stale unavailable-local-copy assertions after new OI admissions. Particular crowd/institutional and implemented-commons outcomes remain independent of programme reports.'),
'history-zero-subject-advent':('Arithmetic admission and articulation of concealed psychic/perspectival conditions form an authorial braid, not one historical cause. The acquired symbol retains the first sign’s exact office.','Freud passage debt, Jung consulted-carrier boundaries and source-specific Neumann/Gebser times survive; no universal timetable or artificial phenomenal conclusion.'),
'dossier-formal-limit':('Russell formation repair, Gödel relative derivability, Wittgenstein saying/showing and ethics, Cusa approximation, Eckhart qualified predication and native performed return have different consequences.','Refs12/31/64/89 bounded residuals completed in owned receipt. Ref53 Cusa passages remain tasks; FileOne older alias unresolved; frequency→retention/signed-dia remains Offered research; no three-value escape from Gödel.'),
'dossier-bohm':('Dye recovery differs from vortex persistence; suspension changes a question; quarter-turn preserves modulus; SEED retains participants and the source/lens/return protocol is Offered.','1980/1996 books differ from consulted interview/essay/handout. Programme is not measured outcome; QL/tattvic relation remains authorial; no universal physical reversibility.'),
'dossier-jung-pauli-psychoid':('Dated correspondence preserves neutral-language demand, Jung’s psychoid clarification and refusal of absorption, and Pauli metric/topology objection. Typology has four functions and two attitudes with different offices.','Princeton/Roscoe consulted edition versus selected Routledge collation remains open; 1921 German witness requires source-house admission, not repeated recovery. Bache/attractor/cymatics claims are scoped Offered research.'),
'dossier-process':('Later note changes heard phrase; achieved occasion enters subsequent availability; biological production differs from permitted software action; changing criterion differs from trajectory under it.','Parent refs24/37/47/78/82/88 repairs and selected primary admissions are retained. Later enaction books, Van Eenwyk quotations, actual basin/physical confinement and deployed technical tests remain tasks.'),
'dossier-indian-philosophy':('Sound/name/bearer, I/you/it, witness/instrument, exclusion, finite capacity and recognition remain distinct. Five-step functional return retains source, generation and evaluation offices.','Selected Dyczkowski66–81 is bounded;90–91, Tantraloka identity, particular vikalpa exegesis, Vāk notebook mediation and Kripke passage cards remain their own tasks.'),
'dossier-zero-reception':('Inscription, place, operand and permitted zero-denominator regime are different admissions. Nothaft correction changes historical attribution; Rotman’s produced observer-role differs from native subject-pole.','Nothaft q001 is corrective abstract only; Gerbert and Salem manuscript remain separate primary tasks; Rotman chapter2 unacquired. No claim that zero’s arithmetic powers depend on these missing histories.'),
'dossier-oi-technical-responsibility':('Source, projection, contribution, acceptance and refusal keep distinct authority; six record probes are bounded behaviour. Six product offices differ from E6 operations; five-step return and three-office comparison remain specified proposals.','New SOURCE and three local copies now admitted per parent/Laplace. Six probes do not establish authentication, hosted acceptance, deployed entire lifecycle or artificial phenomenality. Full institutional consequence test remains task.'),
'lens-baudrillard':('Three historical orders differ from four image phases; model efficacy differs from fidelity; symbolic reversibility resists benign-dialogue reduction; the analysis must receive what its own frame excludes.','14 bounded primary paraphrases and2 editorial dispositions in five houses. Orgy belongs Transparency; map inversion Baudrillard; Fatal retains extremity without guaranteed acceleration programme. No five-book fullread or quotation-ready claim; fourfalls unratified.'),
'lens-foucault':('Admission of speech, distributed office and population-scale intervention are different mechanisms. An accurate worker report may protect the assignment; appeal must reach responsible commission.','Paragraph69 blanket Baudrillard collation debt stale; replace with exact selected Forget Foucault and Transparency warrant and remaining edition/quotation tasks. Other Foucault works remain individually scoped.')}
branch_debts={
'E1-con':'Four distinct contra/computare/continentia/comes lines; do not collapse by prefix. Keep each existing dictionary witness separate.',
'E1-region':'Country Path Gegnet dialogue distinct from Memorial Address; full region/horizon/gathering passage and translation collation remain required; Chang is nested reception.',
'E1-countenance':'Facies/prosopon independent entries and dated appearance/role uses; personhood not established by gloss sequence; Levinas/Watson/Gans source distinctions.',
'E1-count-six':'Six counting families need separate lexical histories; regere/reckon/rechnen cognacy unresolved; no universal counting genealogy.',
'E1-chinese':'Separate 向/嚮/饗/響/影響 histories; 域/遇 poetic only; Laozi variants/translation and Zhuangzi II whole passage tasks remain.',
'E1-native':'Native /, =, −/− and inverse parent require all eight; no lexical acquisition substitutes for native derivation.',
'E2-arbiter':'Dictionary witness/perception/weighing/decision acquired; dated primary institutional uses remain separate from authorial usurpation.',
'E2-hybris':'Historically attested excess distinct from native local-measure-occupies-source; retain legitimate finite decision.',
'E2-regard-leaf':'TLFi French dated senses acquired; Anglo-French and English dating separate; generated Regard not lexical synonym.',
'E2-anamnesis-leaf':'LSJ cited Plato locators acquired; continuous Platonic passages and selected editions not thereby read; recognition source collation distinct.',
'E2-fides-bridge':'LewisShort arbitror II.A PlautusBacchides3.6.41 dictionary attestation acquired; complete dramatic passage and selected edition remain.',
'E3-fourfold':'1539 judicial acts and1794 programme bounded; twelve history branches now developed and documentary yield uneven; no universal chronology.',
'E3-deficient':'Neo-nativity diagnosis requires actual institution, changed standing and effective challenge evidence for each history; modern technical execution still Offered.',
'E3-surety':'Homerq008 named contingent liability and release; later payment not reported; Latin lexical history and Greek-law classification remain independent.',
'E4-token':'Matching token sense acquired; dated institutional practice and dia/syn-ballein history remain distinct tasks.',
'E4-circulation':'1694 split tally and account dictionary are scoped witnesses; compute/credit/coin/fiat/value/digit do not thereby gain one completed history.',
'E4-comparative':'Sanskrit Samkhya, HebrewSPR, Chinesezhengming, Arabichisab/Names, Egyptianrn each still require entry, primary passage and dated practice.',
'E4-hole':'Reference38 hāl whole/holy/heal/health distinguished from hol hole; phonic chiasm register4, operational opening register3, no topology proof.',
'E5-greek':'Greek agreement/proportion and Aristotle focality have separate scopes; modern biological or formal identity not lexical consequence.',
'E5-biology':'Owen1843 selected original witness and source-route receipt exist; modern criterion has its own object and does not warrant every correspondence.',
'E5-invariant':'Each comparison owes map/respect, preserved relation and limits; no shared mark/number supplies causal or historical identity.',
'E6-names':'nomen/numerus comparative entries, nem reconstruction and denomination morphology remain uncollated; public joining is operational.',
'E6-house':'Selected Aristotle/Ephesians/Irenaeus/Ostrom scopes acquired; no completed coinage, theology, AI labour or planetary material-chain history.',
'E6-ratio':'ratio reor/ratus dictionary admitted; arithmos/harmony braid unverified; counting and criterion remain distinct.'}
nation=[
'1539arts110–111 and1794Grégoire bounded;1209/1229/1271 treaty/jurisdiction, school implementation and affected speakers still require primary recovery.',
'PGP Lunel→Maimonides letter supports that route; RABaD/IsaacKabbalah and ibnTibbontranslation distinct; Spain/Italy/Ficino/Pico links require dated chains.',
'Patronage/dynastic/Pacioli print-object witnesses are distinct; Minervois biscione exactobject unidentified;1494/1509 passages and change of mathematical use remain.',
'Yates thesis and Hanegraaff programme differ; exact scholarship and specific rejection/censorship/curriculum act remain needed.',
'Aion1979 consulted-carrier maps now present;1978 selected-printing/quotation collation and independent historical causal evidence remain.',
'Manzoni1868 four-objection text recovered; literary norm differs from administration; regional schooling/use evidence remains.',
'Fichte VII/VIII and1935 laws scoped; Herder/Grimm and each language→people→ancestry→race→law transition need their own witnesses.',
'Welsh1847 Conwy secondary notice scoped; actualActs/report, Irish plantation/property/office and ScottishGaelic sources remain distinct tasks.',
'1913notice andMandate1922articles scoped; actualschool records, PalestinianArabic/land/displacement/citizenship testimony remain constitutive tasks.',
'Torahhalakhahdiaspora, ChristianLogos/vernacular andQuranArabic/multilingualumma/fiqh have distinct objects; choose precise legal/covenantal question pertradition; Petersnotuniversalwarrant.',
'Paperclip1946approval andNARA2000Gehlen notice scoped; actualcompliance/personnel and USracial-law→Nazijurist reception are separate tasks.',
'Perdomo2020abstract, DPO2023 andOstrom2009 differentwarrants; actualversioned commission→source→policy→action→response→revision execution remains unperformed.'
]
# Authored reading judgments are kept separate from mechanically collected paragraphs.
ambiguous={'T21-A01','T21-A02','T21-A15','T21-A16','T21-A18','T21-A24','T21-A34','T21-A35','T21-C01','T21-C08','T21-C11','T21-C21','T21-C53','T21-C54','T21-C60','T21-C63'}
missing_concepts={'T21-C26':'The explicit apportioned-office/economy operation is developed in #4/#5 and Declared field; add literal E6 return to the received-share/source relation.', 'T21-C33':'The image→valuation→protected profile→changed interpreter circuit is developed; add literal E4 Account does not replace source return. Aion no-excerpts remains true, but acquired contextual passage-map status can now be added.', 'T21-C43':'The five-step and changed-source/state/evaluator/permission return is developed; add literal E4 Account re-enters source-field without certifying prakasa or deployed training.', 'T21-C49':'Native local-mark/source-office and inverse Two Ones relation is developed; add literal E4 Symbol answers to source. Preserve full native derivation and no new aphorism.'}
reroutes={'T21-C25':'Current direct return is Count-through-Countenance; old row assigns Name-through-Count. Preserve constitutive selection and add the distinct answer-to-counting-rule operation rather than silently replacing it.', 'T21-C27':'Direct E4 paragraph names Trust keeps the return route active while old row assigns Account does not replace source; criterion immunity connects both. Materialise two named operations only with their distinct account/reliance consequences.', 'T21-C46':'Direct anchor is Con-text-through-Diaphaneity; paragraph also performs Resolution by changed next conditions. Retain both generated offices in row.', 'T21-M04':'Current direct route is E3 Fides/Credere plus complete aphorism; old row assigns E4 Trust. Keep genealogy scopes; materialise E3 route and preserve/complete distinct E4 undertaking return.', 'T21-M23':'Direct anchor Arbitration-in-Crisis; paragraph exposes conditions and changes regime through Resolution. Expand operation mapping; do not identify within-basin motion with changed regime.', 'T21-M25':'Current direct route E1 native-field return; old row assigns E4 Symbol. Preserve all-eight source precedence and explicitly route source-answerability separately if retained.', 'T21-M34':'Current direct route E5 comparison separating Lacan and native QL; old row assigns E4 Symbol. Preserve E5 warrant and add E4 source-answerability only as distinct office.', 'T21-M40':'Current direct route E2 Con-text/Regard; original assigns Criterion-through-Distinction. Preserve criterion constituting the score and regard revising its office as two operations.', 'T21-M41':'Current direct route E1 Count-through-Countenance; old assigns E4 Account. Real local Bimba and wider source-dependence are developed; retain both routes with their distinct obligations.', 'T21-M44':'Current E4 label Account does not replace source; original Account re-enters source-field. Paragraph carries revisable reference; add actual changed-next-use consequence or record pair without treating inspection alone as re-entry.'}
for r in d['rows']:
 rid=r['row_id'];kind=r['row_kind'];home=r['canonical_home'];r['semantic_operation_witnessed']=False;r['global_row_closure']=False;r['current_fragment_candidates']=L[rid]['return_candidates'];r['observation_sha256']=L[rid]['sha256'];r['evidence_scope']='Native/authorial operation and historical/source warrant remain independent; present audit does not reacquire six source corpora.'
 r['source_obligations']=r.get('source_obligations',[]);r['consumer_obligations']=[]
 for c in r['consumers']:
  c['current_literal_return_fragments']=links(c['path'],r['field_path']);c['current_literal_forward_fragments']=links(r['field_path'],c['path']);c['semantic_standing']='Pair-specific comparison not inferred from either link or a primary-row judgment.'
 if kind=='whole-field-operation':
  r.update(development_status='field-operation-developed; all-declared-consumer-pairs-not-certified',semantic_operation_witnessed=True,judgment='The current whole develops this exact operation in its differentiated circuit; field cardinality is retained. This judgment does not certify every programme-assigned consumer or historical branch.')
  r['consumer_obligations']=['Use each consumer’s current occurrence and separately authored row judgment; do not propagate one operation sentence across all recipients as proof.']
  r['source_obligations']=[v for k,v in branch_debts.items() if k.startswith(rid[:2]+'-')]
 elif kind=='historical-source-branch':
  r.update(development_status='branch-retained; bounded-witness-and-research-disposition; historical-closure-not-certified',judgment=branch_debts[rid]);r['source_obligations']=[branch_debts[rid]];r['derived_branch_path']=str(Path(r['field_path']).with_name('HISTORICAL-BRANCHES.md'))
  r['consumer_obligations']=['No consumer may acquire descent, causal or doctrinal identity from a register-3 operation return; preserve this branch-specific task in its own home.']
 elif kind=='development-packet':
  key=rid[4:];j,s=carrier[key];r.update(development_status='carrier-operation-developed; E-return-parent-verified; source-boundaries-retained',semantic_operation_witnessed=True,judgment=j,source_obligations=[s],parent_pair_proof={'path':P,'record_id':key,'recheck':'working/p2-enrichment/receipts/T22-parent-E19-proof-recheck.json','standing':'63 actual paragraph pairs independently rechecked by parent; not this auditor’s full primary-source read or all downstream A/C/M closure'})
  r['current_E_pair_proof']=PR[key]['relations']
 elif kind=='historical-leaf-development':
  n=int(rid[-2:]);r.update(development_status='historical-operation-developed; documentary-coverage-partial',semantic_operation_witnessed=True,judgment='This branch follows the named institutional or transmission operation rather than substituting its taxonomy. '+nation[n-1],source_obligations=[nation[n-1]])
 elif kind=='per-element-consumer-scope':
  if rid in missing_concepts:r.update(development_status='consumer-operation-developed; literal-E-return-missing',semantic_operation_witnessed=True,judgment=missing_concepts[rid],consumer_obligations=[missing_concepts[rid]])
  elif rid in ambiguous:r.update(development_status='current-return-fragment-read; full-row-operation-proof-not-certified',judgment='The quoted current E-return fragment is relevant but does not alone establish every component of the authored row scope. Preserve the body; compare its full local derivation with: '+r['operation'],consumer_obligations=['Attach the material local derivation and its actual changed consequence, not just the E declaration.'])
  else:r.update(development_status='consumer-operation-witnessed; pair-specific-closure-not-extrapolated',semantic_operation_witnessed=True,judgment='The current quoted consumer paragraph performs the assigned local return with a stated consequence or retained distinction: '+r['operation'])
 elif kind=='transferred-39-movement-alignment':
  if L[rid]['return_candidates'] and rid!='T21-M33':r.update(development_status='movement-operation-witnessed; original-alignment-retained',semantic_operation_witnessed=True,judgment='The current movement fragment makes the local E operation consequential in this movement, rather than only listing the operation: '+r['operation'])
  else:r.update(development_status='movement-alignment-needs-exact-pair-reconciliation',judgment='The original operation remains a programme assignment. Current movement has no literal return to the assigned field, or the returned image alone does not prove the whole movement assignment. Do not infer missing mature body.',consumer_obligations=['Compare the current whole movement against '+r['operation']+'; preserve existing other-field and carrier returns; add only the exact missing consequence/return if this assignment survives.'])
 elif kind=='ratified-conjugate-development-scope':
  if L[rid]['return_candidates']:r.update(development_status='conjugate-operation-fragment-witnessed; full-scope-not-certified',semantic_operation_witnessed=True,judgment='Current conjugate fragment makes the local source/criterion/recognition return explicit; it does not certify the complete operational or empirical scope: '+r['operation'])
  else:r.update(development_status='conjugate-current-body-preserved; direct-E-pair-unproved',judgment='No literal link to the programme-assigned E field was located. This does not establish absence of the authored operation; whole conjugate semantic reread is not completed by this audit.',consumer_obligations=['Reconcile the existing conjugate through its canonical A home and exact inherited operation: '+r['operation']+'; direct E link is needed only if the programme intends a direct pair rather than that mediated route.'])
 elif kind=='ratified-root-scope':r.update(development_status='root-preserved; complete-semantic-audit-not-certified',judgment='AC remains one root with36 conjugates and36 arguments; no second primitive ontology or direct E link is inferred. Exact conditioning/thinging proof remains a separate root audit.',consumer_obligations=[r['operation']])
 elif kind=='explicit-admission-missing-from-inherited-queue':
  r.update(development_status='admitted-and-developed; obsolete-missing-body-status',semantic_operation_witnessed=True,judgment='One complete four-line aphorism now exists; E3 Fides/Credere and E4 Trust return preserve investigation/determination and faith/absolute-limit distinctions. These two rows are two routes to one record, not two aphorisms.',source_obligations=['Native027/#39 ratified exact four-line form; no abbreviated Two Ones reconstruction and no esoteric Name/Power essay dependency.'])
 elif kind=='pending-field-not-promoted':r.update(development_status='pending-not-promoted; preserved',judgment='Earth/taste/wisdom remains an unpromoted proposal; do not count a seventh E field or demand a canonical missing body.',source_obligations=['Retain homo/humus and sapere/scire sources independently; homo/homos not descent; Hebrew comparison homology.'])
 if rid in reroutes:r['proposed_operation_reconciliation']=reroutes[rid];r['consumer_obligations'].append(reroutes[rid]);r['development_status']+='; operation-map-adjustment-needed'
# Known literal gaps get full current bodies as evidence, not invisible semantic claims.
for r in d['rows']:
 if r['row_id'] in missing_concepts:r['current_local_body_witness']=paras(r['canonical_home'])
# Every row has exact source/disposition authority pointers, never an invented missing source claim.
for r in d['rows']:
 r['source_disposition_authorities']=['working/p2-enrichment/reference-note-dispositions.json','working/p2-enrichment/legacy-carrier-dispositions.json','working/p2-enrichment/T21-record-input-locators.json']
 r['proposed_row_update']={'row_id':r['row_id'],'development_status':r['development_status'],'canonical_home':r['canonical_home'],'operation':r['operation'],'evidence_register':r['evidence_register'],'source_obligations':r['source_obligations'],'consumer_obligations':r['consumer_obligations']}
counts=collections.Counter(r['row_kind'] for r in d['rows']);yes=collections.Counter(r['row_kind'] for r in d['rows'] if r['semantic_operation_witnessed'])
d.update(status='bounded-current-reconciliation-complete; global-semantic-closure-not-certified',observed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),method='Authored semantic judgments based on current operation paragraphs and recovered carrier reads; literal fragment harvesting is locator-only. Parent E19 proof separately attributed. Hashes are read-time observations, never frozen gates.',counts={'rows':len(d['rows']),'by_kind':dict(counts),'positive_local_semantic_witnesses':sum(yes.values()),'positive_local_semantic_witnesses_by_kind':dict(yes),'globally_closed_rows_certified':0,'parent_E_carrier_records':19,'parent_E_carrier_pairs':63,'parent_E_carrier_pair_errors':0},cardinalities={'E_fields':6,'whole_operation_rows':29,'E1_terms':6,'E1_operations':4,'E2_conjugate_fields':'6/6-prime','E2_generated_relations':6,'E3_offices':'Fides0→Topos1→Logos2→Nomos3→Natio4→Credere5→Fides','E4_terms':3,'E4_operations':4,'E5_terms':2,'E5_offices':3,'E6_terms':2,'E6_applications':5,'histories':10,'dossier_lenses':9,'A':36,'C':64,'conjugates_including_root':37,'movements':48,'inherited_record_inventory':162,'independently_admitted_aphorism_records':1,'reference_notes':89,'reference_note_files_including_README':90,'evidence_registers':4},mutation_scope='Only private audit files written. No canonical/SOURCE/NOTES/HISTORY/shared census/shared queue/index changes.')
(B/'current-row-audit.json').write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
(B/'proposed-row-updates.json').write_text(json.dumps({'standing':'Proposals only; materialise after parent barrier. Preserve authored operations unless explicit reconciliation accepted.','rows':[r['proposed_row_update'] for r in d['rows']]},indent=2,ensure_ascii=False)+'\n')
print(json.dumps(d['counts'],indent=2))
