from pathlib import Path
import json,hashlib
p=Path('working/p2-enrichment/audits/T21-current-reconciliation/current-row-audit.json');d=json.loads(p.read_text())
updates={
'T21-history-process-systems-science':('carrier-operation-developed; reciprocal-consumer-proof-pending','The historical companion separates finite determination, duration/occasion, formal recurrence/biological production, dynamical model and participating instrument. Each specifies what becomes available for a next act; final E4 return retains different objects rather than substituting a school taxonomy.','Bergson qualitative succession, Whitehead occasion, Varela third-state rules and Maturana production have separate cited carriers. Flasch exact passages, Blind Spot book excerpts, Van Eenwyk copied quotations and literal dynamical/technical tests remain explicit debts.','Read current M04/M06/M07/M11/M12/M23/M27/M30/M31/M36/M39/M41/M42/M44/M45 and A14/A19/A26/A30/A32/C07/C12/C41/C42/C43/C55 fragments before declaring complete reciprocal coverage.'),
'T21-dossier-bohm':('carrier-operation-developed; reciprocal-consumer-proof-pending','Dye recovery and vortex persistence perform distinct explication/persistence operations; suspension exposes assumptions; quarter-turn preserves modulus; SEED programme retains participant worlds; source/lens/return protocol remains Offered. E4 receives explicitly differentiated physical, dialogical and institutional returns.','Book1980 and1996 identities stay distinct from consulted interview, essay and undated handout. Brochure establishes programme/intention, not outcomes. QL and tattvic mapping are authorial; no physical universal reversibility or implementation result.','A14/A26/A22/A30/A32 and C07/C41/C37/C42/C55 need current actual fragment comparison; source→dossier outgoing links alone do not complete returns.'),
'T21-dossier-process':('carrier-operation-developed; reciprocal-consumer-proof-pending','A later note changes the heard phrase; an achieved occasion becomes available beyond immediacy; production networks differ from permitted software actions; a changed criterion differs from another trajectory under that criterion. These are distinct mechanisms of Account re-entering source-field.','Selected Bergson/Whitehead/Maturana/Varela/Daza cards are named. Later enaction works, Gebser selected passages, Van Eenwyk quotations, measurable basin construction and physical confinement/plate remain explicit research tasks, not undeveloped core process identity.','Verify A14/A26/A30/A19/A32/C07/C43/C12/C55 actual return fragments separately. Process history link still points to HISTORY rather than companion; legitimate history reference, but it is not proof of companion reciprocity.'),
'T21-lens-foucault':('carrier-operation-developed; stale-cross-source-claim; reciprocal-consumer-proof-pending','An accurate worker report can be classified to protect the assignment; distributed office retains accountable jurisdiction; aggregation changes scale of intervention; objection must reach commission. E2 crisis/E3 Nomos/E6 labour returns are differentiated and applications explicitly Offered.','The paragraph under foucault-critique-return still calls Baudrillard intake uncollated and its warrant a source task. Current five Baudrillard houses now carry14 bounded primary paraphrases plus2 editorial dispositions; retain remaining visual/full-book debts while replacing blanket stale claim at integration. Other Foucault works remain separate source tasks.','Current A24/A25/A29/C27/C28/C29/C53 fragments require individual proof. Declared commissioned authority is not a universal claim that every office usurps source.')}
for row in d['rows']:
 if row['row_id'] not in updates:continue
 status,j,s,c=updates[row['row_id']];f=Path(row['canonical_home']);body=f.read_text();row.update(development_status=status,judgment=j,source_obligations=[s],consumer_obligations=[c],carrier_witness={'path':str(f),'start_line':1,'end_line':len(body.splitlines()),'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'scope':'current complete carrier body read; source acquisitions not repeated'})
p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
