"""Explicit editorial operations for the accumulated whole; source lanes remain unchanged."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[3]
W=ROOT/'working/manuscript-source-enrichment-2026-09-20'
KEYS=['s01','s0','s1','s2','s3','s4','s5','s50']
texts={k:(W/'sections'/k/'SECTION.md').read_text(encoding='utf-8') for k in KEYS}
initial=texts.copy(); edits=[]
def change(k,old,new,label,reason):
    assert texts[k].count(old)==1,(k,label,texts[k].count(old),old[:80])
    assert old!=new
    texts[k]=texts[k].replace(old,new,1)
    edits.append(dict(section=k,id=label,reason=reason,old=old,new=new,original_start_line=initial[k][:initial[k].find(old)].count('\n')+1 if old in initial[k] else None))
def para(k,start,new,label,reason):
    m=re.search(r'^'+re.escape(start)+r'[^\n]*(?:\n(?!\n)[^\n]*)*',texts[k],re.M)
    assert m,(k,label,start)
    change(k,m.group(),new,label,reason)
def span(k,start,end,new,label,reason):
    a=texts[k].index(start); b=texts[k].index(end,a)
    change(k,texts[k][a:b],new,label,reason)
def reprise(k,start,end,label,summary,lead=''):
    a=texts[k].index(start); b=texts[k].index(end,a); old=texts[k][a:b]
    new=lead+f'<!-- reprise:{label}:start | {summary} -->\n\n'+old+f'<!-- reprise:{label}:end -->\n\n'
    change(k,old,new,label,'Controlled standalone reprise: the full source-specific development is preserved in this one body, folded in whole-manuscript reading and opened for standalone §5. The shared analytical continuation remains the same text.')

change('s01',"The difficulty encountered in Kripke's *Naming and Necessity* leads beneath the name to the discrimination of an instance:","Saul Kripke asks in *Naming and Necessity* how a name can identify its bearer beyond the descriptions presently associated with it. The inquiry pursued here carries that difficulty beneath the name to the discrimination of an instance:",'W01','Introduce the thinker through the naming difficulty; keep the subsequent name–instance–circumstance development explicitly this essay’s reception, as its existing note requires.')
change('s01','Descartes arrives at this pressure through doubt.','René Descartes reaches the question by trying to withhold assent from everything he can doubt.','W02','Give doubt its acting inquirer and particular method, rather than another authority arriving at an abstract pressure.')
change('s01',"Spinoza approaches that achievement through figure.","Benedict de Spinoza approaches the power of a limit through figure.",'W03','First introduction identifies the person and the definite operation already under examination.')
change('s01','Russell met this question within the attempt to secure mathematical reasoning.','Bertrand Russell met this question while trying to determine which constructions mathematical reasoning could safely admit.','W04','Specify the formation problem before the set construction; do not treat formal limits as interchangeable.')
change('s01',"Gödel found a different difficulty in sufficiently strong, effectively axiomatised arithmetic.","Kurt Gödel turned the inquiry towards what sufficiently strong, effectively axiomatised arithmetic could prove about its own proofs.",'W05','Introduce the specific investigation while retaining all hypotheses and the full following argument.')
change('s01',"The early Wittgenstein asks what lets a proposition represent at all.","Ludwig Wittgenstein, in his early work, asks what lets a proposition represent at all.",'W06','First introduction, with early/later distinction retained.')
change('s01',"In Whitehead's process philosophy, determinate unity is itself an accomplishment.","Alfred North Whitehead approaches the formation of a definite thing as an accomplishment in its own right.",'W07','Let the source enter through its positive problem rather than a surname plus doctrine label.')
para('s01',"Formal construction can also change what a system admits.","Formal construction can also change what a system admits. G. Spencer-Brown's calculus begins with the act of making a distinction. When that distinction re-enters the space it distinguishes, a two-state reading encounters a difficulty: crossing changes either state into the other, so a value required to equal its own crossing has no stable solution among those states. Repeated crossing alternates them. Francisco Varela takes up this self-reference problem by introducing an autonomous third state and rules governing its reduction alongside the others.[^s01-11] What becomes possible depends on that changed construction. The return into the marked space has made the calculus reconsider what it can admit.",'W08','Give Spencer-Brown and Varela a connected mathematical encounter, preserving the distinct re-entry operation and third-state response later developed in M27.')
para('s01',"The Śaiva articulation of knower, means of knowing and known gives this return a further precision.","The Śaiva articulation gives this return a further precision: knower, means of knowing and known remain distinguishable within one occurrence. In Mark Dyczkowski's exposition, awareness is luminous because an experience is manifest, whether it is a colour, a sound or a thought, and reflexive because that appearing is already known.[^s01-2] The definition has led back to this knowing without replacing it. Seeing, attending and remembering retain their different work within it; their constitution now becomes a positive subject of inquiry.",'W09','M07 is the primary full mirror/regress and cognitive-powers development. Keep the needed closure of the defining performance while removing a second compressed teaching immediately before it.')
para('s0','A name shows why articulation needs a situation.',"The name heard in the call now does more than identify its bearer. It places the named person in an address: someone is speaking to me, here, about something that may require an answer. The earlier distinction between name, instance and circumstance becomes active in the exchange. The speaker's I becomes the hearer's you, while either can become the person spoken about. A person described in the third person can be addressed and answer in the first; the relation changes because the one described now participates in determining what can be said.",'W10','Replace the repeated homonymy/counting lesson with the new operation M07 owns: a name becomes address and the described person can answer.')
span('s1',"Kashmir gives this second question a developed philosophical body.","Śakti gives this difference its positive force.","The Kashmiri account developed through Abhinavagupta gives the second question a philosophical body we can now recognise. Prakāśa and vimarśa have already shown how a colour and its contrast can be manifest and apprehended within one awareness. The changing content does not have to become a second substance outside that awareness in order to be different.[^s1-9] Here this anatomy meets the mathematical text's question of invariance: the source can remain itself through a real differentiation whose particular forms do change.\n\n",'W11','M07–M11 have supplied the positive Śaiva anatomy and comparative grounds. M14’s new work is the source-distinct encounter with Bhāskara; retain that encounter and its full following argument.')
change('s1',"Dutta's reconstruction asks us", "Amartya Kumar Dutta's reconstruction asks us",'W12','Identify the modern reconstructive witness at first entry without changing its historical standing.')
change('s1',"Robinson's enlargement of the number system allows", "Abraham Robinson's enlargement of the number system allows",'W13','Identify the mathematician through the specific enlargement, retaining the explicit nonzero-increment calculation.')
para('s1',"Naming has the same requirement of a determinate encounter.","The reckoner also inherits the naming problem met at the threshold. An inscription remains useful only while it lets the bearer be recognised in the relevant circumstances. When someone omitted by a count answers, that recognition can expose the inadequacy of the unit or criterion without disputing the total calculated under it. The count can be right and the account it was used to settle still need correction. Naming, counting and answering meet in the use made of the result.",'W14','Replace the third full homonymy example with its acquired consequence for reckoning and the answering Other.')
para('s1',"A *symbolon*, in its matching-token sense, gives a spare material expression", "The corresponding token met at the threshold carries this relation in its edge: the present piece remains answerable to the counterpart from which it was divided.[^s1-23] Zero and one can be held in that way. A determination is real, exact and consequential; its source remains consequential within its use. What matters now is how the powers of differentiation hold that relation when they distinguish, decide and gather.",'W15','Remember the existing token instead of introducing it again; give M19 a concrete inherited question without repeating its exact opening phrase.')
para('s2',"A word must be distinguishable from another word", "A judgment has to distinguish what follows from what does not. A refusal needs an edge; a perception needs a difference; a word must be distinguishable from another word to say anything. Zero's return has preserved these powers while making their dependence available to inquiry. The question is how they act: what does a distinction retain of the relation through which it became possible?",'W16','Receive M18’s achievement and turn it into the section’s operative question; remove the duplicated “differentiation with all its powers” sentence and the unneeded imaginary denial.')
span('s2',"Two senses of one are active here.","Self-Identity is present through the capacity to differ.","The Two Ones give the question its terms. `0 = One = Self-Identity` names the uncounted condition; `1 = All = Self-Difference` names the manifest and determinable field. A red mark belongs wholly to what appears while depending on the surrounding surface, the capacity to see colour and the continuity through which this appearance can be recognised. Its contour is real without originating those conditions. The source and the articulated All cannot be placed beside one another as two specimens of unity.[^native]\n\n",'W17','M18 has given the full Two-Ones development. Retain its exact terms and use the mark to enter the new continuity/correction and trust argument.')
para('s2',"Counting makes the mechanism easy to miss", "Counting makes the mechanism easy to miss because the count may be accurate. The meeting at the threshold counted attendance, then allowed attendance to decide standing. Here the excluded person returns as someone facing the decision-makers: its consequences will enter a life the list did not admit. *Countenance* gives this return an address. A name identifies and a count gives an amount under a criterion; neither supplies the other person's reply. Letting that reply affect the decision can change what the institution ought to count.[^fields]",'W18','Turn the earlier attendance/standing example into an institutional encounter; avoid a fourth explanation of shared names while preserving the full E1 relation.')
span('s2',"Another net conducts attention through another source-world.","Name and Power remain coequal throughout these actions.","The Huayan jewel-net now returns with a question raised by this release. The southwest jewel disclosed the many through one particular entrance; the ink mark became visible elsewhere through their existing relations. Its two questions prevented that entrance from becoming self-sufficient, and the teaching's own optical qualification returned the image towards Vairocana's activity for beings.[^indra]\n\n<a id=\"roz-s02-m22-claim05\"></a>\n\nHephaestus's net holds bodies whose release requires a changed undertaking. The jewel-net makes a local appearance intelligible through its constituting relations. Neither operation can do the other's work: a reflected mark assumes no debt, while Poseidon's undertaking changes who will answer for a possible loss. The first telling made dependence perceptible; the present encounter requires someone to act within it. Their conjunction makes the difference between mutual visibility and entrusted continuation newly exact.\n\n",'W19','The entire jewel/objections/ink/limit/return narrative already occurs in M10. Preserve its acquired memory and source boundary while developing its distinct encounter with Homer rather than retelling it.')
para('s3',"Dia-ballein `(+1)/(−1)` and sym-ballein", "The compact sixfold just constructed retains two terms and their four ordered relations. Its return must now become operable: a difference becomes definite, that determination can be repeated, and its result enters the conditions of another act. A triangle gives this inquiry a particular beginning. We can identify the figure, recognise its form in another instance and change the relation which makes its boundary an edge. The changes are distinguishable enough to be performed rather than only named.",'W20','Receive M24’s actual proof, then enter the construction M25 performs instead of introducing dia/syn again.')
para('s3',"These are eight determinations of one passage.","These are eight determinations of one passage: the parent relation and return bracket six qualitative determinations. Their traversal does not enlarge the six-position body into eight positions. The typed construction `B ⊔ (B×B)`, already counted as `2+2²=6`, retains the two singles and four ordered pairs. Following the judgment has now given those retained offices a qualitative articulation. The body can be counted, and the act through which it is recognised remains within its account.",'W21','Retain both the eightfold and typed six without a second elementary enumeration immediately after M24.')
para('s3',"The distinction between atlas and dynamics now becomes decisive.","The jigsaw's altered joins give the earlier distinction between a description and a transformation a precise test. Translating a trajectory into another chart preserves the motion being described. Changing the conditions which govern that motion can change the trajectory, its attractor or the basins from which an organisation is approached. Chart compatibility supplies none of those changes on its own. In a symbolic encounter, the corresponding question is whether the person has acquired another description of the same expectation or a changed capacity to receive and act. The atlas makes the descriptions comparable; the encounter must establish what has changed in the life.",'W22','M23 already taught phase-space, attractor, basin and bifurcation; M28 supplied chart transitions. Gather these achievements through the jigsaw’s changed office rather than reset the definitions.')
para('s3',"The traveller can put the pieces down.","The traveller can put the pieces down. The picture remains useful, and the journey remains more than the picture can contain. On returning to a familiar place, a formerly hidden face may now be expected; a trusted route may be reconsidered. The acquired form participates in a changed encounter. What happens when that change concerns the person who recognises the form—when a dream, an image or another's answer alters what the person can bear, desire or do?",'W23','Replace the stage direction “the psyche must now be allowed” with the particular question handed to the Pauli and energetic encounters.')
para('s4',"The psychoid names the ordering relation before its division", "The psychoid relation established through the Arche-Topos now has to be encountered from within a life. Number can be grasped inwardly without the objects it subsequently orders; those objects can also resist an interpretation of what the relation means. Exactness constrains the thinking that apprehends it, while apprehension gives the exact relation a place in an inquiry. Psychic and physical determinations retain their different warrants within the common ordering field. What follows concerns how that field becomes significant to the person participating in it.[^s4-01]",'W24','M30 has earned affirmative psychoid priority. Receive it at its full strength and open the new burden of experienced significance rather than re-prove it.')
change('s4',"Jung and Pauli approach this problem through a disagreement worth keeping intact.","Carl Gustav Jung and Wolfgang Pauli approach this problem through a disagreement that changes their proposed common ground.",'W25','Introduce the particular correspondence encounter as changing inquiry rather than instructing the reader to preserve a distinction.')
span('s4',"A person waiting for a reply can inhabit a world", "The image, the complex and the archetype have different offices.","The accusation has remained unsent, but the waiting person still reaches for the screen. Knowing how the rejection story formed has not removed the pull of it. An ambiguous sentence from the earlier exchange acquires its hard edge again; memories of other silences are readily available. A defensive message could provoke the withdrawal it anticipates. Silence could become another test which the other is expected to understand without being told.\n\nThe account examined in §2 can therefore survive its own explanation. Its criterion is now visible, yet it still offers a familiar way to bear the delay and a course to take. The other may actually be withdrawing. The further question concerns the investment through which this one possibility commands attention before an answer arrives, and the change that would let a real answer determine what follows.[^s4-07]\n\n",'W26','Carry forward the actual unsent accusation and criterion inquiry of M23. The new movement begins with their insufficiency to redistribute psychic investment, not with another introduction of the delayed message.')
para('s4',"There is an energetic reason why recognising an error may fail", "The rejection story still offers protection even when its reasoning is exposed. It ends the open waiting, gives the hurt a cause and preserves a practised identity: the one who sees disappointment coming, the one who will not be made a fool of again. The person may understand this service and continue to need it. Relinquishing the story now means meeting the desire and uncertainty it had organised, without yet knowing whether another response will be bearable.",'W27','M23 has established pain/relief and false certainty. Make the added energetic question the persistence of that protection after insight, retaining the distinct next paragraph on libido.')
para('s4',"The means through which a person recognises a world", "The crossed zero first marked an instrument's image occupying the Subject's place. The energetic inquiry has now shown why that substitution can persist after it is understood: a name or description can carry the protection on which conduct has come to depend. A person recognises themselves through it, and the history gathered under the name begins to appear as the source of every new act. The question now reaches the means of that identification—how can their operation become available to the one identifying?",'W28','M16 supplied the first crossed-zero office and M32 its investment. Open M34 from their acquired relation, preserving the complete succeeding seven-step performance.')
span('s4',"The return through a sign becomes integral", "My Gebser encounter brings the demand", "The view itself can now undergo the return which the sign has made possible. Gebser's account of perspective, encountered at the threshold, gave represented depth and the positioned viewer their historical relation. His later attention to time and multiple aspects in painting extends the question: a work can change the conditions of showing, rather than add more objects to the same view.[^s4-32]\n\nIntegral diaphaneity makes earlier structures available through their co-presence. Rational discrimination retains its acquired power while the modes it had treated as superseded can participate in what is received. The psychic reality of an unfamiliar experience and the warrant of its interpretation remain different questions. The change in the person is now decisive: can an experience alter the view's governing terms, or will the admission that those terms are partial become one more way of preserving them?\n\n",'W29','M05 established perspective and integral co-presence; M35 inherits that history and advances into invested conduct and the full resistant Daphne encounter.')
span('s4',"Light enters a room through a window of coloured glass.","MEF gives this work a repeatable articulation.","The coloured window can now be approached from the side of its alteration. Its first appearance at the threshold let a projected image disclose the aperture which formed it; the mathematical return distinguished the Original, the spectral order, the refracting conditions and the situated projection. Bimba, QL, MEF and pratibimba name those different offices. What is prior in being can be later in knowledge: the viewer encounters the image before recognising how it came to appear.[^s4-38]\n\nA pane can now be repositioned. A different angle, material or join changes what passes into the room; moving the viewer changes what can be received. Following a difference back to the appropriate condition makes this a test of transformation, not only transparency. A historical discontinuity must remain a discontinuity; a translation needs its particular limits; a mathematical demonstration and a psychic encounter bring different warrants. The joins retain these relations so that a corrected reading can reach the source, aperture or act which actually requires change.\n\n",'W30','M05 and M30 already give the full optical scene and source assignments. M36 develops intervention and repeatable refraction instead of narrating the window from scratch a third time.')
change('s4','Life/Mind is the whole; Subjective Internality, Objective Internality and World retain knower, means and known offices.','Life/Mind is the whole; Subjective Immediacy, Objective Internality and World retain knower, means and known offices.','W31','Correct the note against the actual pinned A/C opening, which already says Subjective Immediacy. This is not a new terminological ruling or a change to the source.')
reprise('s5','**Objective Internality names','A paradigm ordinarily works','s5-grounding','Grounding recalled: knower, means, known and order of dependence')
for start,end,label,title in [
 ('The Quaternal lens asks','The concrete identities protect','s5-central-lenses','Central: Quaternal × Divine Logos'),
 ('The Causal lens differentiates','<a id="s5-m38-preference-gauge"','s5-actuation-lenses','Actuation: Causal × Scientific'),
 ("AIKit's Logical lens keeps",'The two lenses together make','s5-aikit-lenses','AIKit: Logical × Chronological'),
 ('The Processual lens gives','The person at the centre','s5-factory-lenses','Factory: Processual × Alchemical-Elemental'),
 ('The Phenomenological lens opens','<a id="s5-m41-encounter"','s5-workcell-lenses','Workcell: Phenomenological × Phenomenal'),
 ('The Para Vāk lens asks','Number and meaning are therefore','s5-ql-lenses','QL: Para Vāk × Archetypal-Numerical')]:
    reprise('s5',start,end,label,title)
para('s5','The concrete identities protect',"The Quaternal questions and Divine Logos return now become distinctions an agent can use. Central names the containing locus of authored continuity; a Project names a determinate undertaking; a ProjectCentral carries that undertaking's local ground. A Machine names one material situation, and an AgentProfile names a selected orientation for agency. Control sources concern the rules under which changes are admitted. Moving a project to another machine should not invent another author; changing an agent's profile should not rewrite the project's history; selecting a child project should not silently grant authority over the containing ground. These separations let a retained reason become effective without losing who gave it or what it governs.",'W32','After the full paired teaching in M36, make the pair act through concrete identities and scope rather than introduce a memory-store foil.')
reprise('s5','The formal seed is small enough','This ordered movement matters to practice.','s5-formal-reprise','Formal relations recalled: typed sixfold, inverse parents and eight determinations')
para('s5','This ordered movement matters to practice.',"The ordered movement now has a practical consequence. A source becomes a determinate assertion; the assertion orients an act; the act recurs as a method; the method enters a situated world. A local result can then expose a question about the wider condition. Each transition changes what can be asked and which evidence matters. The previously derived `X/x` keeps capacity and instance distinct; the adjacent Being, Becoming and Knowing/unKnowing pairs, and the complementary Essence, Constitution and Text–Texture folds, let the same undertaking be read through different relations. Nothing requires the earlier moment to be discarded when the later one becomes available.",'W33','Consume the demonstrated formal body in its actual technical work; remove repeated defensive statements about Pauli and the product count from the shared continuation.')
reprise('s5','The older image of a maker, a trap and a pledge','The whole scene distinguishes operations','s5-homer-reprise','The maker and the pledge: full narrative context')
span('s5','The whole scene distinguishes operations','The institutional return now becomes more exact.',"Hephaestus's objection now bears directly on the work's release. Capture and disclosure succeeded, yet Poseidon's first assurance left the maker exposed to a debtor who would be free. The second undertaking changed the bearer of that possible loss, and Hephaestus then used his own power to open the bonds. Hermes's willingness to accept the same captivity had already shown why one visible fact could not supply every witness with one judgment.\n\nThe distinction makes Gate and Recognition more exact. A check can establish a candidate's performance or defect. Accepting the work also requires authority to release it, resources for what remains, and someone answerable for the consequences placed upon others. These offices cannot be generated by the check's accuracy. The change must reach an act, as the changed pledge reached the maker's hands. A release which merely transfers the remaining risk to an unconsulted recipient would preserve the exposure while moving it out of view.\n\n",'W34','Replace repeated whole narration and negative analogies with a consequence earned by the first complete Homeric telling in M22; retain the full source-specific scene for standalone reading.')
reprise('s5',"The distinction allows Jung and Pauli's inquiry", "QL's concrete primitives make that demand workable.",'s5-psychoid-reprise','Pauli and Aion: participation and altered seeing recalled')
change('s5',"<!-- reprise:s5-psychoid-reprise:end -->\n\nQL's concrete primitives", "<!-- reprise:s5-psychoid-reprise:end -->\n\nPauli discovered the blue egg already in his hand before he performed the division. The algebra retained the resulting relation; the dream retained the different histories through which its terms had arrived. Aion's eyewash changed the organ which would receive the next appearance. These acquired differences specify the technological demand: preserve the agent's own contribution to the field it reports, and let a recovered difference change the means of the next inquiry. A system can otherwise inherit the result while concealing both how it was produced and what its production changed.\n\nQL's concrete primitives",'W35','Give the psychoid return one shared technological consequence after its full earlier telling; the optional reprise is the same preserved text, not a competing argument.')
span('s5','This manuscript has undergone a smaller','Self-application gives the mirror its practical depth.',"This manuscript has undergone an inspectable version of the problem. An earlier research response organised the contemporary field around vendors and model families. The author asked for the engineer's encountered difficulties, the omitted institutional middle and the world being made through the tools. The governing unit changed from a model label to an undertaking: each facet had to follow sources, operative distinctions, powers, costs and returned consequences. Recovering the original correction and the full product constitutions made that change possible.[^s5-self-application]\n\nThe same work exposed a more intimate failure. The opening's Subject theorem had been replaced by a concept definition and fluent commentary about its limit. Increasing the commentary left the requested performance absent. Returning to the original defining text and its recorded Subject reappointment restored a definite proposition, its self-application, failed enclosure, productive disclosure, contextual turn and first-person recognition. The source did not merely supply another fact for the old account; it changed what counted as doing the writing. The eight section inquiries returned their own source reconstructions before the present whole-work reading recomposed their relations.\n\nThe resulting technical section follows Hashimoto's changed practice and carries the NHS coordination example through data, categories, permissions, labour and possible revision. Its retry passage supplies a smaller factual check: the inherited report's five layers became seven when the primary documentation was consulted, with fallback distinguished from repetition. The theorem recovery and this correction have different depths, but both can be located in changed prose. Their existence does not supply the author's judgment of the result. It makes the effect of the intervention available to that judgment.\n\n",'W36','Recover the actual failure and repair that led to the eight-section commission, verified in s01’s source-return and defining passage. Distinguish changed criterion from a factual count; do not infer literary success from the existence of a protocol.')
old=re.search(r'^\[\^s5-self-application\]:[^\n]*',texts['s5'],re.M).group()
change('s5',old,old+" The defining-performance example is grounded in Taylor's *The Definition of God — Draft 3*, A01, and the source-backed Subject reappointment recorded with the opening; its original formula and the candidate rendering remain distinguished in the opening's native-source note. The assembly review retains the exact editorial provenance separately.",'W37','Give the added self-application its actual underlying authorial works and semantic owner; keep process receipts separate from public philosophical warrant.')
change('s5','This is the adopted sequence, distinct from the older operational Observe–Verify sequence. Its force is clearest where a trace changes the question.','The sequence becomes consequential where a trace changes the question.','W38','The superseded Observe–Verify wording is a source-history issue already preserved in the return, not an additional lesson the reader needs inside the lens.')
para('s50','The instrument enters a world whose inhabitants',"Setting the instrument down does not end every consequence of its making. Someone will rely upon its answer, someone will live under a decision it helped to make, and someone whose experience never entered its instructions will encounter the effects. The maker's intention has become a power among other powers. A finite work can be complete while the relations it has altered continue. The freedom gained through the work therefore acquires an obligation: the people reached by it must remain able to answer.",'W39','Receive s5’s actual ending without immediately restarting production; distinguish a completed work from its continuing consequences and open Compassion through affected lives.')
change('s50',"The God-definition attempted at the beginning names the whole in which coherent representation participates and which it cannot contain.","The defining performance at the beginning approached the whole from the Subject pole and then from its theological direction: coherent representation participates in the whole which it cannot contain.",'W40','Repair the terminal callback against the actual Subject-led opening, preserving the explicitly recovered two orientations rather than naming the rejected God-led version.')
para('s50',"Indra’s jewel-net offers a contemplative image at this juncture.","The ink mark in Indra's jewel-net became visible through relations already constituting each jewel. The chosen entrance remained particular; the source's optical qualification prevented its comprehensiveness from becoming a claim to possess the whole.[^s50-indra] A community receiving another's work inherits this question of participation. What it can see through a common field and what it is entitled to do within that field remain different powers.",'W41','Remember the complete M10 telling and M22 pledge comparison; carry its acquired question into actual governance rather than retell the image again.')
para('s50',"The return begins as `1/0`.","The return begins as `1/0`. The account has acquired real powers: it can distinguish a failed proof from a changed construction, carry the history of an image, and follow an entrusted act through its consequences. It now tries to include the knowing through which these achievements are understood. Another description appears; understanding occurs again. The successful account meets the same dependence that the opening definition made encounterable, now with a history of exact and consequential work to relinquish as an ultimate self-portrait. Its achieved distinctions remain available.",'W42','Make the final recognition receive the actual mathematical, mythemic and institutional work; preserve the sourceward encounter without repeating a generic introductory non-exhaustion paragraph.')
change('s5','The two lenses together make a practical difference to a failed attempt.','Logical standing and the temporal life of a capacity make a practical difference to a failed attempt.','W43','The analytical continuation must name its own relation when the previously taught lens exposition is folded.')
change('s5','through introversion and extroversion, with sensation','through introversion and extraversion, with sensation','W44','Harmonise the Jungian attitude term with the received source and the complete M36 pair; no substantive office changes.')
para('s2','Psychological accounts illuminate parts of this problem',"Gustave Le Bon approaches collective participation through its power to change how people perceive and act. Carl Gustav Jung brings the question to the responsibility surrendered when the State is treated as a person. The issue is not only what an individual believes: belonging can alter the position from which a belief is held and acted upon.\n\nMattias Desmet proposes a more particular account of the attraction: isolation, loss of meaning and unbound anxiety can make a totalising narrative compelling. Vicky Iakovou contests the explanatory sufficiency of this approach. The institutions and forces through which domination becomes effective have to be identified; susceptibility does not establish who has the power to enforce a classification. The psychological investment and the political arrangement bear upon one another without supplying interchangeable explanations.[^crowds]",'W45','Give the crowd/State/totalisation witnesses an argumentative sequence and preserve the substantive institutional objection, rather than a procession of surnames.')
change('s0',"Watson's Buddhist and psychotherapeutic inquiry", "Gay Watson's Buddhist and psychotherapeutic inquiry",'W46','Identify the contemporary interlocutor at first substantive entry, within the already developed comparison.')
change('s2',"Van Eenwyk's encounter between analytical psychology and nonlinear dynamics", "John R. Van Eenwyk's encounter between analytical psychology and nonlinear dynamics",'W47','First introduction within the particular modelling problem, not an isolated surname.')
for k,t in texts.items():
    assert all(x in t for x in re.findall(r'\[\^([^\]]+)\]:',initial[k]))
