-- Epi-Card QL Conjugate System v1.0.0
-- Portable/offline schema for SQLite 3.45+
-- IDs are UUIDv7 strings generated by the runtime before INSERT.
-- Timestamps are RFC 3339 UTC strings unless a local civil time is explicitly named.
-- JSON columns are TEXT checked with json_valid().

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;

BEGIN;

CREATE TABLE schema_revision (
  version TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL,
  specification_hash TEXT NOT NULL CHECK(length(specification_hash)=64),
  notes TEXT
);

CREATE TABLE actor (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK(kind IN ('human','agent','service','provider')),
  display_name TEXT,
  external_ref TEXT,
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  metadata TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(kind, external_ref)
);

CREATE TABLE pasu (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK(kind IN ('human','collective','anonymous','other')),
  public_handle TEXT,
  private_profile_ref TEXT,
  locale TEXT,
  timezone_default TEXT,
  consent_profile TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(consent_profile)),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE pasu_attribute (
  id TEXT PRIMARY KEY,
  pasu_id TEXT NOT NULL REFERENCES pasu(id) ON DELETE CASCADE,
  attribute_type TEXT NOT NULL,
  value TEXT NOT NULL CHECK(json_valid(value)),
  source_ref TEXT,
  valid_from TEXT,
  valid_to TEXT,
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  external_provider_ok INTEGER NOT NULL DEFAULT 0 CHECK(external_provider_ok IN (0,1)),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  CHECK(valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from)
);
CREATE INDEX pasu_attribute_lookup_idx ON pasu_attribute(pasu_id, attribute_type);

CREATE TABLE pasu_snapshot (
  id TEXT PRIMARY KEY,
  pasu_id TEXT NOT NULL REFERENCES pasu(id),
  snapshot TEXT NOT NULL CHECK(json_valid(snapshot)),
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  source_attribute_ids TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(source_attribute_ids)),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL
);

CREATE TABLE epi_session (
  id TEXT PRIMARY KEY,
  pasu_id TEXT REFERENCES pasu(id),
  parent_session_id TEXT REFERENCES epi_session(id),
  continuation_of_id TEXT REFERENCES epi_session(id),
  session_key_hash BLOB NOT NULL UNIQUE,
  harness TEXT,
  harness_session_ref TEXT,
  started_at TEXT NOT NULL,
  ended_at TEXT,
  timezone TEXT NOT NULL,
  locale TEXT,
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  resumable_state TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(resumable_state)),
  last_event_sequence INTEGER NOT NULL DEFAULT 0,
  created_by TEXT REFERENCES actor(id),
  CHECK(ended_at IS NULL OR ended_at >= started_at)
);

CREATE TABLE temporal_snapshot (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES epi_session(id),
  event_time TEXT,
  observed_at TEXT NOT NULL,
  local_civil_time TEXT,
  timezone TEXT NOT NULL,
  location TEXT CHECK(location IS NULL OR json_valid(location)),
  location_precision TEXT,
  astronomy_provider TEXT,
  astronomy_version TEXT,
  astrology_profile_id TEXT,
  astrology_profile_version TEXT,
  astronomical_facts TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(astronomical_facts)),
  interpreted_contributions TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(interpreted_contributions)),
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  created_at TEXT NOT NULL
);

CREATE TABLE configuration_profile (
  id TEXT NOT NULL,
  version TEXT NOT NULL,
  profile_type TEXT NOT NULL CHECK(profile_type IN ('ql_lens','ql_relation','mapping','disclosure','validation','duration','render','print','interaction','symbol_baseline','audio_tuning','audio_resonator','spatial','provider_policy','other')),
  status TEXT NOT NULL CHECK(status IN ('draft','active','deprecated','retired')),
  register TEXT NOT NULL DEFAULT 'ql_derived' CHECK(register IN ('exact_identity','ql_derived','canonical_symbolic','cross_register','archetypal_reception','open_extension')),
  content TEXT NOT NULL CHECK(json_valid(content)),
  content_hash TEXT NOT NULL CHECK(length(content_hash)=64),
  source_refs TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(source_refs)),
  change_log TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(change_log)),
  author_actor_id TEXT REFERENCES actor(id),
  reviewer_actor_ids TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(reviewer_actor_ids)),
  effective_from TEXT,
  effective_to TEXT,
  created_at TEXT NOT NULL,
  PRIMARY KEY(id,version),
  CHECK(effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from)
);

CREATE TABLE profile_set (
  id TEXT PRIMARY KEY,
  stable_key TEXT NOT NULL,
  version TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('draft','active','deprecated','retired')),
  set_hash TEXT NOT NULL UNIQUE CHECK(length(set_hash)=64),
  description TEXT,
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(stable_key,version)
);

CREATE TABLE profile_set_member (
  profile_set_id TEXT NOT NULL REFERENCES profile_set(id) ON DELETE CASCADE,
  registry TEXT NOT NULL CHECK(registry IN ('configuration','correspondence','projection','provider_capability')),
  profile_id TEXT NOT NULL,
  profile_version TEXT NOT NULL,
  precedence INTEGER NOT NULL DEFAULT 0,
  required INTEGER NOT NULL DEFAULT 1 CHECK(required IN (0,1)),
  PRIMARY KEY(profile_set_id,registry,profile_id,profile_version)
);

CREATE TABLE attractor (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL,
  stable_key TEXT UNIQUE,
  label TEXT NOT NULL,
  description TEXT,
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE attractor_revision (
  id TEXT PRIMARY KEY,
  attractor_id TEXT NOT NULL REFERENCES attractor(id) ON DELETE CASCADE,
  revision_no INTEGER NOT NULL CHECK(revision_no > 0),
  label TEXT NOT NULL,
  description TEXT,
  metadata TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata)),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(attractor_id, revision_no)
);

CREATE TABLE basin_member (
  id TEXT PRIMARY KEY,
  attractor_revision_id TEXT NOT NULL REFERENCES attractor_revision(id) ON DELETE CASCADE,
  stable_local_key TEXT NOT NULL,
  label TEXT NOT NULL,
  description TEXT,
  relation TEXT NOT NULL CHECK(relation IN ('essential','constitutive','contextual','resonant','counterpole','boundary','excluded','unresolved')),
  weight REAL NOT NULL CHECK(weight >= 0 AND weight <= 1),
  register TEXT NOT NULL CHECK(register IN ('exact_identity','ql_derived','canonical_symbolic','cross_register','archetypal_reception','open_extension')),
  rationale TEXT NOT NULL,
  ql_candidate_addresses TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(ql_candidate_addresses)),
  valid_from TEXT,
  valid_to TEXT,
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(attractor_revision_id, stable_local_key, relation),
  CHECK(valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from)
);

CREATE TABLE engagement (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE,
  pasu_snapshot_id TEXT REFERENCES pasu_snapshot(id),
  temporal_snapshot_id TEXT REFERENCES temporal_snapshot(id),
  attractor_revision_id TEXT NOT NULL REFERENCES attractor_revision(id),
  question TEXT,
  intention TEXT,
  active_lens_id TEXT NOT NULL,
  active_lens_version TEXT NOT NULL,
  profile_set TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(profile_set)),
  profile_set_id TEXT REFERENCES profile_set(id),
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','mapping','art_direction','production','review','approved','rendered','published','returned','archived')),
  current_revision INTEGER NOT NULL DEFAULT 1 CHECK(current_revision > 0),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE engagement_projection (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  projection_kind TEXT NOT NULL CHECK(projection_kind IN ('private','shared','public','provider')),
  revision_no INTEGER NOT NULL CHECK(revision_no > 0),
  disclosure TEXT NOT NULL CHECK(disclosure IN ('secret','private','shared','public')),
  provider TEXT,
  purpose TEXT,
  source_revision_manifest TEXT NOT NULL CHECK(json_valid(source_revision_manifest)),
  snapshot TEXT NOT NULL CHECK(json_valid(snapshot)),
  snapshot_hash TEXT NOT NULL UNIQUE CHECK(length(snapshot_hash)=64),
  status TEXT NOT NULL CHECK(status IN ('draft','approved','superseded','expired')),
  expires_at TEXT,
  created_by TEXT REFERENCES actor(id),
  approved_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  approved_at TEXT,
  UNIQUE(engagement_id,projection_kind,provider,purpose,revision_no),
  CHECK((projection_kind='provider' AND provider IS NOT NULL AND purpose IS NOT NULL) OR projection_kind<>'provider')
);
CREATE INDEX engagement_projection_lookup_idx ON engagement_projection(engagement_id,projection_kind,status,revision_no DESC);

CREATE TABLE resource_lock (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  target_kind TEXT NOT NULL,
  target_id TEXT NOT NULL,
  field_path TEXT NOT NULL DEFAULT '',
  lock_type TEXT NOT NULL CHECK(lock_type IN ('semantic','symbol_geometry','palette_token','typography','scene_intent','plate','audio_tuning','render','publication')),
  reason TEXT NOT NULL,
  locked_by TEXT NOT NULL REFERENCES actor(id),
  locked_at TEXT NOT NULL,
  expires_at TEXT,
  released_by TEXT REFERENCES actor(id),
  released_at TEXT,
  release_reason TEXT,
  CHECK(released_at IS NULL OR released_at >= locked_at),
  CHECK(expires_at IS NULL OR expires_at > locked_at)
);
CREATE UNIQUE INDEX resource_lock_active_unique_idx ON resource_lock(engagement_id,target_kind,target_id,field_path) WHERE released_at IS NULL;

CREATE TABLE engagement_session (
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL REFERENCES epi_session(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK(role IN ('originating','continuing','reviewing','publishing')),
  joined_at TEXT NOT NULL,
  PRIMARY KEY(engagement_id, session_id, role)
);

CREATE TABLE talismanic_activation (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL UNIQUE REFERENCES engagement(id) ON DELETE CASCADE,
  intent_statement TEXT NOT NULL,
  recipient_pasu_id TEXT REFERENCES pasu(id),
  activation_scope TEXT,
  activation_at TEXT,
  activation_event TEXT,
  review_at TEXT,
  expiry_condition TEXT,
  return_condition TEXT,
  handling_notes TEXT,
  private_phrase_ref TEXT,
  cadence_or_repetition TEXT CHECK(cadence_or_repetition IS NULL OR json_valid(cadence_or_repetition)),
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL
);

CREATE TABLE activation_witness (
  activation_id TEXT NOT NULL REFERENCES talismanic_activation(id) ON DELETE CASCADE,
  actor_id TEXT NOT NULL REFERENCES actor(id),
  role TEXT NOT NULL DEFAULT 'witness',
  PRIMARY KEY(activation_id, actor_id, role)
);

CREATE TABLE source_form (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  source_kind TEXT NOT NULL,
  declared_arity INTEGER CHECK(declared_arity >= 0),
  native_relations TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(native_relations)),
  source_ref TEXT,
  notes TEXT,
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL
);

CREATE TABLE source_member (
  id TEXT PRIMARY KEY,
  source_form_id TEXT NOT NULL REFERENCES source_form(id) ON DELETE CASCADE,
  ordinal INTEGER,
  member_key TEXT,
  content TEXT NOT NULL CHECK(json_valid(content)),
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  created_at TEXT NOT NULL,
  UNIQUE(source_form_id, ordinal),
  UNIQUE(source_form_id, member_key)
);

CREATE TABLE asset (
  id TEXT PRIMARY KEY,
  sha256 TEXT NOT NULL UNIQUE CHECK(length(sha256)=64 AND sha256 NOT GLOB '*[^0-9a-f]*'),
  uri TEXT NOT NULL,
  media_type TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('source','reference','candidate','canonical','intermediate','rendition','poster','mask','symbol','font_outline','audio_layer','transcript','storyboard','print','knowledge_export','validation_report')),
  byte_length INTEGER CHECK(byte_length IS NULL OR byte_length >= 0),
  width INTEGER CHECK(width IS NULL OR width > 0),
  height INTEGER CHECK(height IS NULL OR height > 0),
  duration_ms INTEGER CHECK(duration_ms IS NULL OR duration_ms >= 0),
  alpha_mode TEXT NOT NULL DEFAULT 'none' CHECK(alpha_mode IN ('none','straight','premultiplied')),
  colour_profile TEXT,
  sample_rate INTEGER CHECK(sample_rate IS NULL OR sample_rate > 0),
  bit_depth INTEGER CHECK(bit_depth IS NULL OR bit_depth > 0),
  rights_status TEXT NOT NULL DEFAULT 'unknown',
  licence TEXT,
  creator_actor_id TEXT REFERENCES actor(id),
  provider TEXT,
  model_id TEXT,
  model_version TEXT,
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  metadata TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata)),
  created_at TEXT NOT NULL
);

CREATE TABLE asset_derivation (
  output_asset_id TEXT NOT NULL REFERENCES asset(id) ON DELETE CASCADE,
  input_asset_id TEXT NOT NULL REFERENCES asset(id),
  relation TEXT NOT NULL CHECK(relation IN ('derived_from','references','contains','mask_of','mixes','continues')),
  operation_name TEXT,
  operation_version TEXT,
  parameters TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(parameters)),
  sequence_no INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(output_asset_id, input_asset_id, relation, sequence_no),
  CHECK(output_asset_id <> input_asset_id)
);

CREATE TABLE recording (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES epi_session(id),
  engagement_id TEXT REFERENCES engagement(id),
  asset_id TEXT NOT NULL REFERENCES asset(id),
  recorded_at TEXT,
  speaker_map TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(speaker_map)),
  consent_state TEXT NOT NULL,
  language_hints TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(language_hints)),
  capture_metadata TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(capture_metadata)),
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  created_at TEXT NOT NULL
);

CREATE TABLE transcript (
  id TEXT PRIMARY KEY,
  recording_id TEXT NOT NULL REFERENCES recording(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  model_id TEXT NOT NULL,
  model_version TEXT,
  language TEXT,
  diarisation_map TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(diarisation_map)),
  transcript_asset_id TEXT REFERENCES asset(id),
  digest TEXT CHECK(digest IS NULL OR length(digest)=64),
  created_at TEXT NOT NULL
);

CREATE TABLE transcript_segment (
  id TEXT PRIMARY KEY,
  transcript_id TEXT NOT NULL REFERENCES transcript(id) ON DELETE CASCADE,
  ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
  speaker_ref TEXT,
  start_ms INTEGER NOT NULL CHECK(start_ms >= 0),
  end_ms INTEGER NOT NULL CHECK(end_ms > start_ms),
  text TEXT NOT NULL,
  confidence REAL CHECK(confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  redacted INTEGER NOT NULL DEFAULT 0 CHECK(redacted IN (0,1)),
  disclosure TEXT NOT NULL DEFAULT 'private' CHECK(disclosure IN ('secret','private','shared','public')),
  UNIQUE(transcript_id, ordinal)
);

CREATE TABLE ql_canonical_position (
  phase TEXT NOT NULL CHECK(phase IN ('bimba','pratibimba')),
  position_index INTEGER NOT NULL CHECK(position_index BETWEEN 0 AND 5),
  address TEXT NOT NULL,
  canonical_unit TEXT NOT NULL,
  canonical_question TEXT NOT NULL,
  structural_role TEXT NOT NULL,
  PRIMARY KEY(phase, position_index),
  UNIQUE(address)
);

INSERT INTO ql_canonical_position VALUES
  ('bimba',0,'P0','Truth','Why?','Ground / source / ever-present origin'),
  ('bimba',1,'P1','Mind','What?','First definition / material articulation'),
  ('bimba',2,'P2','Word','How?','Dynamis / operation / energetic expression'),
  ('bimba',3,'P3','Logos','Who? Which? Whereby?','Pattern / identity / ordering relation'),
  ('bimba',4,'P4','Son','Where? When? Whither?','Context / horizon / situated embodiment'),
  ('bimba',5,'P5','Image','Why-for? Why-not?','Synthesis / integration / manifested whole'),
  ('pratibimba',0,'P0′','Play','Why, through groundlessness?','Abyss, freedom, ungrounded source condition'),
  ('pratibimba',1,'P1′','Need','What hidden form or trace remains?','Residue, evidence, demand, concealed definition'),
  ('pratibimba',2,'P2′','Sacrifice','How does operation meet obstruction and cost?','Resistance, shadow, exchange, necessary loss'),
  ('pratibimba',3,'P3′','Decision','Which pattern operates beneath the recognised pattern?','Cut, counter-pattern, recurrence, governing choice'),
  ('pratibimba',4,'P4′','Love','Which sources and missed contexts reopen the horizon?','Context examining itself, care, embrace, reframing'),
  ('pratibimba',5,'P5′','Work','What crystallises from the conjugate passage?','Verified expression, public work, completed recognition');

CREATE TABLE ql_frame_revision (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  revision_no INTEGER NOT NULL CHECK(revision_no > 0),
  prior_revision_id TEXT REFERENCES ql_frame_revision(id),
  threshold_snapshot TEXT NOT NULL CHECK(json_valid(threshold_snapshot)),
  frame_snapshot TEXT NOT NULL CHECK(json_valid(frame_snapshot)),
  frame_hash TEXT NOT NULL CHECK(length(frame_hash)=64),
  status TEXT NOT NULL CHECK(status IN ('proposed','approved','superseded')),
  created_by TEXT REFERENCES actor(id),
  approved_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  approved_at TEXT,
  UNIQUE(engagement_id,revision_no),
  UNIQUE(engagement_id,frame_hash),
  CHECK(prior_revision_id IS NULL OR prior_revision_id <> id),
  CHECK(status <> 'approved' OR approved_at IS NOT NULL)
);

ALTER TABLE engagement ADD COLUMN current_ql_frame_revision_id TEXT REFERENCES ql_frame_revision(id);

CREATE TRIGGER ql_frame_revision_content_immutable
BEFORE UPDATE OF engagement_id,revision_no,prior_revision_id,threshold_snapshot,frame_snapshot,frame_hash,created_by,created_at ON ql_frame_revision
FOR EACH ROW WHEN OLD.status IN ('approved','superseded')
BEGIN
  SELECT RAISE(ABORT,'Approved/superseded QL frame revision content is immutable');
END;

CREATE TRIGGER ql_frame_revision_delete_guard
BEFORE DELETE ON ql_frame_revision
FOR EACH ROW WHEN OLD.status IN ('approved','superseded')
BEGIN
  SELECT RAISE(ABORT,'Approved/superseded QL frame revision is immutable');
END;

CREATE TABLE ql_position (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  phase TEXT NOT NULL CHECK(phase IN ('bimba','pratibimba')),
  position_index INTEGER NOT NULL CHECK(position_index BETWEEN 0 AND 5),
  address TEXT NOT NULL,
  canonical_unit TEXT NOT NULL,
  canonical_question TEXT NOT NULL,
  structural_role TEXT NOT NULL,
  local_label TEXT,
  local_question TEXT,
  short_summary TEXT,
  extended_articulation TEXT,
  occupancy TEXT NOT NULL DEFAULT 'unknown' CHECK(occupancy IN ('present','latent','missing','unknown','withheld','conflicted','overdetermined')),
  occupancy_reason TEXT,
  salience REAL NOT NULL DEFAULT 0.5 CHECK(salience >= 0 AND salience <= 1),
  revision_no INTEGER NOT NULL DEFAULT 1 CHECK(revision_no > 0),
  approved_at TEXT,
  approved_by TEXT REFERENCES actor(id),
  UNIQUE(engagement_id, phase, position_index),
  UNIQUE(engagement_id, address),
  FOREIGN KEY(phase,position_index) REFERENCES ql_canonical_position(phase,position_index),
  CHECK((phase='bimba' AND address='P'||position_index) OR (phase='pratibimba' AND address='P'||position_index||'′')),
  CHECK(occupancy NOT IN ('missing','withheld','unknown') OR occupancy_reason IS NOT NULL)
);

CREATE TRIGGER ql_position_canonical_insert
BEFORE INSERT ON ql_position
FOR EACH ROW
BEGIN
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM ql_canonical_position c
    WHERE c.phase=NEW.phase AND c.position_index=NEW.position_index
      AND c.address=NEW.address
      AND c.canonical_unit=NEW.canonical_unit
      AND c.canonical_question=NEW.canonical_question
      AND c.structural_role=NEW.structural_role
  ) THEN RAISE(ABORT,'QL canonical identity mismatch') END;
END;

CREATE TRIGGER ql_position_canonical_update
BEFORE UPDATE OF phase,position_index,address,canonical_unit,canonical_question,structural_role ON ql_position
FOR EACH ROW
BEGIN
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM ql_canonical_position c
    WHERE c.phase=NEW.phase AND c.position_index=NEW.position_index
      AND c.address=NEW.address
      AND c.canonical_unit=NEW.canonical_unit
      AND c.canonical_question=NEW.canonical_question
      AND c.structural_role=NEW.structural_role
  ) THEN RAISE(ABORT,'QL canonical identity mismatch') END;
END;

CREATE TABLE ql_relation (
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  source_position_id TEXT NOT NULL REFERENCES ql_position(id) ON DELETE CASCADE,
  target_position_id TEXT NOT NULL REFERENCES ql_position(id) ON DELETE CASCADE,
  relation_type TEXT NOT NULL CHECK(relation_type IN ('adjacent','klein_twist','enriched_return','conjugate','complement','explicate_partition','implicate_partition','physical_triad','contextual_triad')),
  direction TEXT NOT NULL CHECK(direction IN ('directed','undirected')),
  sequence_no INTEGER,
  metadata TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata)),
  PRIMARY KEY(engagement_id, source_position_id, target_position_id, relation_type),
  CHECK(source_position_id <> target_position_id)
);

CREATE TABLE ql_assignment (
  id TEXT PRIMARY KEY,
  ql_position_id TEXT REFERENCES ql_position(id) ON DELETE CASCADE,
  source_member_id TEXT NOT NULL REFERENCES source_member(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK(role IN ('direct','distributed','condensed','supporting','counterposed','unassigned')),
  weight REAL NOT NULL CHECK(weight >= 0 AND weight <= 1),
  register TEXT NOT NULL CHECK(register IN ('exact_identity','ql_derived','canonical_symbolic','cross_register','archetypal_reception','open_extension')),
  rationale TEXT NOT NULL,
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  CHECK((role='unassigned' AND ql_position_id IS NULL) OR (role<>'unassigned' AND ql_position_id IS NOT NULL))
);
CREATE UNIQUE INDEX ql_assignment_unique_idx ON ql_assignment(IFNULL(ql_position_id,''),source_member_id,role);
CREATE UNIQUE INDEX ql_assignment_unassigned_once_idx ON ql_assignment(source_member_id) WHERE role='unassigned';

CREATE TABLE claim (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  ql_position_id TEXT REFERENCES ql_position(id) ON DELETE CASCADE,
  claim_text TEXT NOT NULL,
  register TEXT NOT NULL CHECK(register IN ('exact_identity','ql_derived','canonical_symbolic','cross_register','archetypal_reception','open_extension')),
  confidence REAL CHECK(confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  status TEXT NOT NULL DEFAULT 'proposed' CHECK(status IN ('proposed','accepted','rejected','superseded')),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL
);

CREATE TABLE evidence_link (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  target_kind TEXT NOT NULL CHECK(target_kind IN ('basin_member','claim','ql_assignment','resonance_contribution','symbol_revision','scene_atom','audio_state','audit_position','return_deposit')),
  target_id TEXT NOT NULL,
  source_kind TEXT NOT NULL CHECK(source_kind IN ('source_member','asset','transcript_segment','temporal_snapshot','pasu_attribute','prior_engagement','external_reference')),
  source_id TEXT,
  source_uri TEXT,
  selector TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(selector)),
  relation TEXT NOT NULL,
  register TEXT NOT NULL CHECK(register IN ('exact_identity','ql_derived','canonical_symbolic','cross_register','archetypal_reception','open_extension')),
  note TEXT,
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  CHECK(source_id IS NOT NULL OR source_uri IS NOT NULL)
);

CREATE TABLE return_deposit (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL UNIQUE REFERENCES engagement(id) ON DELETE CASCADE,
  self_implication TEXT NOT NULL,
  remainder TEXT NOT NULL,
  achieved_work TEXT,
  external_implications TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(external_implications)),
  next_ground TEXT NOT NULL,
  next_seed_set TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(next_seed_set)),
  semantic_delta TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(semantic_delta)),
  media_delta TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(media_delta)),
  next_engagement_id TEXT REFERENCES engagement(id),
  loop_profile_id TEXT,
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  CHECK(next_engagement_id IS NULL OR next_engagement_id <> engagement_id)
);

CREATE TABLE correspondence_profile (
  id TEXT NOT NULL,
  version TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('draft','active','deprecated','retired')),
  scope TEXT NOT NULL,
  register TEXT NOT NULL CHECK(register IN ('exact_identity','ql_derived','canonical_symbolic','cross_register','archetypal_reception','open_extension')),
  author_actor_id TEXT REFERENCES actor(id),
  rules TEXT NOT NULL CHECK(json_valid(rules)),
  change_log TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(change_log)),
  effective_from TEXT,
  effective_to TEXT,
  created_at TEXT NOT NULL,
  PRIMARY KEY(id,version),
  CHECK(effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from)
);

CREATE TABLE resonance_contribution (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  ql_position_id TEXT REFERENCES ql_position(id) ON DELETE CASCADE,
  source_system TEXT NOT NULL,
  source_selector TEXT NOT NULL,
  source_value TEXT NOT NULL CHECK(json_valid(source_value)),
  phase REAL CHECK(phase IS NULL OR (phase >= 0 AND phase < 1)),
  register_log2 REAL,
  pulse REAL CHECK(pulse IS NULL OR pulse >= 0),
  amplitude REAL CHECK(amplitude IS NULL OR (amplitude >= 0 AND amplitude <= 1)),
  coherence REAL CHECK(coherence IS NULL OR (coherence >= 0 AND coherence <= 1)),
  bandwidth REAL CHECK(bandwidth IS NULL OR (bandwidth >= 0 AND bandwidth <= 1)),
  polarity REAL CHECK(polarity IS NULL OR (polarity >= -1 AND polarity <= 1)),
  ratio_set TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(ratio_set)),
  elemental_vector TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(elemental_vector)),
  chakra_vector TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(chakra_vector)),
  weight REAL NOT NULL CHECK(weight >= 0 AND weight <= 1),
  register TEXT NOT NULL CHECK(register IN ('exact_identity','ql_derived','canonical_symbolic','cross_register','archetypal_reception','open_extension')),
  rationale TEXT NOT NULL,
  profile_id TEXT NOT NULL,
  profile_version TEXT NOT NULL,
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  FOREIGN KEY(profile_id,profile_version) REFERENCES correspondence_profile(id,version)
);

CREATE TABLE resonance_state (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  ql_position_id TEXT REFERENCES ql_position(id) ON DELETE CASCADE,
  phase REAL NOT NULL CHECK(phase >= 0 AND phase < 1),
  register_log2 REAL NOT NULL,
  pulse REAL NOT NULL CHECK(pulse >= 0),
  amplitude REAL NOT NULL CHECK(amplitude >= 0 AND amplitude <= 1),
  coherence REAL NOT NULL CHECK(coherence >= 0 AND coherence <= 1),
  bandwidth REAL NOT NULL CHECK(bandwidth >= 0 AND bandwidth <= 1),
  polarity REAL NOT NULL CHECK(polarity >= -1 AND polarity <= 1),
  ratio_set TEXT NOT NULL CHECK(json_valid(ratio_set)),
  elemental_vector TEXT NOT NULL CHECK(json_valid(elemental_vector)),
  chakra_vector TEXT NOT NULL CHECK(json_valid(chakra_vector)),
  profile_set_hash TEXT NOT NULL CHECK(length(profile_set_hash)=64),
  calculation_receipt TEXT NOT NULL CHECK(json_valid(calculation_receipt)),
  created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX resonance_state_unique_idx ON resonance_state(engagement_id,IFNULL(ql_position_id,''),profile_set_hash);

CREATE TABLE projection_profile (
  id TEXT NOT NULL,
  version TEXT NOT NULL,
  modality TEXT NOT NULL CHECK(modality IN ('audio','colour','geometry','typography','motion','editing_pace','light_material','spatial')),
  parameters TEXT NOT NULL CHECK(json_valid(parameters)),
  transforms TEXT NOT NULL CHECK(json_valid(transforms)),
  clamps TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(clamps)),
  defaults TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(defaults)),
  inverse_labels TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(inverse_labels)),
  status TEXT NOT NULL CHECK(status IN ('draft','active','deprecated','retired')),
  created_at TEXT NOT NULL,
  PRIMARY KEY(id,version)
);

CREATE TABLE projected_parameter_set (
  id TEXT PRIMARY KEY,
  resonance_state_id TEXT NOT NULL REFERENCES resonance_state(id) ON DELETE CASCADE,
  projection_profile_id TEXT NOT NULL,
  projection_profile_version TEXT NOT NULL,
  modality TEXT NOT NULL,
  parameters TEXT NOT NULL CHECK(json_valid(parameters)),
  calculation_receipt TEXT NOT NULL CHECK(json_valid(calculation_receipt)),
  created_at TEXT NOT NULL,
  FOREIGN KEY(projection_profile_id,projection_profile_version) REFERENCES projection_profile(id,version),
  UNIQUE(resonance_state_id,projection_profile_id,projection_profile_version)
);

CREATE TABLE art_direction_revision (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  revision_no INTEGER NOT NULL CHECK(revision_no > 0),
  palette_tokens TEXT NOT NULL CHECK(json_valid(palette_tokens)),
  typography_signature TEXT NOT NULL CHECK(json_valid(typography_signature)),
  geometry_direction TEXT NOT NULL CHECK(json_valid(geometry_direction)),
  motion_direction TEXT NOT NULL CHECK(json_valid(motion_direction)),
  light_material_direction TEXT NOT NULL CHECK(json_valid(light_material_direction)),
  constraints TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(constraints)),
  locked_paths TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(locked_paths)),
  status TEXT NOT NULL CHECK(status IN ('draft','proposed','approved','superseded')),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(engagement_id,revision_no)
);

CREATE TABLE symbol_family (
  id TEXT PRIMARY KEY,
  stable_key TEXT UNIQUE,
  name TEXT NOT NULL,
  semantic_operation TEXT NOT NULL,
  invariant_grammar TEXT NOT NULL CHECK(json_valid(invariant_grammar)),
  resonance_signature TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(resonance_signature)),
  primary_svg_asset_id TEXT REFERENCES asset(id),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE symbol_relation (
  source_symbol_id TEXT NOT NULL REFERENCES symbol_family(id) ON DELETE CASCADE,
  target_symbol_id TEXT NOT NULL REFERENCES symbol_family(id) ON DELETE CASCADE,
  relation TEXT NOT NULL CHECK(relation IN ('conjugate','inverse','contains','variant','shares_operation','shares_topology','returns_to')),
  weight REAL CHECK(weight IS NULL OR (weight >= 0 AND weight <= 1)),
  rationale TEXT,
  PRIMARY KEY(source_symbol_id,target_symbol_id,relation),
  CHECK(source_symbol_id <> target_symbol_id)
);

CREATE TABLE symbol_revision (
  id TEXT PRIMARY KEY,
  symbol_family_id TEXT NOT NULL REFERENCES symbol_family(id) ON DELETE CASCADE,
  engagement_id TEXT REFERENCES engagement(id),
  revision_no INTEGER NOT NULL CHECK(revision_no > 0),
  resolution_mode TEXT NOT NULL CHECK(resolution_mode IN ('reuse','parameterise','transform','combine','generate_new')),
  grammar TEXT NOT NULL CHECK(json_valid(grammar)),
  canonical_svg_asset_id TEXT REFERENCES asset(id),
  monochrome_svg_asset_id TEXT REFERENCES asset(id),
  status TEXT NOT NULL CHECK(status IN ('candidate','validated','approved','superseded')),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(symbol_family_id,revision_no)
);

CREATE TABLE symbol_state (
  id TEXT PRIMARY KEY,
  symbol_revision_id TEXT NOT NULL REFERENCES symbol_revision(id) ON DELETE CASCADE,
  ql_position_id TEXT NOT NULL REFERENCES ql_position(id) ON DELETE CASCADE,
  transformation TEXT NOT NULL CHECK(json_valid(transformation)),
  svg_asset_id TEXT REFERENCES asset(id),
  alpha_asset_id TEXT REFERENCES asset(id),
  mask_asset_id TEXT REFERENCES asset(id),
  loop_anchor TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(loop_anchor)),
  UNIQUE(symbol_revision_id,ql_position_id)
);

CREATE TABLE storyboard_revision (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  revision_no INTEGER NOT NULL CHECK(revision_no > 0),
  profile TEXT NOT NULL CHECK(profile IN ('base','extended','custom')),
  width INTEGER NOT NULL CHECK(width > 0),
  height INTEGER NOT NULL CHECK(height > 0),
  fps_num INTEGER NOT NULL CHECK(fps_num > 0),
  fps_den INTEGER NOT NULL DEFAULT 1 CHECK(fps_den > 0),
  duration_frames INTEGER NOT NULL CHECK(duration_frames > 0),
  storyboard_asset_id TEXT REFERENCES asset(id),
  status TEXT NOT NULL CHECK(status IN ('draft','approved','superseded')),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(engagement_id,revision_no)
);

CREATE TABLE scene_pair (
  id TEXT PRIMARY KEY,
  storyboard_revision_id TEXT NOT NULL REFERENCES storyboard_revision(id) ON DELETE CASCADE,
  position_index INTEGER NOT NULL CHECK(position_index BETWEEN 0 AND 5),
  order_index INTEGER NOT NULL CHECK(order_index BETWEEN 0 AND 5),
  start_frame INTEGER NOT NULL CHECK(start_frame >= 0),
  duration_frames INTEGER NOT NULL CHECK(duration_frames > 0),
  reciprocity_mode TEXT NOT NULL CHECK(reciprocity_mode IN ('phase_flip','crossfade','interleaved','split_field','masked_reveal','conjugate_cut','audio_visual_exchange')),
  transition_in TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(transition_in)),
  transition_out TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(transition_out)),
  UNIQUE(storyboard_revision_id,position_index),
  UNIQUE(storyboard_revision_id,order_index)
);

CREATE TABLE scene_atom (
  id TEXT PRIMARY KEY,
  scene_pair_id TEXT NOT NULL REFERENCES scene_pair(id) ON DELETE CASCADE,
  ql_position_id TEXT NOT NULL REFERENCES ql_position(id) ON DELETE CASCADE,
  face_order INTEGER NOT NULL CHECK(face_order IN (0,1)),
  intent TEXT NOT NULL CHECK(json_valid(intent)),
  visual_action TEXT NOT NULL,
  camera TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(camera)),
  light_material TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(light_material)),
  generation_plan TEXT NOT NULL CHECK(json_valid(generation_plan)),
  accepted_plate_asset_id TEXT REFERENCES asset(id),
  occupancy TEXT NOT NULL DEFAULT 'unknown' CHECK(occupancy IN ('present','latent','missing','unknown','withheld','conflicted','overdetermined')),
  UNIQUE(scene_pair_id,ql_position_id),
  UNIQUE(scene_pair_id,face_order)
);

CREATE TABLE provider_capability (
  provider TEXT NOT NULL,
  model_id TEXT NOT NULL,
  model_version TEXT NOT NULL,
  capability_version TEXT NOT NULL,
  modalities_in TEXT NOT NULL CHECK(json_valid(modalities_in)),
  modalities_out TEXT NOT NULL CHECK(json_valid(modalities_out)),
  limits TEXT NOT NULL CHECK(json_valid(limits)),
  features TEXT NOT NULL CHECK(json_valid(features)),
  constraints TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(constraints)),
  terms_snapshot_ref TEXT,
  active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
  checked_at TEXT NOT NULL,
  PRIMARY KEY(provider,model_id,model_version,capability_version)
);

CREATE TABLE provider_job (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  model_id TEXT NOT NULL,
  model_version TEXT NOT NULL,
  provider_job_id TEXT,
  operation TEXT NOT NULL,
  request_payload TEXT NOT NULL CHECK(json_valid(request_payload)),
  request_hash TEXT NOT NULL CHECK(length(request_hash)=64),
  status TEXT NOT NULL,
  resume_cursor TEXT CHECK(resume_cursor IS NULL OR json_valid(resume_cursor)),
  response_payload TEXT CHECK(response_payload IS NULL OR json_valid(response_payload)),
  submitted_at TEXT,
  completed_at TEXT,
  UNIQUE(provider,provider_job_id)
);

CREATE TABLE audio_palette_revision (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  revision_no INTEGER NOT NULL CHECK(revision_no > 0),
  reference_hz REAL NOT NULL CHECK(reference_hz > 0),
  ratio_set TEXT NOT NULL CHECK(json_valid(ratio_set)),
  tuning_profile TEXT NOT NULL CHECK(json_valid(tuning_profile)),
  resonator_profile TEXT NOT NULL CHECK(json_valid(resonator_profile)),
  spatial_profile TEXT NOT NULL CHECK(json_valid(spatial_profile)),
  status TEXT NOT NULL CHECK(status IN ('draft','approved','superseded')),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(engagement_id,revision_no)
);

CREATE TABLE audio_state (
  id TEXT PRIMARY KEY,
  audio_palette_revision_id TEXT NOT NULL REFERENCES audio_palette_revision(id) ON DELETE CASCADE,
  ql_position_id TEXT NOT NULL REFERENCES ql_position(id) ON DELETE CASCADE,
  parameters TEXT NOT NULL CHECK(json_valid(parameters)),
  render_asset_id TEXT REFERENCES asset(id),
  analysis TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(analysis)),
  UNIQUE(audio_palette_revision_id,ql_position_id)
);

CREATE TABLE modifier_operation (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  sequence_no INTEGER NOT NULL CHECK(sequence_no >= 0),
  operation_name TEXT NOT NULL,
  operation_version TEXT NOT NULL,
  parameters TEXT NOT NULL CHECK(json_valid(parameters)),
  input_asset_id TEXT NOT NULL REFERENCES asset(id),
  output_asset_id TEXT NOT NULL REFERENCES asset(id),
  deterministic INTEGER NOT NULL CHECK(deterministic IN (0,1)),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(engagement_id,sequence_no,output_asset_id),
  CHECK(input_asset_id <> output_asset_id)
);

CREATE TABLE render_plan (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  storyboard_revision_id TEXT NOT NULL REFERENCES storyboard_revision(id),
  art_direction_revision_id TEXT NOT NULL REFERENCES art_direction_revision(id),
  symbol_revision_id TEXT NOT NULL REFERENCES symbol_revision(id),
  audio_palette_revision_id TEXT NOT NULL REFERENCES audio_palette_revision(id),
  profile TEXT NOT NULL,
  plan TEXT NOT NULL CHECK(json_valid(plan)),
  plan_hash TEXT NOT NULL CHECK(length(plan_hash)=64),
  renderer TEXT NOT NULL,
  renderer_version TEXT NOT NULL,
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(engagement_id,plan_hash)
);

CREATE TABLE rendition (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  render_plan_id TEXT NOT NULL REFERENCES render_plan(id),
  rendition_kind TEXT NOT NULL CHECK(rendition_kind IN ('web_card','master_video','loop_video','poster','audio_master','print_front','print_back','transparent_symbol','social_variant')),
  profile TEXT NOT NULL,
  revision_no INTEGER NOT NULL CHECK(revision_no > 0),
  status TEXT NOT NULL CHECK(status IN ('rendering','candidate','approved','superseded','failed')),
  manifest TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(manifest)),
  created_at TEXT NOT NULL,
  UNIQUE(engagement_id,rendition_kind,profile,revision_no)
);

CREATE TABLE rendition_asset (
  rendition_id TEXT NOT NULL REFERENCES rendition(id) ON DELETE CASCADE,
  asset_id TEXT NOT NULL REFERENCES asset(id),
  role TEXT NOT NULL,
  PRIMARY KEY(rendition_id,asset_id,role)
);

CREATE TABLE action_definition (
  name TEXT NOT NULL,
  version TEXT NOT NULL,
  side_effect TEXT NOT NULL CHECK(side_effect IN ('read','write','generate','render','publish')),
  input_schema_ref TEXT NOT NULL,
  output_schema_ref TEXT NOT NULL,
  required_permissions TEXT NOT NULL CHECK(json_valid(required_permissions)),
  provider_dependencies TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(provider_dependencies)),
  audit_required INTEGER NOT NULL DEFAULT 1 CHECK(audit_required IN (0,1)),
  gate_mode TEXT NOT NULL DEFAULT 'none' CHECK(gate_mode IN ('none','conditional','required')),
  gate_policy TEXT NOT NULL DEFAULT '{"summary":"none","gates":[]}' CHECK(json_valid(gate_policy)),
  idempotency_policy TEXT NOT NULL,
  retry_policy TEXT NOT NULL CHECK(json_valid(retry_policy)),
  transaction_policy TEXT NOT NULL,
  PRIMARY KEY(name,version)
);

CREATE TABLE action_run (
  id TEXT PRIMARY KEY,
  action_name TEXT NOT NULL,
  action_version TEXT NOT NULL,
  request_id TEXT NOT NULL UNIQUE,
  idempotency_key TEXT NOT NULL,
  actor_id TEXT NOT NULL REFERENCES actor(id),
  session_id TEXT REFERENCES epi_session(id),
  engagement_id TEXT REFERENCES engagement(id),
  status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','awaiting_external','awaiting_review','succeeded','failed_retryable','failed_terminal','cancelled')),
  input TEXT NOT NULL CHECK(json_valid(input)),
  output TEXT CHECK(output IS NULL OR json_valid(output)),
  warning_set TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(warning_set)),
  next_actions TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(next_actions)),
  retry_metadata TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(retry_metadata)),
  resume_cursor TEXT CHECK(resume_cursor IS NULL OR json_valid(resume_cursor)),
  started_at TEXT,
  completed_at TEXT,
  created_at TEXT NOT NULL,
  FOREIGN KEY(action_name,action_version) REFERENCES action_definition(name,version),
  UNIQUE(action_name,action_version,idempotency_key)
);

CREATE TABLE action_event (
  id TEXT PRIMARY KEY,
  action_run_id TEXT NOT NULL REFERENCES action_run(id) ON DELETE CASCADE,
  sequence_no INTEGER NOT NULL,
  event_type TEXT NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(payload)),
  created_at TEXT NOT NULL,
  UNIQUE(action_run_id,sequence_no)
);

CREATE TABLE action_gate_evaluation (
  id TEXT PRIMARY KEY,
  action_run_id TEXT NOT NULL REFERENCES action_run(id) ON DELETE CASCADE,
  gate_index INTEGER NOT NULL CHECK(gate_index >= 0),
  evaluation_no INTEGER NOT NULL CHECK(evaluation_no > 0),
  gate_kind TEXT NOT NULL CHECK(gate_kind IN ('provider_disclosure','consent','human_review','human_approval','actor_authorization','account_authorization','prior_approval')),
  gate_stage TEXT NOT NULL CHECK(gate_stage IN ('pre_execute','pre_commit','pre_promote','pre_publish')),
  gate_mode TEXT NOT NULL CHECK(gate_mode IN ('none','conditional','required')),
  when_predicate TEXT NOT NULL,
  when_arguments TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(when_arguments)),
  when_result INTEGER NOT NULL CHECK(when_result IN (0,1)),
  requires_predicate TEXT NOT NULL,
  requires_arguments TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(requires_arguments)),
  requires_result INTEGER NOT NULL CHECK(requires_result IN (0,1)),
  decision TEXT NOT NULL CHECK(decision IN ('not_applicable','passed','blocked')),
  failure_code TEXT,
  context_hash TEXT NOT NULL CHECK(length(context_hash)=64),
  predicate_registry_version TEXT NOT NULL,
  evaluator_version TEXT NOT NULL,
  evaluated_at TEXT NOT NULL,
  UNIQUE(action_run_id,gate_index,evaluation_no),
  CHECK (
    (decision='not_applicable' AND when_result=0)
    OR (decision='passed' AND when_result=1 AND requires_result=1)
    OR (decision='blocked' AND when_result=1 AND requires_result=0)
  ),
  CHECK(decision<>'blocked' OR failure_code IS NOT NULL)
);
CREATE INDEX action_gate_run_stage_idx ON action_gate_evaluation(action_run_id,gate_stage,gate_index,evaluation_no DESC);

CREATE TABLE audit_canonical_position (
  phase TEXT NOT NULL CHECK(phase IN ('bimba','pratibimba')),
  position_index INTEGER NOT NULL CHECK(position_index BETWEEN 0 AND 5),
  audit_role TEXT NOT NULL,
  PRIMARY KEY(phase,position_index),
  UNIQUE(phase,position_index,audit_role)
);

INSERT INTO audit_canonical_position VALUES
  ('bimba',0,'decision_ground'),
  ('bimba',1,'objective_or_candidate_field'),
  ('bimba',2,'proposed_operation'),
  ('bimba',3,'selection_pattern_or_test'),
  ('bimba',4,'situated_constraints'),
  ('bimba',5,'provisional_integrated_outcome'),
  ('pratibimba',0,'ungrounded_assumptions_and_unknowns'),
  ('pratibimba',1,'traces_evidence_and_provenance'),
  ('pratibimba',2,'obstruction_failure_cost_or_sacrifice'),
  ('pratibimba',3,'counter_pattern_or_hidden_bias'),
  ('pratibimba',4,'missed_context_or_wider_horizon'),
  ('pratibimba',5,'verified_work_and_deposited_output');

CREATE TABLE provider_disclosure_manifest (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  action_run_id TEXT REFERENCES action_run(id) ON DELETE SET NULL,
  provider_job_id TEXT REFERENCES provider_job(id) ON DELETE SET NULL,
  projection_id TEXT NOT NULL REFERENCES engagement_projection(id),
  provider TEXT NOT NULL,
  model_id TEXT,
  purpose TEXT NOT NULL,
  transmitted_field_paths TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(transmitted_field_paths)),
  transmitted_asset_ids TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(transmitted_asset_ids)),
  privacy_summary TEXT NOT NULL CHECK(json_valid(privacy_summary)),
  retention_expectation TEXT NOT NULL CHECK(json_valid(retention_expectation)),
  consent_receipt TEXT NOT NULL CHECK(json_valid(consent_receipt)),
  status TEXT NOT NULL CHECK(status IN ('proposed','approved','rejected','used','expired')),
  created_by TEXT REFERENCES actor(id),
  approved_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  approved_at TEXT,
  used_at TEXT,
  CHECK(status NOT IN ('approved','used') OR approved_at IS NOT NULL)
);
CREATE INDEX provider_disclosure_action_idx ON provider_disclosure_manifest(action_run_id);
CREATE INDEX provider_disclosure_job_idx ON provider_disclosure_manifest(provider_job_id);

CREATE TABLE audit_tick (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  action_run_id TEXT UNIQUE REFERENCES action_run(id) ON DELETE CASCADE,
  parent_tick_id TEXT REFERENCES audit_tick(id),
  subject_kind TEXT NOT NULL,
  subject_id TEXT,
  threshold TEXT NOT NULL CHECK(json_valid(threshold)),
  selected_outcome TEXT CHECK(selected_outcome IS NULL OR json_valid(selected_outcome)),
  rejected_candidates TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(rejected_candidates)),
  remaining_uncertainty TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(remaining_uncertainty)),
  semantic_delta TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(semantic_delta)),
  media_delta TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(media_delta)),
  next_ground TEXT CHECK(next_ground IS NULL OR json_valid(next_ground)),
  status TEXT NOT NULL CHECK(status IN ('open','complete','invalidated')),
  created_at TEXT NOT NULL,
  completed_at TEXT,
  CHECK(parent_tick_id IS NULL OR parent_tick_id <> id)
);

CREATE TABLE audit_position (
  id TEXT PRIMARY KEY,
  audit_tick_id TEXT NOT NULL REFERENCES audit_tick(id) ON DELETE CASCADE,
  phase TEXT NOT NULL CHECK(phase IN ('bimba','pratibimba')),
  position_index INTEGER NOT NULL CHECK(position_index BETWEEN 0 AND 5),
  address TEXT NOT NULL,
  audit_role TEXT NOT NULL,
  content TEXT NOT NULL CHECK(json_valid(content)),
  occupancy TEXT NOT NULL DEFAULT 'present' CHECK(occupancy IN ('present','latent','missing','unknown','withheld','conflicted','overdetermined')),
  occupancy_reason TEXT,
  confidence REAL CHECK(confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  register TEXT NOT NULL CHECK(register IN ('exact_identity','ql_derived','canonical_symbolic','cross_register','archetypal_reception','open_extension')),
  UNIQUE(audit_tick_id,phase,position_index),
  UNIQUE(audit_tick_id,address),
  FOREIGN KEY(phase,position_index,audit_role) REFERENCES audit_canonical_position(phase,position_index,audit_role),
  CHECK((phase='bimba' AND address='P'||position_index) OR (phase='pratibimba' AND address='P'||position_index||'′')),
  CHECK(occupancy NOT IN ('missing','withheld','unknown') OR occupancy_reason IS NOT NULL)
);

CREATE TABLE approval (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  target_kind TEXT NOT NULL,
  target_id TEXT NOT NULL,
  approval_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'requested' CHECK(status IN ('requested','approved','rejected','revoked')),
  requested_by TEXT REFERENCES actor(id),
  decided_by TEXT REFERENCES actor(id),
  request_note TEXT,
  decision_note TEXT,
  requested_at TEXT NOT NULL,
  decided_at TEXT
);

CREATE TABLE validation_report (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  target_kind TEXT NOT NULL,
  target_id TEXT NOT NULL,
  validator_name TEXT NOT NULL,
  validator_version TEXT NOT NULL,
  passed INTEGER NOT NULL CHECK(passed IN (0,1)),
  report_asset_id TEXT REFERENCES asset(id),
  receipt TEXT NOT NULL CHECK(json_valid(receipt)),
  created_at TEXT NOT NULL
);

CREATE TABLE validation_finding (
  id TEXT PRIMARY KEY,
  validation_report_id TEXT NOT NULL REFERENCES validation_report(id) ON DELETE CASCADE,
  severity TEXT NOT NULL CHECK(severity IN ('info','warning','error','fatal')),
  code TEXT NOT NULL,
  path TEXT,
  message TEXT NOT NULL,
  evidence TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(evidence))
);

CREATE TABLE okf_export (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  projection_id TEXT NOT NULL REFERENCES engagement_projection(id),
  okf_version TEXT NOT NULL DEFAULT '0.2',
  disclosure TEXT NOT NULL CHECK(disclosure IN ('private','shared','public')),
  bundle_asset_id TEXT NOT NULL REFERENCES asset(id),
  manifest TEXT NOT NULL CHECK(json_valid(manifest)),
  manifest_hash TEXT NOT NULL CHECK(length(manifest_hash)=64 AND manifest_hash NOT GLOB '*[^0-9a-f]*'),
  validation_report_id TEXT REFERENCES validation_report(id),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(engagement_id,projection_id,okf_version,manifest_hash)
);

CREATE TRIGGER okf_export_consistency_insert
BEFORE INSERT ON okf_export
FOR EACH ROW
BEGIN
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM engagement_projection p
    WHERE p.id=NEW.projection_id AND p.engagement_id=NEW.engagement_id
      AND p.status='approved' AND p.projection_kind IN ('private','shared','public')
      AND p.projection_kind=NEW.disclosure
  ) THEN RAISE(ABORT,'OKF export projection mismatch') END;
  SELECT CASE WHEN NEW.validation_report_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM validation_report v
    WHERE v.id=NEW.validation_report_id AND v.engagement_id=NEW.engagement_id AND v.passed=1
  ) THEN RAISE(ABORT,'OKF export validation report mismatch') END;
END;

CREATE TRIGGER okf_export_consistency_update
BEFORE UPDATE ON okf_export
FOR EACH ROW
BEGIN
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM engagement_projection p
    WHERE p.id=NEW.projection_id AND p.engagement_id=NEW.engagement_id
      AND p.status='approved' AND p.projection_kind IN ('private','shared','public')
      AND p.projection_kind=NEW.disclosure
  ) THEN RAISE(ABORT,'OKF export projection mismatch') END;
  SELECT CASE WHEN NEW.validation_report_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM validation_report v
    WHERE v.id=NEW.validation_report_id AND v.engagement_id=NEW.engagement_id AND v.passed=1
  ) THEN RAISE(ABORT,'OKF export validation report mismatch') END;
END;

CREATE TABLE package_export (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  engagement_revision_no INTEGER NOT NULL CHECK(engagement_revision_no > 0),
  projection_id TEXT NOT NULL REFERENCES engagement_projection(id),
  projection_hash TEXT NOT NULL CHECK(length(projection_hash)=64 AND projection_hash NOT GLOB '*[^0-9a-f]*'),
  ql_frame_revision_id TEXT NOT NULL REFERENCES ql_frame_revision(id),
  ql_frame_hash TEXT NOT NULL CHECK(length(ql_frame_hash)=64 AND ql_frame_hash NOT GLOB '*[^0-9a-f]*'),
  profile_set_id TEXT NOT NULL REFERENCES profile_set(id),
  profile_set_hash TEXT NOT NULL CHECK(length(profile_set_hash)=64 AND profile_set_hash NOT GLOB '*[^0-9a-f]*'),
  okf_export_id TEXT NOT NULL REFERENCES okf_export(id),
  disclosure TEXT NOT NULL CHECK(disclosure IN ('private','shared','public')),
  package_asset_id TEXT NOT NULL REFERENCES asset(id),
  sqlite_schema_version TEXT NOT NULL,
  specification_hash TEXT NOT NULL CHECK(length(specification_hash)=64 AND specification_hash NOT GLOB '*[^0-9a-f]*'),
  manifest_schema_id TEXT NOT NULL DEFAULT 'urn:epi-card:schema:package-manifest:1.0.0'
                     CHECK(manifest_schema_id='urn:epi-card:schema:package-manifest:1.0.0'),
  manifest_hash TEXT NOT NULL CHECK(length(manifest_hash)=64 AND manifest_hash NOT GLOB '*[^0-9a-f]*'),
  package_root_sha256 TEXT NOT NULL CHECK(length(package_root_sha256)=64 AND package_root_sha256 NOT GLOB '*[^0-9a-f]*'),
  manifest TEXT NOT NULL CHECK(json_valid(manifest)),
  validation_report_id TEXT NOT NULL REFERENCES validation_report(id),
  created_by TEXT REFERENCES actor(id),
  created_at TEXT NOT NULL,
  UNIQUE(package_root_sha256),
  UNIQUE(engagement_id,projection_id,ql_frame_revision_id,manifest_hash)
);

CREATE TABLE package_export_rendition (
  package_export_id TEXT NOT NULL REFERENCES package_export(id) ON DELETE CASCADE,
  rendition_id TEXT NOT NULL REFERENCES rendition(id),
  package_role TEXT NOT NULL,
  PRIMARY KEY(package_export_id,rendition_id,package_role)
);

CREATE TRIGGER package_export_consistency_insert
BEFORE INSERT ON package_export
FOR EACH ROW
BEGIN
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM engagement e
    WHERE e.id=NEW.engagement_id AND e.current_revision=NEW.engagement_revision_no
      AND e.current_ql_frame_revision_id=NEW.ql_frame_revision_id
      AND e.profile_set_id=NEW.profile_set_id
  ) THEN RAISE(ABORT,'Package engagement revision mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM engagement_projection p
    WHERE p.id=NEW.projection_id AND p.engagement_id=NEW.engagement_id
      AND p.status='approved' AND p.projection_kind IN ('private','shared','public')
      AND p.projection_kind=NEW.disclosure AND p.snapshot_hash=NEW.projection_hash
  ) THEN RAISE(ABORT,'Package projection mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM ql_frame_revision q
    WHERE q.id=NEW.ql_frame_revision_id AND q.engagement_id=NEW.engagement_id
      AND q.status='approved' AND q.frame_hash=NEW.ql_frame_hash
  ) THEN RAISE(ABORT,'Package QL frame revision mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM profile_set s
    WHERE s.id=NEW.profile_set_id AND s.status='active' AND s.set_hash=NEW.profile_set_hash
  ) THEN RAISE(ABORT,'Package profile set mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM okf_export o JOIN validation_report ov ON ov.id=o.validation_report_id
    WHERE o.id=NEW.okf_export_id AND o.engagement_id=NEW.engagement_id
      AND o.projection_id=NEW.projection_id AND o.disclosure=NEW.disclosure
      AND ov.engagement_id=NEW.engagement_id AND ov.passed=1
  ) THEN RAISE(ABORT,'Package OKF export mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM validation_report v
    WHERE v.id=NEW.validation_report_id AND v.engagement_id=NEW.engagement_id AND v.passed=1
  ) THEN RAISE(ABORT,'Package validation report mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM schema_revision s
    WHERE s.version=NEW.sqlite_schema_version AND s.specification_hash=NEW.specification_hash
  ) THEN RAISE(ABORT,'Package specification hash mismatch') END;
END;

CREATE TRIGGER package_export_consistency_update
BEFORE UPDATE ON package_export
FOR EACH ROW
BEGIN
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM engagement e
    WHERE e.id=NEW.engagement_id AND e.current_revision=NEW.engagement_revision_no
      AND e.current_ql_frame_revision_id=NEW.ql_frame_revision_id
      AND e.profile_set_id=NEW.profile_set_id
  ) THEN RAISE(ABORT,'Package engagement revision mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM engagement_projection p
    WHERE p.id=NEW.projection_id AND p.engagement_id=NEW.engagement_id
      AND p.status='approved' AND p.projection_kind IN ('private','shared','public')
      AND p.projection_kind=NEW.disclosure AND p.snapshot_hash=NEW.projection_hash
  ) THEN RAISE(ABORT,'Package projection mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM ql_frame_revision q
    WHERE q.id=NEW.ql_frame_revision_id AND q.engagement_id=NEW.engagement_id
      AND q.status='approved' AND q.frame_hash=NEW.ql_frame_hash
  ) THEN RAISE(ABORT,'Package QL frame revision mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM profile_set s
    WHERE s.id=NEW.profile_set_id AND s.status='active' AND s.set_hash=NEW.profile_set_hash
  ) THEN RAISE(ABORT,'Package profile set mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM okf_export o JOIN validation_report ov ON ov.id=o.validation_report_id
    WHERE o.id=NEW.okf_export_id AND o.engagement_id=NEW.engagement_id
      AND o.projection_id=NEW.projection_id AND o.disclosure=NEW.disclosure
      AND ov.engagement_id=NEW.engagement_id AND ov.passed=1
  ) THEN RAISE(ABORT,'Package OKF export mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM validation_report v
    WHERE v.id=NEW.validation_report_id AND v.engagement_id=NEW.engagement_id AND v.passed=1
  ) THEN RAISE(ABORT,'Package validation report mismatch') END;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM schema_revision s
    WHERE s.version=NEW.sqlite_schema_version AND s.specification_hash=NEW.specification_hash
  ) THEN RAISE(ABORT,'Package specification hash mismatch') END;
END;

CREATE TRIGGER package_export_rendition_consistency_insert
BEFORE INSERT ON package_export_rendition
FOR EACH ROW
BEGIN
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM package_export p JOIN rendition r ON r.id=NEW.rendition_id
    WHERE p.id=NEW.package_export_id AND r.engagement_id=p.engagement_id AND r.status='approved'
  ) THEN RAISE(ABORT,'Packaged rendition mismatch') END;
END;

CREATE TRIGGER package_export_rendition_consistency_update
BEFORE UPDATE ON package_export_rendition
FOR EACH ROW
BEGIN
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM package_export p JOIN rendition r ON r.id=NEW.rendition_id
    WHERE p.id=NEW.package_export_id AND r.engagement_id=p.engagement_id AND r.status='approved'
  ) THEN RAISE(ABORT,'Packaged rendition mismatch') END;
END;

CREATE TABLE publication (
  id TEXT PRIMARY KEY,
  engagement_id TEXT NOT NULL REFERENCES engagement(id) ON DELETE CASCADE,
  rendition_id TEXT NOT NULL REFERENCES rendition(id),
  platform TEXT NOT NULL,
  account_ref TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'prepared' CHECK(status IN ('prepared','awaiting_approval','approved','submitting','processing','published','failed_retryable','failed_terminal','revoked')),
  metadata TEXT NOT NULL CHECK(json_valid(metadata)),
  disclosure_manifest TEXT NOT NULL CHECK(json_valid(disclosure_manifest)),
  approval_id TEXT REFERENCES approval(id),
  remote_publication_id TEXT,
  remote_status TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(remote_status)),
  idempotency_key TEXT NOT NULL,
  prepared_at TEXT NOT NULL,
  submitted_at TEXT,
  published_at TEXT,
  UNIQUE(platform,account_ref,idempotency_key)
);

-- Portable-package validation views. The runtime MUST query these before export/finalisation.
CREATE VIEW ql_frame_validation AS
SELECT e.id AS engagement_id,
       COUNT(q.id) AS total_positions,
       SUM(CASE WHEN q.phase='bimba' THEN 1 ELSE 0 END) AS bimba_positions,
       SUM(CASE WHEN q.phase='pratibimba' THEN 1 ELSE 0 END) AS pratibimba_positions,
       CASE WHEN COUNT(q.id)=12
                  AND SUM(CASE WHEN q.phase='bimba' THEN 1 ELSE 0 END)=6
                  AND SUM(CASE WHEN q.phase='pratibimba' THEN 1 ELSE 0 END)=6
                  AND e.profile_set_id IS NOT NULL
                  AND EXISTS (SELECT 1 FROM ql_frame_revision r WHERE r.id=e.current_ql_frame_revision_id AND r.engagement_id=e.id AND r.status='approved')
            THEN 1 ELSE 0 END AS valid
FROM engagement e
LEFT JOIN ql_position q ON q.engagement_id=e.id
GROUP BY e.id;

CREATE VIEW audit_tick_validation AS
SELECT t.id AS audit_tick_id,
       COUNT(p.id) AS total_positions,
       SUM(CASE WHEN p.phase='bimba' THEN 1 ELSE 0 END) AS bimba_positions,
       SUM(CASE WHEN p.phase='pratibimba' THEN 1 ELSE 0 END) AS pratibimba_positions,
       CASE WHEN COUNT(p.id)=12
                  AND SUM(CASE WHEN p.phase='bimba' THEN 1 ELSE 0 END)=6
                  AND SUM(CASE WHEN p.phase='pratibimba' THEN 1 ELSE 0 END)=6
                  AND t.selected_outcome IS NOT NULL
                  AND t.next_ground IS NOT NULL
            THEN 1 ELSE 0 END AS valid
FROM audit_tick t
LEFT JOIN audit_position p ON p.audit_tick_id=t.id
GROUP BY t.id;

CREATE VIEW action_gate_validation AS
WITH defined AS (
  SELECT ar.id AS action_run_id,
         CAST(j.key AS INTEGER) AS gate_index,
         json_extract(j.value,'$.stage') AS gate_stage
  FROM action_run ar
  JOIN action_definition ad ON ad.name=ar.action_name AND ad.version=ar.action_version
  JOIN json_each(ad.gate_policy,'$.gates') j
  WHERE json_extract(j.value,'$.stage') IN ('pre_execute','pre_commit','pre_publish')
), latest AS (
  SELECT e.*
  FROM action_gate_evaluation e
  WHERE e.evaluation_no=(
    SELECT MAX(e2.evaluation_no)
    FROM action_gate_evaluation e2
    WHERE e2.action_run_id=e.action_run_id
      AND e2.gate_index=e.gate_index
      AND e2.gate_stage=e.gate_stage
  )
), counts AS (
  SELECT ar.id AS action_run_id,
         COUNT(d.gate_index) AS defined_gates,
         SUM(CASE WHEN l.id IS NOT NULL THEN 1 ELSE 0 END) AS evaluated_gates,
         SUM(CASE WHEN l.decision='blocked' THEN 1 ELSE 0 END) AS blocked_gates
  FROM action_run ar
  LEFT JOIN defined d ON d.action_run_id=ar.id
  LEFT JOIN latest l ON l.action_run_id=d.action_run_id AND l.gate_index=d.gate_index AND l.gate_stage=d.gate_stage
  GROUP BY ar.id
)
SELECT action_run_id, defined_gates, evaluated_gates, blocked_gates,
       CASE WHEN defined_gates=evaluated_gates AND blocked_gates=0 THEN 1 ELSE 0 END AS valid
FROM counts;

CREATE VIEW storyboard_validation AS
SELECT sb.id AS storyboard_revision_id,
       COUNT(DISTINCT sp.id) AS scene_pairs,
       COUNT(sa.id) AS scene_atoms,
       COUNT(DISTINCT qp.address) AS ql_addresses,
       CASE WHEN COUNT(DISTINCT sp.id)=6 AND COUNT(sa.id)=12 AND COUNT(DISTINCT qp.address)=12
            THEN 1 ELSE 0 END AS valid
FROM storyboard_revision sb
LEFT JOIN scene_pair sp ON sp.storyboard_revision_id=sb.id
LEFT JOIN scene_atom sa ON sa.scene_pair_id=sp.id
LEFT JOIN ql_position qp ON qp.id=sa.ql_position_id
GROUP BY sb.id;

CREATE INDEX action_run_status_idx ON action_run(status,created_at);
CREATE INDEX action_run_engagement_idx ON action_run(engagement_id,created_at);
CREATE INDEX evidence_target_idx ON evidence_link(target_kind,target_id);
CREATE INDEX transcript_segment_time_idx ON transcript_segment(transcript_id,start_ms,end_ms);
CREATE INDEX scene_atom_position_idx ON scene_atom(ql_position_id);
CREATE INDEX publication_status_idx ON publication(status,prepared_at);

INSERT INTO schema_revision(version,applied_at,specification_hash,notes)
VALUES('1.0.0',strftime('%Y-%m-%dT%H:%M:%fZ','now'),'dfdaa496ef90261ba185510f2b65abde88e0ee6059dfd3fbbd47b7be3b07a902','Packaged against the normative v1.0.0 specification.');

COMMIT;
