from pathlib import Path
import json,os,hashlib
P=Path(__file__).parent
R={r['record_id']:r for r in json.loads((P/'carrier-list.json').read_text())}
N=['encounter-region-name-count','arbitration-hybris-regard-anamnesis','trust-place-logos-nomos-natio-credere','symbol-account-and-trust','homology-and-analogy','apportionment-and-economy']
B={i+1:Path('submission-package/essay/symbolon/episteme/etymologies')/n/'HISTORICAL-BRANCHES.md' for i,n in enumerate(N)}
rows=[]
def add(e,r,slot,body):
 f=B[e]; link=os.path.relpath(R[r]['path'],f.parent)
 rows.append({'path':str(f),'carrier_path':R[r]['path'],'record_id':r,'field':'E'+str(e),'slot':slot,'paragraph':body.replace('@',link),'evidence_register':3,'kind':'branch-companion-return'})
add(1,'history-indian-philosophy','## Chinese facing','The [Indian philosophy history](@) **qualifies** the counting comparison at register 3: enumerated functions, a referent qualified by exclusion and contracted powers have distinct positive offices. Their separate Sāṃkhya, Buddhist and Śaiva witnesses prevent the counting branch from acquiring an imagined common ancestry. Recognition returns the achieved discrimination with its source relation intact.')
add(1,'dossier-indian-philosophy','## Native field','The [Indian philosophy dossier](@) **extends** the register-3 naming relation through speech’s formative and personed acts. A sound-name can recur while speaker, addressee and circumstance change. The returned account must retain which bearer and contrast make this use exact; Greek, Sanskrit and modern analytic attribution remain separate.')
add(1,'dossier-zero-reception','## Native field','The [zero-reception dossier](@) **historicises** the receiving medium and rule that let a sign count. Positional mark and arithmetic operand retain different permissions; Gerbert and Salem remain independent source tasks. Nothaft’s corrective abstract changes a modern story about reception, demonstrating how Count-to-Account can receive an actual source correction without altering a separately established arithmetic result.')
add(2,'history-psychology','## Institutional return','The [psychology history](@) **historicises** recognition through the distinct scopes of ego, complex and symbolic totality. Its institutional comparison also returns a qualification at register 3: a changed psychic relation does not itself redistribute an office’s power, while an institutional change need not dissolve the affect sustaining it. Anamnesis keeps both histories effective.')
add(2,'history-language-law-nation-centralisation','## Regard:','The [language–law–nation development](@) **historicises** the deciding office through twelve situated branches. A language’s judicial standing, the work of translation and the exclusions of an inherited national alignment can have different histories. At register 3, the consequence must reach the authority able to alter its criterion; one document’s language rule does not certify every branch’s enforcement.')
add(2,'history-language-symbol-dialogue','## Anamnesis,','The [language and dialogue development](@) **extends** Regard at register 3 through the reply that can change interpretation. Lacan’s address and Bohm’s suspended assumptions have different practices and sources. The return concerns a changed hearing or question, not merely another utterance recorded beneath the same frame.')
add(2,'history-technology-politics','## Register 4','The [technology–politics development](@) **historicises** the difference between disclosure and changed jurisdiction. Its institutions, training procedures and commons proposal retain their dates and evidence classes. At register 3, a returned cost or correction must identify the rule, evaluator or commission it can change; the existence of a design report does not complete that intervention.')
add(3,'history-language-law-nation-centralisation','## Rings,','The [developed twelve-branch history](@) **historicises** the whole tree through its actual documentary yield. It distinguishes incorporation from textual transmission, literary from administrative languages, national from transregional formations, and inherited categories from their later institutional or computational use. Its return to Natio and Credere retains the particular bearer, exclusion and undertaking; branches with incomplete witnesses remain exact tasks within the developed history.')
add(3,'dossier-indian-philosophy','### Nomos /','The [Indian philosophy dossier](@#2--speech-forms-a-world-which-can-answer-its-speaker) **compares** Vāk and Logos through the formative and personed act of articulation, with Greek attestation and Śaiva textual attribution kept distinct.')
add(4,'history-language-symbol-dialogue','## Reliance and','The [language, symbol and dialogue development](@) **historicises** the passage from an articulated sign to the practices through which it is used and answered. Reference, rule-following, situated address and suspended assumption retain different carriers. At register 3, the received account owes those conditions to its next use rather than treating a shared word for language as their common source.')
add(4,'history-zero-subject-advent','## Reckoning,','The [zero–subject development](@) **historicises** the authorial braid of two admissions. A sign acquires arithmetic powers; a represented psychic or perspectival condition acquires an investigative office. Symbol answers to source at register 3 by preserving each achievement and its distinct history. Integral return does not turn every earlier token into the final Symbol.')
add(4,'dossier-formal-limit','<a id="reference-38','The [formal-limit dossier](@#e3-e4-consumer-return) **qualifies** the Trust branch through separate consequences of formation, derivability, elucidation and predication. Their conditions remain available for inquiry. The further undertaking of using an examined account belongs to register 3 and cannot be manufactured by a shared word for limit.')
add(4,'dossier-indian-philosophy','## Branches kept','The [Indian philosophy dossier](@#50--the-next-act-must-inherit-the-return) **extends** the source-distinct Indian comparison into the full functional return cycle; E4’s four operations retain their distinct burdens.')
add(4,'dossier-bohm',None,'The [Bohm dossier](@) **historicises** the sources of the dialogical comparison: physical interpretation, the dated 1975 conversation, an independently admitted handout and SEED’s later programme retain separate carriers. Their register-3 return asks whether a disclosed assumption and a contributor’s correction can change the next shared question while preserving the originating authority.')
add(4,'dossier-process',None,'The [process dossier](@) **qualifies** Account re-entry at register 3 through qualitative succession, concrescence, biological production, formal self-reference and symbolic transformation. Each return states its own changed condition. A later record is not thereby lived duration, and a self-editing instrument is not thereby an autopoietic production network.')
add(4,'history-process-systems-science',None,'The [process-science history](@) **historicises** those distinct continuations through their selected editions, practices and instruments. Its chronology does not assert a single chain of influence. The achieved account returns with the object and transformation each source actually permits another inquiry to investigate.')
add(4,'lens-baudrillard','## Reliance and','The [Baudrillard lens](@) **qualifies** the record/source distinction at register 3 by asking how an account helps produce what it then describes. The three historical orders and four image phases keep different purposes; the symbolic’s reversibility does not promise benign reconciliation. The analysis itself must remain capable of receiving a source correction.')
add(5,'history-ancient-philosophy','## #2 —','The [ancient-philosophy development](@#ancient-tension) **historicises** differing agreement in B51 through its transmitted wording, physical reading and separately argued Homeric allusion. The bow’s tension and an exact tuning ratio have different objects. This register-3 comparison gives the Greek agreement branch a material test without inventing historical transmission between its witnesses.')
add(5,'dossier-formal-limit','## #3 —','The [formal-limit dossier](@#eckhart-qualified-predication) **extends** the focal and qualified branch at register 3 through the respect under which a predicate holds. Cusa’s theological approximation and Eckhart’s predication do not become Gödelian unprovability; each returns its own warranted continuation. The comparison preserves positive inquiry while narrowing attribution to its actual source.')
add(5,'history-mathematics','## #5→0 —','The [mathematics development](@) **historicises** exact invariants through their transformations. A lifted loop retains winding, alternation with a shift yields its matrix relation, and temperament adjusts intervals under a chosen criterion. At register 3, these different achievements qualify what the receiving comparison can preserve; their common language of return supplies no identity of mathematical objects.')
add(5,'dossier-jung-pauli-psychoid','## #5→0 —','The [Jung–Pauli dossier](@) **historicises** the research boundary through disagreement within the correspondence. Pauli’s demand for neutral language, Jung’s psychoid clarification and refusal of disciplinary absorption change what a later account can attribute to either speaker. Their numbered dreams and physical quantities remain different objects; the crossing is a research question rather than a demonstrated common cause.')
add(5,'history-myth',None,'The [myth development](@) **historicises** the whole telling’s corrective office: dangerous genealogy, unreported payment and a contemplative simile’s own limit each change an otherwise convenient comparison. At register 3, the source’s aftermath must be able to revise the reading. Mythic geography and temporal reception remain distinct from Neumann’s shared structuration.')
add(6,'history-technology-politics','## #4 —','The [technology–politics development](@#commons-and-responsible-return) **historicises** apportioned authority through named institutional and technical operations. Training a comparison, delegating work and proposing a commons distribute different powers. Its register-3 return identifies who performs, who benefits and who bears cost, while report claims remain distinct from observed implementation.')
add(6,'dossier-oi-technical-responsibility',None,'The [O:I dossier](@#oi-commons-and-return) **extends** the returned share at register 3 through source, projection, contribution and acceptance. A shared artifact can change another local field without transferring source ownership; refusal and correction rights remain effective parts of the distribution. The six constructor checks retain their bounded scope beside the wider architectural undertaking.')
# Other missing carrier-side E relations, expressly developed in the received body/proposals.
backs=[('history-language-symbol-dialogue',2,'<a id="language-selection">','The history **returns-to** [Con-text-through-Diaphaneity](@) through the assumption that becomes available for inquiry in dialogue. A participant’s reply can alter what the question asks and how its answer is judged. This register-3 consequence retains the distinct practices of address and suspension; their source histories do not establish a single procedure or guaranteed result.','con-text-through-diaphaneity'),('history-mathematics',6,'## #5→0 —','The history **returns-to** [Measure as an apportioned criterion](@) through the selected unit and purpose that make commensuration exact. Tuning a cycle and retaining an octave-completing factor keep different operations; a comparison class and reference policy likewise keep different roles. At register 3, a disputed result must return to the particular measure it uses rather than to an unspecified ideal of greater precision.','measure-is-an-apportioned-criterion'),('dossier-zero-reception',5,'## #5→0 —','The dossier **returns-to** [E5’s research boundary](@) through the difference between a historically instituted signifying position and the native subject-condition. Their comparison names the particular relation without treating ordinal succession or an attractive reception story as a substitute for the missing textual witness. This register-3 discipline lets an attribution change while the independently derived operation retains its standing.','research-boundary'),('dossier-oi-technical-responsibility',1,'<a id="oi-evidence-standing">','The dossier **returns-to** [Count-through-Countenance](@) through a participant able to answer beyond an attributed profile. A Contribution’s declared basis and an Encounter’s mediated record make acts examinable; they do not certify the participant’s understanding or consent. Count-to-Account must retain the route by which a reply can change its classification, permission or subsequent use.','count-through-countenance'),('dossier-oi-technical-responsibility',5,'<a id="oi-commons-and-return">','The dossier **returns-to** [E5’s research boundary](@) through the exact scope of each technical comparison. Constructor validation, an acceptance architecture, a three-office proposal and a functional return cycle require different tests. The successful six checks remain valid within their scope while leaving source authentication, learning and phenomenal localisation separately unestablished.','research-boundary')]
for r,e,slot,text,a in backs:
 f=Path(R[r]['path']);w=B[e].with_name('WHOLE-FIELD.md');text=text.replace('@',os.path.relpath(w,f.parent)+'#'+a)
 rows.append({'path':str(f),'carrier_path':str(f),'record_id':r,'field':'E'+str(e),'slot':slot,'paragraph':text,'evidence_register':3,'kind':'additional-carrier-return'})
# Exact user-specified proposals, within correct existing operation sections.
for fname,allowed in [('T22-taylor-parent-proposals.json',{4}),('T22-maya-parent-proposals.json',{2,5})]:
 for r in json.loads((Path('working/p2-enrichment/receipts')/fname).read_text()):
  if not r['target'].endswith('WHOLE-FIELD.md'):continue
  e=next(i for i,p in B.items() if str(p.with_name('WHOLE-FIELD.md'))==r['target'])
  if e not in allowed:continue
  rows.append({'path':r['target'],'field':'E'+str(e),'record_id':'taylor-authored-images' if e==4 else 'maya-eye-veil-frame-horizon','slot':{4:'## #2 —',2:'## A determination carried',5:'## #5→0 —'}[e],'paragraph':r['exact_paragraph'],'evidence_register':3,'kind':'exact-released-proposal'})
(P/'companion-additions.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
paths=sorted({r['path'] for r in rows});manifest=[]
for i,s in enumerate(paths):
 f=Path(s);t=f.read_text();b=t.encode();snap=f'before/companion-{i:02}.md';(P/snap).write_bytes(b);manifest.append({'path':s,'sha256':hashlib.sha256(b).hexdigest(),'snapshot':snap})
 for r in rows:
  if r['path']!=s:continue
  assert r['paragraph'] not in t
  if r['slot']:
   assert t.count(r['slot'])==1,(s,r['slot']);t=t.replace(r['slot'],r['paragraph']+'\n\n'+r['slot'],1)
  else:t=t.rstrip()+'\n\n'+r['paragraph']+'\n'
 f.write_text(t)
(P/'companion-before.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Applied',len(rows),'companion/reciprocal/proposal paragraphs',len(paths),'files')
