from pathlib import Path
import json,os,hashlib
P=Path(__file__).parent
R={r['record_id']:r for r in json.loads((P/'carrier-list.json').read_text())}
N=['encounter-region-name-count','arbitration-hybris-regard-anamnesis','trust-place-logos-nomos-natio-credere','symbol-account-and-trust','homology-and-analogy','apportionment-and-economy']
E={i+1:Path('submission-package/essay/symbolon/episteme/etymologies')/n/'WHOLE-FIELD.md' for i,n in enumerate(N)}
slots={1:'## #3 —',2:'## A determination carried',3:'### Epi-Logos',4:'## #5→0 —',5:'## #4 —',6:'## #3 —'}
ops={1:'Name-through-Count; Count-to-Account',2:'Con-text-through-Diaphaneity; Resolution-in-Reconciliation',3:'Credere after situated and instituted account',4:'Account re-enters source-field',5:'Research boundary and preserved respect',6:'Measure is an apportioned criterion'}
rows=[]
def add(e,r,label,body,slot=None,op=None,anchor=''):
 f=Path(R[r]['path']);link=os.path.relpath(f,E[e].parent)+('#'+anchor if anchor else '')
 text=f'The [{label}]({link}) **'+('historicises' if r.startswith('history-') else 'extends')+'** '+body
 rows.append(dict(record_id=r,field='E'+str(e),field_path=str(E[e]),carrier_path=str(f),operation=op or ops[e],evidence_register=3,paragraph=text,slot=slot or slots[e],status='additional-declared-return'))
add(1,'history-language-symbol-dialogue','language and dialogue history','Name-through-Count through the circumstance which makes a repeated expression apply to this bearer. Its later Wittgenstein inquiry locates use in practice, while Lacan’s address retains speaker, room and audience. At register 3, Count-to-Account returns that determining situation with the telling: an addressee must remain able to correct the terms of the address.','<a id="evidence-registers">',anchor='language-account-return')
add(1,'history-mathematics','mathematics history','Name-through-Count at register 3 by distinguishing a named absence from the rules admitting an arithmetic participant. Its subsequent calculations retain their domain, selected unit and forbidden inference. Count-to-Account returns those conditions to the next user, including the difference between an attention distribution and a selected index.','<a id="evidence-registers">')
add(1,'history-technology-politics','technology–politics history','Count-to-Account at register 3 through the difference between a recorded score and the conditions under which it governs action. Dataset, comparison class, evaluator and permission have different offices. Returning their provenance makes an output attributable; a subsequent objection must still be able to reach the office that can change its use.','<a id="evidence-registers">',op='Count-to-Account',anchor='preference-training-and-delegation')
add(1,'history-zero-subject-advent','zero–subject history','Name-through-Count at register 3 through admission into an operative vocabulary. Zero acquires specific arithmetic permissions; a disciplinary account makes psychic processes available for investigation. The two histories keep their objects and source footing distinct, and the represented item does not take over the determining capacity through which it becomes addressable.')
add(1,'dossier-oi-technical-responsibility','O:I dossier','Count-through-Countenance and Count-to-Account at register 3 through an attributed participant whose response exceeds a stored profile. Contribution, metric and Encounter retain contributor, basis and mediation without certifying understanding or endorsement. The next account must give a correction an address at the source, criterion or permission it challenges.','<a id="evidence-registers">',op='Count-through-Countenance; Count-to-Account',anchor='oi-source-projection-contribution-route')
add(2,'history-indian-philosophy','Indian philosophy history','Criterion-through-Distinction through the effective limits of finite knowledge and agency, and Resolution-in-Reconciliation through recognition of their source relation. At register 3, Māyā’s bounded competence precedes its possible absolutisation. Recollection, Śaiva recognition and psychological integration keep different objects and histories; the returned particular retains its acquired powers.')
add(2,'history-language-law-nation-centralisation','language–law–nation history','Arbitration-in-Crisis through the institution that makes a linguistic form consequential. Con-text-through-Diaphaneity requires excluded speakers, access costs and contrary evidence to reach its deciding office; Resolution-in-Reconciliation returns the settlement with that history active. This register-3 operation has twelve situated branches, whose unequal documentary coverage remains explicit rather than being repaired by one universal national chronology.',anchor='historical-anamnesis')
add(2,'history-language-symbol-dialogue','language and dialogue history','Con-text-through-Diaphaneity at register 3 through participants able to expose a speaking position’s assumptions. Bohm’s suspension, Lacan’s address and the later technical criterion have different practices and warrants. Regard requires the answering voice to affect the terms of interpretation; logging another utterance under an immune frame does not perform that change.',op='Con-text-through-Diaphaneity → Regard',anchor='language-dialogue')
add(2,'history-mathematics','mathematics history','Con-text-through-Diaphaneity at register 3 where a preference result discloses its comparison conditions. A reward’s additive gauge and DPO’s reference policy have different offices: invariance under the former does not license changing the latter as though nothing changed. Regard sends a relevant correction to the criterion or commission, and the next calculation retains that revision’s history.')
add(2,'history-myth','myth history','Arbitration-in-Crisis through the tribunal that receives Hephaestus’s display. Evidence of capture, spectators’ desire and an accepted surety do different work; the maker’s eventual release changes the situation. At register 3, Regard asks whether a represented participant can reach the governing measure. The telling’s public exposure alone supplies neither reconciliation nor payment.')
add(2,'history-technology-politics','technology–politics history','Resolution-in-Reconciliation at register 3 through a technical decision returned with its governing circumstances. Psychological mass formation and an institution’s coercive offices remain distinct; a training pipeline and a commons proposal likewise require different evidence. A second use must show which source, rule, evaluator or commission was retained or changed, beyond the availability of a new explanation.',anchor='commons-and-responsible-return')
add(2,'history-zero-subject-advent','zero–subject history','Con-text-through-Diaphaneity at register 3 through a perspective that discloses the viewer’s own invested situation. Gebser’s cultural account and Taylor’s crossed-zero reading retain different authorship. The returned account can change its criterion while preserving the mental-rational achievement; more represented context alone does not establish that the judging office has become answerable.')
add(2,'dossier-jung-pauli-psychoid','Jung–Pauli dossier','Resolution-in-Reconciliation at register 3 through an interpretation revised by the actual correspondence. Pauli’s p.107 proposal, Jung’s p.127 account and Pauli’s p.159 criticism require different speakers and inferences. A second reading that appends those locators but continues to claim disciplinary fusion has failed to receive the correction. Anamnesis retains the disagreement as part of the resulting account.')
add(2,'dossier-oi-technical-responsibility','O:I dossier','Arbitration-in-Crisis, Regard and recollective return at register 3 through a distinction between accepting a contribution and accepting it as source. A Projection may diverge locally or propose a source revision; only the source’s authorised process accepts the latter. Returned evidence can challenge the commission without acquiring ownership merely by entering the shared field.',anchor='oi-source-projection-contribution-route')
add(3,'history-mathematics','mathematics history','the Topos–Logos–Credere passage at register 3 through the reader, notation and rule already relied upon in calculation. Examination identifies the actual algebra, training objective or reference policy. Renewed use remains an undertaking after that inquiry; a confidence score cannot perform entrustment for the person who will bear its consequence.')
add(3,'history-myth','myth history','Credere at register 3 through the change from Poseidon’s first assurance to his personal contingent liability. Hephaestus accepts and releases; later payment remains unreported. Bride-gifts, adulterer’s fine and surety retain different grounds. The narrated undertaking makes continuation possible without turning Homer into a source of the Latin field’s lexical descent.')
add(3,'history-technology-politics','technology–politics history','Credere at register 3 by keeping the bearer of reliance beside an inspectable technical result. A specified score can be reproduced while the office responsible for using it remains unanswerable. The proposed commons therefore owes a route for refusal, revised permission and recommissioning; the report’s design and its historical comparisons do not certify that route as implemented.',anchor='commons-and-responsible-return')
add(3,'history-zero-subject-advent','zero–subject history','Nomos and Credere at register 3 through the institutional life of an acquired sign. A reference can genuinely govern local comparison while remaining dependent upon wider sources. A correction must reach the authority able to revise that reference or its use; the returned sign retains its exact office and the undertaking involved in using it again.')
add(3,'dossier-formal-limit','formal-limit dossier','Fides and Credere at register 3 as different relations to inquiry. Reliance on language, witness and method is already enacted before their examination; an examined undertaking can then be entrusted again. Gödel’s hypotheses, a predication’s respect and a native performed return remain different warrants. An unproved proposition does not acquire credibility from another account’s limit.',anchor='e3-e4-consumer-return')
add(3,'dossier-indian-philosophy','Indian philosophy dossier','Logos and Epi-Logos at register 3 through speech that forms a circumstance and receives a reply. Vāk’s formative, mental and uttered offices remain distinct; I, you and it exchange positions without making context a fourth pronoun. The achieved account returns with speaker, addressee and source relations active. Greek attestation and Śaiva attribution keep independent tasks.','## #3 —',op='Logos; Epi-Logos')
add(3,'dossier-zero-reception','zero-reception dossier','Credere at register 3 through reliance on a translation within its stated scope. Gerbert’s numerical apparatus and the Salem manuscript require different primary recoveries; Nothaft’s corrective abstract cannot certify an unread medieval case. The reader can use the acquired arithmetic while keeping those boundaries and a consequential route for later correction.')
add(3,'dossier-oi-technical-responsibility','O:I dossier','the full Fides–Topos–Logos–Nomos–Natio–Credere circuit at register 3. A contribution enters an inherited world of records, translations and permissions; its account identifies a situated author and commission; source acceptance has an authorised office; renewed reliance follows examination. These relations keep their six offices and do not become six product names or one shared historical descent.',anchor='oi-source-and-commission')
add(4,'history-mathematics','mathematics history','Trust and Account re-entry at register 3 through a result whose exactness includes its conditions. A source correction can change a permitted inference, and a changed reference policy can change an optimisation problem. The returned calculation retains what was proved under the earlier conditions while making its next use answerable to their revision.')
add(4,'history-myth','myth history','all four E4 operations at register 3 through different whole movements. Hephaestus’s display requires a further undertaking for release; Huayan’s net returns its own simile-limit; Taylor’s mirror makes the account a condition of its next encounter. Trust remains a personed commitment, optical inclusion remains a contemplative likeness, and the instrument’s initiated return remains distinct from its mere efficacy.')
add(4,'history-psychology','psychology history','Account re-entry at register 3 through an image which changes the interpreter and therefore its own later field. Jung’s ego/Self distinctions, Neumann’s morphology and Gebser’s cultural reading retain separate objects and times. The next interpretation must receive the altered relation rather than enlarge an immune ego or institution; an observed psychological or technical outcome still needs its own evidence.')
add(4,'history-technology-politics','technology–politics history','Account re-entry at register 3 by distinguishing what an instrument represented from what its use subsequently changed. Training, institutional classification and a governed local Bimba have different causal offices. A returned source or affected participant must be able to alter the responsible criterion or permission. The history keeps native claim standing distinct from the proposed architecture’s implementation.',anchor='world-agency-and-local-original')
add(4,'dossier-formal-limit','formal-limit dossier','Trust at register 3 through a source-bound account whose use retains its conditions. A formation restriction, relative unprovability, saying/showing and qualified predication support different continuations. Investigation makes those distinctions available; reliance carries the examined account into an act while preserving correction and refusal. No single mathematical limit supplies that undertaking.','## #4 —',op='Trust keeps the return route active',anchor='e3-e4-consumer-return')
add(4,'dossier-jung-pauli-psychoid','Jung–Pauli dossier','Account re-entry at register 3 when a corrected attribution changes the receiving interpretation. The adopting discipline’s required transformation and Jung’s refusal of absorption remain a disagreement within the correspondence. Its retention makes the next account more exact; the source is not honoured by preserving a claim of fusion beneath newly appended citations.')
add(4,'dossier-indian-philosophy','Indian philosophy dossier','Account re-entry at register 3 through the full functional return: retain the selected claim and excluded field, expose judgment’s conditions, perform a counter-reading, state the unresolved limit, and identify what changes in the next act. Source, generation and evaluation keep their distinct offices. This constructive comparison does not assign software modules to Śaiva deities or certify artificial phenomenality.')
add(4,'dossier-zero-reception','zero-reception dossier','Symbol answering to source at register 3 through an actual interpretive correction. Nothaft’s subtitle and abstract challenge a modern legend rather than warrant it. Changing that attribution changes the next historical account while preserving zero’s independently warranted arithmetic powers. Gerbert, Salem and Rotman retain their separately named passage tasks.','## #2 —',op='Symbol answers to source')
add(4,'dossier-oi-technical-responsibility','O:I dossier','all four source-circuit operations at register 3. A Projection identifies the source it claims to bear; an account retains local originality and wider dependence; an undertaking leaves recourse and refusal possible; acceptance or divergence changes what a later Projection inherits. The six constructor probes establish bounded record behaviour, not the completed source-return state machine.',anchor='oi-source-projection-contribution-route')
add(4,'lens-baudrillard','Baudrillard lens','Account not replacing source at register 3 through the difference between a model’s efficacy and fidelity. Three historical orders remain distinct from four image phases; symbolic reversibility remains distinct from a promise of benign dialogue. The analysis must itself receive what its explanatory frame excludes. A real local Bimba retains its source-dependence, and the native third motion asks a consequence to revise the account’s criterion rather than merely feed its next output.','## #3 —',op='Account does not replace source; Account re-enters source-field')
add(5,'history-psychology','psychology history','the research boundary at register 3 through three source-distinct objects: Pauli’s mathematical dream, Lacan’s formal transmission and Taylor’s native X/x. A repeated mark or numeral does not identify their methods. The dynamical comparison likewise needs a stated system before a psychic pattern can be claimed as a literal basin; the symbolic transformation retains its Argued office independently.')
add(5,'history-technology-politics','technology–politics history','comparative precision at register 3 by distinguishing reward gauge, reference policy, attention weights, selected index, compatibility energy and learning loss. Their different jobs remain visible when the account reaches psychic valuation or instituted authority. The common operation concerns a determination with recoverable conditions; neither historical transmission nor empirical equivalence follows from that comparison.',anchor='preference-training-and-delegation')
add(5,'history-zero-subject-advent','zero–subject history','the comparison’s retained difference at register 3. Neumann’s morphology of ego differentiation and Gebser’s co-presence of consciousness structures supply different historical objects. Their meeting makes a changed return legible while retaining each telling’s geography, mediation and time; it supplies no single universal timetable and does not derive Taylor’s marked-paper or eightfold sequence.')
add(5,'dossier-zero-reception','zero-reception dossier','the qualifying respect at register 3 by retaining the disagreement between Rotman’s semiotically constituted position and Taylor’s irreducible subject-pole. An institution of a readable role is a real achievement; its history does not by itself account for the condition through which that institution appears. The ordinal identity and native self-application retain their own objects rather than supplying the missing Rotman chapter.')
add(5,'dossier-oi-technical-responsibility','O:I dossier','the research boundary at register 3 through separately testable contracts, constructors and proposed architectures. Six checks of structured records do not prove source authentication, hosted acceptance or phenomenal localisation. The three-office comparison and five-step return state what an implementation would have to change; their philosophical and source claims keep their independent standing.',anchor='oi-evidence-standing')
add(6,'history-ancient-philosophy','ancient-philosophy history','apportioned measure at register 3 through Aristotle’s different distributions, rectifications and exchanges. A share under merit, correction of gain and loss, and conventionally mediated exchange require different units and ends. Provision remains distinct from accumulation, and the ancient household’s unequal membership stays explicit. Contemporary answerable allocation is the essay’s further institutional operation.',anchor='ancient-measure-provision')
add(6,'history-indian-philosophy','Indian philosophy history','finite power by apportionment at register 3 through contracted efficacy, knowledge, desire, time and order. Their limits make distinct capacities workable; recognition returns through those capacities without annulling the apparatus. Sāṃkhya’s witness and Śaiva manifestation retain different accounts, and the native sixfold, eightfold and thirty-sixfold keep their own offices.','## #2 —',op='Power becomes finite by apportionment')
add(6,'history-language-law-nation-centralisation','language–law–nation history','measure and delegated capacity at register 3 through language becoming a condition of legal participation. A common judicial form can increase portability while distributing translation work, access and exclusion unevenly. The twelve branches retain their actual evidence; a recovered institutional cost must be able to reach the office changing the next allocation.','### Liability and release',op='Measure; delegated labour; returned share',anchor='historical-anamnesis')
add(6,'history-mathematics','mathematics history','apportioned criterion at register 3 through a declared unit and purpose. Temperament changes intervals to secure one kind of closure; the native exact product completes an octave under another operation. Likewise, a preference comparison’s gauge and reference policy remain different. The receiving account must retain which measure made its result actionable.')
add(6,'history-myth','myth history','apportioned liability at register 3 through the bride-gifts demanded, the adulterer’s fine and Poseidon’s contingent undertaking. These are different claims with different bearers. Acceptance changes what Hephaestus does with his effective instrument; release is narrated and later payment is not. The comparison preserves an executable change without inventing its future discharge.','### Liability and release',op='Delegated labour; liability and release')
add(6,'dossier-indian-philosophy','Indian philosophy dossier','finite power by apportionment at register 3 through the operative horizon and the different reaches of knowledge, agency, desire, time and order. A sourceward return preserves the capacity which makes it possible. Its three-office technical proposal keeps ground, generation and evaluation distinct and leaves any EBM/JEPA implementation to its own test.','## #2 —',op='Power becomes finite by apportionment')
(P/'expanded-additions.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
# Preserve a fresh prebatch image; no broad restore from the initial packet.
assert all(r['exit_code']==0 for r in json.loads((P/'extension-effects-result.json').read_text()))
manifest=[]
for e,f in E.items():
 t=f.read_text();b=t.encode();snap=f'before/expanded-E{e}.md';(P/snap).write_bytes(b);manifest.append({'path':str(f),'sha256':hashlib.sha256(b).hexdigest(),'snapshot':snap})
 for r in rows:
  if r['field_path']!=str(f):continue
  assert r['paragraph'] not in t
  assert t.count(r['slot'])==1,(str(f),r['slot'])
  t=t.replace(r['slot'],r['paragraph']+'\n\n'+r['slot'],1)
 f.write_text(t)
(P/'expanded-before.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Applied',len(rows),'expanded paragraphs across six E fields')
