from pathlib import Path
import json,os,hashlib
P=Path(__file__).parent
records={r['record_id']:r for r in json.loads((P/'carrier-list.json').read_text())}
names=['encounter-region-name-count','arbitration-hybris-regard-anamnesis','trust-place-logos-nomos-natio-credere','symbol-account-and-trust','homology-and-analogy','apportionment-and-economy']
E={i+1:Path('submission-package/essay/symbolon/episteme/etymologies')/n/'WHOLE-FIELD.md' for i,n in enumerate(names)}
rows=[]
def add(e,r,slot,op,text,anchor=''):
 target=records[r]['path'];link=os.path.relpath(target,E[e].parent)+('#'+anchor if anchor else '')
 text=text.replace('@',link)
 rows.append(dict(record_id=r,field='E'+str(e),field_path=str(E[e]),operation=op,evidence_register=3,carrier_path=target,slot=slot,paragraph=text,status='new-primary-return'))
add(1,'history-indian-philosophy','## #3 —','Name-through-Count','The [Indian philosophical history](@) **historicises** determinate reference through distinct accounts of enumeration, exclusion and recognition. Sāṃkhya’s functional triad differentiates the instrument from its witness; Pind’s qualified referent retains the positive work of preclusion; the Śaiva account makes finite capacities effective through contraction. Name-through-Count receives these differences at register 3: identify what a term makes addressable and the contrast through which it applies before comparing its return. Neither the thirty-six-tattva field nor the native eightfold is replaced by a count of matching words.')
add(1,'dossier-indian-philosophy','## #3 —','Name-through-Count','The [Indian philosophy dossier](@) **extends** Name-through-Count at register 3 through the distinction between a repeated sound-name and its situated bearer. Its I–you–it exchanges make the speaker and addressee consequential; its Vāk descent preserves formative power, mental articulation and utterance as different offices. A returned determination must retain the relevant excluded field and disclose which criterion or permission changes the next act. This authored continuation leaves Kripke’s rigidity, Buddhist exclusion and Śaiva recognition with their own warrants.')
add(1,'dossier-zero-reception','## #3 —','Name-through-Count','The [zero-reception dossier](@) **historicises** a receiving practice’s change of permission. An internal place-marker, an absent astronomical measure and an arithmetic operand can share a later name while doing different work. Name-through-Count receives the rule that makes this sign usable here; Count-to-Account receives the carrier and restricted inference by which another reader can check it. Nothaft’s critique of a modern reception myth changes the historical account without changing the independently established arithmetic. This is an operational return at register 3, with historical claims remaining separately testable.')
add(2,'history-psychology','## A determination carried','Resolution-in-Reconciliation → Anamnesis / Recognition / Return','The [psychology history](@) **historicises** what a settlement must retain when it returns. Jung’s ego and Self keep different scopes; Neumann’s differentiated centre retains each telling’s geography and time; symbolic transformation changes the interpreter who receives the next image. Resolution-in-Reconciliation carries that changed history rather than restoring an untouched beginning. At register 3, the institutional comparison also returns a limit on transfer: psychic recognition alone neither redistributes coercive power nor supplies an effective appeal, and institutional reform alone does not establish changed affective investment.')
add(3,'history-language-law-nation-centralisation','## #5→0 —','Natio and neo-nativity','The [developed twelve-branch history](@) **historicises** Natio through the different means by which place, language and jurisdiction become inherited belonging. Occitan incorporation, Languedoc Jewish transmission, Italian and German national projects, Anglo-Celtic jurisdictions, Hebrew revival and transregional Abrahamic formations retain their separate chronologies. The Renaissance, rejected-knowledge and Aion branches preserve changes of reception; post-war and computational branches ask how inherited categories act again. At register 3, Natio returns each claimed natural unity to its formative institutions and exclusions. The 1539 judicial-language articles and bounded 1794 speech support their specified interventions; neither certifies every branch or its enforcement. Credere receives an undertaking whose bearer and history remain available for examination.','historical-anamnesis')
add(4,'history-language-symbol-dialogue','## #3 —','Account does not replace source','The [language, symbol and dialogue history](@) **historicises** the difference between transmitting an account and retaining its conditions. Apoha makes reference determinate; Wittgenstein’s later practice differs from the earlier saying/showing inquiry; Lacan’s situated address differs from formal transmission; Bohm’s dialogical suspension keeps participants’ assumptions available for change. Attention weights and a selected index then give the technical comparison distinct objects. At register 3, Account does not replace source requires the returned statement to retain which operation it performed and who can correct its use. A history of these practices supplies no single lexical ancestry or demonstrated software outcome.','language-account-return')
add(4,'history-zero-subject-advent','## #2 —','Symbol answers to source','The [zero–subject history](@) **historicises** two distinct admissions joined by Taylor’s authorial braid: arithmetic acquires a sign with specified powers, while psychological and perspectival accounts make previously concealed conditions articulate. Symbol answers to source at register 3 by retaining what each admission achieved and what its representation leaves unpossessed. The integral return carries the exact mathematical sign through its acquired symbolic history; it does not project that final office into every earlier zero. Freud’s present passage debt, bounded Jung material and Neumann’s morphology retain their different evidential reach.')
add(5,'history-ancient-philosophy','## #2 —','Homological agreement','The [ancient-philosophy development](@) **historicises** agreement through materially different relations: B51’s opposed pulls sustain an instrument; Aristotle’s focal predicates refer differently to a primary term; distribution, rectification and exchange employ different measures; a reconstructed mechanism coordinates distinct cycles. Homological agreement at register 3 retains what each act preserves and changes. The modern tuning account’s comma remains distinct from the native octave-completing factor, and modern allusion or reconstruction remains distinct from the ancient witness. The comparison returns more exact terms rather than one timeless doctrine of harmony.','ancient-source-return')
add(5,'history-mathematics','## #3 —','Analogical proportion / focal relation','The [mathematics development](@) **historicises** changed permissions and retained conditions. Zero’s absorption forbids cancelling a zero factor; ordinal succession, mediant insertion and the empty product have different laws; alternation with a shift represents a square root of minus one; a lifted loop retains winding rather than every event of travel. Analogical proportion at register 3 makes their relation explicit without exchanging their objects. In particular, tuning a fifth-cycle and multiplying the native octave-completing factors are different operations. A later evaluation must carry the actual law, reference policy or comparison class on which its precision depends.')
add(5,'history-myth','## #4 —','Research boundary','The [myth history](@) **historicises** what a whole telling can change in its reception. Harmonia retains Fear and Panic in the genealogy; Homer’s capture ends in release upon contingent surety with payment unreported; the Huayan net supplies its own simile-limit; Nietzsche, Gebser and Taylor perform separately dated interpretive work. E5’s research boundary receives those distinctions at register 3. A narrative consequence can qualify the operation attributed to an image, while a shared net, numeral or family figure supplies no proof of common descent, one doctrine or a completed technical return.')
add(5,'dossier-formal-limit','## #3 —','Analogical proportion / focal relation','The [formal-limit dossier](@) **qualifies** analogical proportion through the different continuations a limit permits. Russell’s formation rule requires repair; Gödel’s derivability result retains its specified theory and hypotheses; Wittgenstein’s elucidation concerns its use; Cusa’s approximation and Eckhart’s qualified predicate retain their theological respects. At register 3 the comparison names which operation reaches which limit and what remains possible afterwards. Their relation sharpens the native determining-act inquiry without converting distinct restrictions into one theorem or an unproved sentence into a warrant for faith.','eckhart-qualified-predication')
add(5,'dossier-jung-pauli-psychoid','## #4 —','Research boundary','The [Jung–Pauli dossier](@) **historicises** comparison as a negotiation which changes its terms. Pauli’s 1953 demand for neutral language, Jung’s clarification of psychoid and his rejection of absorption into physics remain different positions; Pauli’s 1957 metric/topology objection qualifies the hyperspace image. Number as mathematical relation, measured quantity and dream figure keeps three different offices. E5’s research boundary returns those speaker, date and object distinctions at register 3. A corrected receiving account must alter its attribution and inference, while psychophysical efficacy remains its own Offered inquiry and empirical task.')
add(6,'history-technology-politics','### Liability and release','Delegated labour distributes capacity and return','The [technology–politics development](@) **historicises** how a measure acquires institutional and technical force. Its crowd and state diagnoses distinguish collective formation from the offices exercising power; preference training distinguishes score, reference policy and delegated action; the commons programme distinguishes a proposed institution from observed execution. Delegated labour distributes capacity and return at register 3 by asking who commissions, performs, benefits and bears the cost. A returned failure must reach the office able to change the evaluator or terms of work. The historical sequence and its distinct technologies establish no claim that the proposed architecture has shipped.','commons-and-responsible-return')
add(6,'dossier-oi-technical-responsibility','### Liability and release','Delegated labour distributes capacity and return','The [O:I responsibility dossier](@) **extends** delegated labour at register 3 through separately inspectable authorisation, source, projection, contribution, encounter and acceptance. Its six responsibility centres retain their offices alongside the five E6 operations and four Name/Power consequences: expenditure, authorised course, affected other and returned result with costs and correction rights. The direct code probes establish bounded provenance, containment and attributed-record behaviour; they do not authenticate a source, demonstrate learning or certify deployment. Return reaches the responsible authority when a contribution can revise a source claim, criterion or commission while preserving refusal and local ownership.','oi-source-projection-contribution-route')
back=[(1,'history-indian-philosophy','## #5→0 —','This history **returns-to** [Name-through-Count](@) through its distinct achievements of addressability. Sāṃkhya enumerates an instrument’s functions without making them its witness; semantic preclusion gives a positive referent its contrast; contracted Śaiva powers make a finite world workable. The receiving account must identify which discrimination it uses before comparing recollection and recognition. This register-3 relation preserves the source differences and the native eightfold; it supplies no common descent for their terms.','name-through-count'),(1,'dossier-indian-philosophy','## #3 —','This dossier **returns-to** [Name-through-Count](@) through the difference between a shared sound-name and the situated bearer of an utterance. Vāk’s descent and the I–you–it exchange make naming an act within an effective circumstance; exclusion keeps the positive determination answerable to its alternatives. At register 3, the returned account must say which bearer, contrast and criterion it has retained. The historical accounts of rigidity, Buddhist semantics and Śaiva articulation remain distinct from Taylor’s pre-nominal count.','name-through-count'),(5,'dossier-formal-limit','<a id="experience-and-constructive-continuation">','The dossier **returns-to** [E5’s analogical proportion](@) with a different continuation for each limit. Formation can require a changed permission; relative unprovability retains its theory; an elucidation changes how it is used; a qualified predicate states the respect under which it holds. This register-3 comparison preserves the surviving work of each account and keeps its source-specific hypotheses active. It gives the native determining-act argument more exact neighbours without deriving that argument from their common label.','analogical-proportion'),(5,'history-myth','## #1 —','This historical comparison **returns-to** [E5’s research boundary](@) through the whole telling’s power to qualify its use. The genealogy retains the dangerous offspring beside concord, and a later reception must preserve the relation actually narrated before drawing a psychic or technical consequence. The comparison operates at register 3; it neither establishes transmission by resemblance nor turns a repeated count into the derivation of the native field.','research-boundary')]
for e,r,slot,text,anchor in back:
 target=Path(records[r]['path']);link=os.path.relpath(E[e],target.parent)+'#'+anchor
 rows.append(dict(record_id=r,field='E'+str(e),field_path=str(E[e]),operation='reciprocal carrier closure',evidence_register=3,carrier_path=str(target),slot=slot,paragraph=text.replace('@',link),status='new-carrier-return'))
(P/'primary-additions.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
# Check freshness for each mutation; all effects must have succeeded first.
assert all(r['exit_code']==0 for r in json.loads((P/'effects-result.json').read_text()))
manifest={r['path']:r for r in json.loads((P/'before-manifest.json').read_text())}
paths={r['field_path'] if r['status']=='new-primary-return' else r['carrier_path'] for r in rows}
for s in paths:assert hashlib.sha256(Path(s).read_bytes()).hexdigest()==manifest[s]['sha256'],s
for s in paths:
 t=Path(s).read_text()
 for r in rows:
  if (r['field_path'] if r['status']=='new-primary-return' else r['carrier_path'])!=s:continue
  assert r['paragraph'] not in t
  assert t.count(r['slot'])==1,(s,r['slot'])
  t=t.replace(r['slot'],r['paragraph']+'\n\n'+r['slot'],1)
 Path(s).write_text(t)
(P/'primary-targets.json').write_text(json.dumps({'elements':[{'canonical_home':s,'register':'episteme'} for s in sorted(paths)]},indent=2)+'\n')
print('Applied',len(rows),'paragraphs across',len(paths),'files')
