from pathlib import Path
import json,hashlib,zipfile,sys,os,re
sys.path.insert(0,'tools')
from source_resolver import resolve_source_house
P=Path(__file__).parent;R=Path.cwd();old=Path('working/p2-enrichment/snapshots/T21-private-oi-technical-responsibility-2026-09-08');z=zipfile.ZipFile(old/'bound-inputs.zip')
assert all(x['exit_code']==0 for x in json.loads((P/'source-repair-effects.json').read_text()))
sha=lambda b:hashlib.sha256(b).hexdigest()
changes=[]
def save(f,t):
 b=f.read_bytes() if f.exists() else None
 snap=f'before/source-{len(changes)}.md'
 if b is not None:(P/snap).write_bytes(b)
 f.parent.mkdir(parents=True,exist_ok=True);f.write_text(t)
 changes.append(dict(path=str(f),before_sha256=sha(b) if b is not None else None,after_sha256=sha(t.encode()),snapshot=snap if b is not None else None))
repairs={
 '42-techne-2026-sovereign-commons':'/Users/admin/Central/Work/projects/4-2-Techne/docs/42-Techne-Sovereign-Commons-Architecture.pdf',
 'taylor-2026-revision-notes-trust':'working/sources-texts-references/definition-of-god-working/revision-notes-trust-and-f-blocks.md',
 'taylor-2026-symbolon-dynamics':'working/sources-texts-references/Epi Paper Write-ups/Symbolon Dynamics — Archetype, Attractor, and Objective Internality.md'}
for sid,local in repairs.items():
 f=resolve_source_house(R,sid).relative_to(R);t=f.read_text();b=Path(local).read_bytes();zn='external'+local if local.startswith('/') else local
 assert b==z.read(zn),('read-reuse mismatch',local)
 t,n=re.subn(r'^local_copy: .*$', 'local_copy: '+json.dumps(local,ensure_ascii=False),t,count=1,flags=re.M);assert n==1
 if sid=='42-techne-2026-sovereign-commons':
  # Preserve the actual valid section assignment without its explanatory suffix.
  t=t.replace('- §5→0 · applied 4:2 Technē architecture','- §5→0')
  t=t.replace('quote_status: locator-needed','quote_status: paraphrase-only')
  cards=[('PDF pp.6–7, §1.1 system overview and §1.2 hardware','Seven-layer design','The system overview lists Foundation, Gateway, Access, Intelligence, Knowledge, Commons and Network. Its introductory sentence says six layers, but the table has seven and the later network discussion explicitly calls Network the seventh. Hardware tiers and performance statements are report claims, not benchmark results admitted here.'),('PDF pp.7–8, §§1.3–1.5','Sessions, knowledge and Agora','The report describes owner, shared-group and sandboxed sessions; local/remote model routing; persistent community knowledge; and three Agora functions: peer compute brokerage, a wisdom feed and a cooperative host. The proposed wisdom feed carries a P5 artifact into another community’s P0 conditions after selection. These are architectural descriptions, not evidence that cross-community learning or federation ran.'),('PDF pp.9–10, §§2.1–2.5','Community entry and subsidiary governance','Stewardship and community participation organise the proposed deployment. Hastings Commons and the OBX hub are identified as prospective pilot partners, with phased introduction and capabilities activated through expressed demand. Their naming establishes the intended locality and governance relation, not a completed installation.'),('PDF pp.11–12, §3','Dated maturity and five-phase roadmap','The February report separates reported component maturity from its five development phases. Foundation, integration, economic layer, governance/federation and intelligence evolution describe a programme. A maturity table and proposed phases do not establish September implementation or successful end-to-end acceptance.'),('PDF pp.13–15, §4','Economic branches and costs','The economic proposal distinguishes local exchange, agent payments and compute exchange, then estimates costs and funding. Its historical community-currency examples remain the report’s attributions, requiring independent sources if used as public historical evidence. Budgets are estimates rather than incurred costs or proven returns.'),('PDF pp.16–17, §§5–6','Governance, federation and artifact return','Community stewards, reciprocal participation and federation are meant to preserve local control while enabling resource and knowledge exchange. The Agora joins infrastructure, knowledge and economic relations. Its proposed return lets an achieved artifact condition further local work without proving the governance, learning or payment mechanism implemented.')]
  txt='The complete seventeen-page local report was read for the T21 technology/O:I development; identical bytes were verified on 2026-09-08. SHA-256: `'+sha(b)+'`. Locators below are PDF page numbers, not a separately collated print edition. No direct quotation is admitted.\n\n'
  for i,(loc,title,body) in enumerate(cards,1):
   q=f'{sid}-q{i:03d}'
   txt+=f'<a id="{q}"></a>\n## Passage card — `{q}` — {title}\n\n> **Paraphrase (not a quotation):** {body}\n\n- **Locator:** {loc}.\n- **Status:** paraphrase-only.\n- **Verification:** full seventeen-page PDF reading, reused at identical SHA-256 on 2026-09-08.\n- **Provenance:** corporate report, version 2.0, February 2026; actual local PDF above.\n- **Source relation:** Paraphrased.\n- **Use boundary:** internal design/report evidence; no independent historical, performance or deployment validation.\n- **Consumers:** [O:I responsibility dossier](../../../../dossiers/oi-technical-responsibility.md); [technology–politics development](../../../../histories/traditions-and-disciplines/technology-politics/DEVELOPMENT.md).\n\n'
  assert t.count('No passage or excerpt has yet been gathered for this source.')==1
  t=t.replace('No passage or excerpt has yet been gathered for this source.',txt.rstrip())
 save(f,t)
sid='oi-2026-responsibility-source-projection'
assert resolve_source_house(R,sid) is None
home=Path('submission-package/essay/symbolon/episteme/sources/computer-science-ml/oi')/sid/'SOURCE.md'
raw=Path('working/sources-texts-references/primary-texts/oi')/sid
assert not home.exists() and not raw.exists()
raw.mkdir(parents=True)
entries=[]
for row in json.loads((old/'product-evidence.json').read_text()):
 b=z.read('external'+row['path']);assert sha(b)==row['sha256'];name=Path(row['path']).name;(raw/name).write_bytes(b);entries.append(dict(row,local_copy=str(raw/name)))
for name in ['SOURCE-AND-AUTHORITY-MAP.md','SYMBOLON-OI-WIKI-CONTRACT.md']:
 orig='working/harmonisation-2026-08-18-objective-internality-capstone/'+name;b=z.read(orig);(raw/name).write_bytes(b);entries.append(dict(path=orig,sha256=sha(b),local_copy=str(raw/name),read_scope='full dated authorial contract; historical audit assertions retain August scope'))
for name in ['implementation-probe.mjs','implementation-probe.json']:
 b=(old/name).read_bytes();(raw/name).write_bytes(b);entries.append(dict(path=str(old/name),sha256=sha(b),local_copy=str(raw/name),read_scope='complete direct constructor probe/evidence'))
(raw/'MANIFEST.json').write_text(json.dumps({'date':'2026-09-08','prior_immutable_packet':str(old/'bound-inputs.zip'),'entries':entries},ensure_ascii=False,indent=2)+'\n')
manifest='# O:I responsibility / source-projection — selected evidence bundle\n\nImmutable copies of material fully read in the T21 O:I development. This is a dated evidence bundle, not an assertion about the latest product checkout.\n\n'
for e in entries:manifest+=f"- [{Path(e['local_copy']).name}]({Path(e['local_copy']).name}): SHA-256 `{e['sha256']}`; origin `{e['path']}`.\n"
(raw/'MANIFEST.md').write_text(manifest)
metadata=dict(title='O:I — Responsibility, Source, Projection and Contribution (selected 2026 evidence)',source_id=sid,primary_domain='computer-science-ml',record_type='technical-documentation',node_type='source-house',ownership='canonical-source-house',schema_version=1,source_role=['internal-project-contract','bounded-code-evidence'],author=['O:I project'],title_full='Responsibility, Source, Projection and Contribution — Selected O:I Contracts and Constructor Evidence',year=2026,metadata_status='verified',edition_status='dated-local-evidence-bundle',citation_status='internal-ready',quote_status='paraphrase-only',chicago_ready=False,local_copy=str(raw/'MANIFEST.md'),passage_surface='#passages',main_source_for=[],consumed_by_dossiers=['submission-package/essay/symbolon/episteme/dossiers/oi-technical-responsibility.md'])
import yaml
t='---\n'+yaml.safe_dump(metadata,sort_keys=False,allow_unicode=True)+'---\n# O:I — Responsibility, Source, Projection and Contribution\n\n## Identity and evidence standing\n\nThis selected internal technical bundle joins authored positions, product contracts, source/projection architecture and a bounded executable floor. The documents retain their separate identities inside the manifest. The O:I checkout was inspected at committed head `c1ce2db81eec3b03a9bdff0a1accf8ece4acf903`. FOUNDING-POSITIONS.md, OBJECTIVE-CO-INTERNALITY.md and social.mjs matched that commit. CANONICAL-PRODUCT-FIELD.md did **not**: its inspected working bytes include the 2026-09-06 S=CLI / M′=desktop owner clarification. Its working SHA-256 is `bb1cfcf38abf8d16095cdff5af0424aea5f120b695b64e093500523a0a105456`; these bytes must not be attributed to the committed head.\n\nThe August capstone contracts retain their dates and original census scope. Their reported read/navigation floor and higher-order authoring gaps are historical statements, not a September software acceptance audit. Later ratification governs present native cardinalities and recursive local Bimba. Full readings are reused from the immutable T21 packet; exact originals and SHA-256 values are retained in the local manifest. No external published edition or direct quotation is claimed.\n\n## Consumption and limits\n\nThe [O:I responsibility dossier](../../../../dossiers/oi-technical-responsibility.md) develops the relation between authorisation, source, projection, contribution, encounter and acceptance. A projected account remains distinct from its source; a returned contribution retains attribution and can be accepted, revised, refused or left divergent. These contract operations are not proof of hosted admission, UI completion, learning, authentication or deployment. The six direct checks establish only the listed constructor behaviours.\n\n<a id="passages"></a>\n## Selected passages and code scope\n\n'
cards=[('Founding positions','FOUNDING-POSITIONS.md, lines81–249 and315–543, read in full544lines','Authored meaning precedes product implementation; agency depends on a world of capacities and conditions. The conjugate movement returns consequences to human agency, differentiated shared worlds, accountable power, contestable epistemic conditions, software form and preserved provenance. These are authored positions and research/design commitments.'),('Product field and working-byte amendment','CANONICAL-PRODUCT-FIELD.md, lines7–69,94–192,525–690; full738lines read','The product contract distinguishes one field, conjugate faces, six centres and their relation surfaces. Perspective differs from participant identity; topology differs from traversed routes. The local September amendment distinguishes the CLI and desktop owner surfaces. The 144 face relations are product design relations, not 144 executed capabilities or additional native QL determinations.'),('SharedField, Contribution and Encounter','OBJECTIVE-CO-INTERNALITY.md, lines21–238 and316–331; full331lines read','SharedField records a common field without merging its participants. Contributions retain basis, targets and provenance; ranking and metrics remain contributions. Encounter mediates a participant’s relation to what appears without establishing subjective understanding. Participant, Projection and Contribution have distinct identities and acceptance obligations.'),('Source and projection return','SYMBOLON-OI-WIKI-CONTRACT.md, lines272–445 and578–611; full802lines read; SOURCE-AND-AUTHORITY-MAP.md, full122lines','A source has a canonical identity while a Projection has its own version and state. Encounter can produce revision and a proposal that returns to explicit acceptance or maintained divergence. A wiki edge, contribution and learned route are different relations. The dated contract’s claims about implemented seams and gaps retain the August audit scope; its higher-order operations require their own acceptance evidence.'),('Six constructor checks','social.mjs, lines1–281, especially87–281; implementation-probe.mjs and implementation-probe.json, complete selected run','Six direct checks of the actual implementation passed: missing provenance rejected; local containment cycles rejected; an external parent retained; metric basis and target retained; an Encounter reconstructed without importing an understanding assertion; and an out-of-field participant rejected by Self/Other. These checks validate structured assertions and boundaries, not their truth. They establish no source authentication, learning, hosted acceptance, UI or deployment outcome.')]
for i,(title,loc,body) in enumerate(cards,1):
 q=f'{sid}-q{i:03d}';t+=f'<a id="{q}"></a>\n## Passage card — `{q}` — {title}\n\n> **Paraphrase (not a quotation):** {body}\n\n- **Locator:** {loc}.\n- **Status:** paraphrase-only.\n- **Source relation:** Paraphrased.\n- **Verification:** full selected material read in T21; immutable bytes and SHA-256 verified at canonical admission on 2026-09-08.\n- **Provenance:** dated local bundle manifest; committed and working-byte distinction above.\n- **Use boundary:** the card’s specific authored-contract or bounded-code standing; no complete implementation inference.\n- **Consumer:** [O:I responsibility dossier](../../../../dossiers/oi-technical-responsibility.md).\n\n'
save(home,t.rstrip()+'\n')
(P/'source-admission-changes.json').write_text(json.dumps(changes,indent=2)+'\n')
print('Three source repairs; six42cards; newOIhouse fivecards;',len(entries),'bound inputs')
