"""Finish review-only apparatus; canonical source snapshot remains frozen."""
from pathlib import Path
import hashlib,json,re,importlib.util,urllib.parse
ROOT=Path(__file__).resolve().parents[2]; W=Path(__file__).resolve().parent
receipt=json.loads((W/'S01-QUOTATION-SOURCE-PATCH-RECEIPT.json').read_text())
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
overrides=json.loads((W/'S01-APPARATUS-OVERRIDES.json').read_text())
book_standing='Locators were checked in the actual user-local carrier on October 4, 2026; these cards do not certify a new quotation transcription.'
def note(marker,text):
    overrides[marker]={'text':text,'repair':'Recover apparatus in derivative review only; preserve the original movement and its authorial body.'}
notes={
's01-jung-psyche':'C. G. Jung, “Psychology and Religion,” in Psychology and Religion: West and East, CW 11, trans. R. F. C. Hull, 2nd ed. (Princeton University Press, 1969; consulted second printing, 1973), ¶¶16, 18; digital PDF page 23. Source house `jung-1969-psychology-religion-cw11`, p007. The intervening examples concern the efficacy of psychic facts; this does not assert the physical world’s non-existence.',
's01-jung-god':'Jung, Psychology and Religion: West and East, CW 11, 2nd ed. (1969; consulted printing 1973), ¶137; digital PDF page 75. Source house `jung-1969-psychology-religion-cw11`, p008. This is the psychologically dominant value, distinct from the essay’s ontological God/Subject argument.',
's01-aion-shadow':'C. G. Jung, Aion: Researches into the Phenomenology of the Self, 2nd ed., trans. R. F. C. Hull, CW 9ii (Princeton University Press, 1979 paperback carrier), ¶¶14, 16, print pp.8–9; digital PDF pages 20–21. Existing house `jung-1978-aion-cw9-2`, p017. The selected 1978 hardcover identity remains distinct from this consulted 1979 carrier; no independent equivalence is claimed.',
's01-jung-paradox':'C. G. Jung, Psychology and Alchemy, CW 12, trans. R. F. C. Hull, 2nd ed., completely revised 1968 (Princeton University Press, first paperback printing 1980), ¶¶18–19; digital PDF pages 47–48. Source house `jung-1980-psychology-alchemy-cw12`, p001. The need for cultivation and danger of misunderstood paradox are retained in the source context.',
's01-jung-logos-eros':'C. G. Jung, Mysterium Coniunctionis, CW 14, trans. R. F. C. Hull, 2nd ed., copyright 1970 (Princeton University Press, first paperback printing 1977), ¶224; digital PDF page 133. Source house `jung-1977-mysterium-coniunctionis-cw14`, p001. ¶225 discusses counterexamples; Jung’s historical gendered account is distinct from the essay’s two-operation continuation.',
's01-golden-flower':'C. G. Jung, “Commentary on The Secret of the Golden Flower,” in Alchemical Studies, CW 13, trans. R. F. C. Hull (Princeton University Press, first paperback printing 1983; copyright 1967), ¶20, print p.16; digital PDF page 30. Source house `jung-1983-alchemical-studies-cw13`, p001. The preceding warning against a mechanical recipe is retained; this is Jung’s commentary rather than the primary Chinese text.',
's01-numinous':'Jung, Psychology and Religion: West and East, CW 11, 2nd ed. (1969; consulted printing 1973), ¶6; digital PDF pages 19–20. Source house `jung-1969-psychology-religion-cw11`, p009, locates the Otto-derived account. The separate feeling-toned-complex lead in “A Review of the Complex Theory,” CW 8, is not newly located by this card.',
's01-jung-know':'The 1959 BBC Face to Face interview with John Freeman and the January 1960 Listener letter remain separate source acquisitions. The second current quotation is located in Jung, The Symbolic Life, CW 18, trans. R. F. C. Hull (Princeton University Press, 1976), ¶1589, “Jung and Religious Belief,” question 3; digital PDF page 654. Source house `jung-1976-symbolic-life-cw18`, p001. The answer separates personal conviction from scientific proof. It cannot certify the interview or Listener wording.',
's01-jung-individuation':'Jung, Psychological Types, CW 6, Hull revision of H. G. Baynes, first corrected Princeton/Bollingen paperback printing 1976, ¶758; digital PDF page 409. Source house `jung-1976-psychological-types-cw6`, p001. Also Jung, The Archetypes and the Collective Unconscious, CW 9i, 2nd ed., trans. R. F. C. Hull (Routledge, consulted carrier n.d.), ¶490, print p.275; digital PDF page 286. Source house `jung-cw9i-hull-routledge-second-edition`, p002. The first rejects isolation; the second distinguishes the ego from psychological totality.',
's01-jung-art':'Jung, “On the Relation of Analytical Psychology to Poetry,” The Spirit in Man, Art, and Literature, CW 15, trans. R. F. C. Hull (Princeton University Press, first paperback printing 1971; copyright 1966), ¶130; digital PDF page 74. Source house `jung-1971-spirit-man-art-literature-cw15`, p001. The contemporary cultural application and typological artist reading remain the essay’s.',
's01-mana':'Jung, “On Psychic Energy,” The Structure and Dynamics of the Psyche, CW 8, trans. R. F. C. Hull, 2nd ed., copyright 1969 (Princeton University Press, third corrected printing 1975), ¶52 n.44; digital PDF page 75. Source house `jung-1975-structure-dynamics-psyche-cw8`, p002. This is a Codrington-mediated witness. The separate n.123 wording remains to be collated; this card does not silently certify it.',
's01-lucifer':'Jung, Aion, CW 9ii, 2nd ed., trans. R. F. C. Hull (Princeton University Press, consulted paperback carrier 1979), ¶127, print p.72; digital PDF page 84. Existing house `jung-1978-aion-cw9-2`, p021, now records the shared Morning Star symbol. The draft’s additional ¶68 science/technology phrase, independent Isaiah/Vulgate textual collation, and Shelley lead are not newly certified by this card.',
's01-privatio':'Jung, Aion, CW 9ii (consulted paperback carrier 1979), ¶¶74–75, print pp.41–42; digital PDF pages 53–54. Existing house `jung-1978-aion-cw9-2`, p018. Jung specifies the empirical-psychological register; theological and metaphysical endorsement are distinct claims.',
's01-aion-antichrist':'Jung, Aion, CW 9ii (consulted paperback carrier 1979), ¶¶76–78, print pp.42–43; digital PDF pages 54–55. Existing house `jung-1978-aion-cw9-2`, p019. The symbolic shadow and counterstroke are located together; this is Jung’s historical-theological reconstruction.',
's01-antimimon':'Jung, Aion, CW 9ii (consulted paperback carrier 1979), continuation of ¶75, print p.42; digital PDF page 54, locates the Antichrist as imitating spirit. Existing house `jung-1978-aion-cw9-2`, p020. The distinct contemporary false-spirit description is ¶67, print p.35; digital PDF page 47. Cite each in its own context; the current M05 Antichrist quotation points to ¶75.',
's01-jung-symbol':'Jung, Psychological Types, CW 6, Hull revision of H. G. Baynes, first corrected Princeton/Bollingen paperback printing 1976, ¶814, Definition 51, “Symbol”; digital PDF page 430. Source house `jung-1976-psychological-types-cw6`, p002. The semiotic badge/token examples retain the contrast between a known referent and the relatively unknown fact formulated by a symbol.',
's01-jung-archetype':'Jung, The Structure and Dynamics of the Psyche, CW 8, 2nd ed., third corrected printing 1975, ¶417, print pp.213–214; digital PDF pages 225–226. Source house `jung-1975-structure-dynamics-psyche-cw8`, p001. The two-irrepresentables sentence is still ¶417; ¶418 begins at digital page 227, print p.215. Also Jung, The Archetypes and the Collective Unconscious, CW 9i, Hull translation, Routledge second-edition carrier n.d., ¶155, print p.79; digital PDF page 90. Source house `jung-cw9i-hull-routledge-second-edition`, p001. The formal possibility is not an inherited determinate image, and the psychoid comparison remains Jung’s analogy/hypothesis.',
's01-jung-self':'Jung, Aion, CW 9ii (consulted paperback carrier 1979), ch.V n.74, print p.61; digital PDF page 73. Existing house `jung-1978-aion-cw9-2`, p022. The reply to Victor White concerns psychological unity of the Self; the essay’s Śaiva/QL comparison remains its own continuation.',
's01-jung-quaternity':'Jung, Psychology and Religion: West and East, CW 11, 2nd ed. (1969; consulted printing 1973), ¶246; digital PDF page 140. Source house `jung-1969-psychology-religion-cw11`, p010. Also Jung, Psychology and Alchemy, CW 12, 2nd ed., consulted paperback printing 1980, ¶31; digital PDF page 56. Source house `jung-1980-psychology-alchemy-cw12`, p002. Four determinants and vacillation between three and four are located; QL’s 4+2 is the essay’s continuation.',
's01-jung-five':'Jung, Mysterium Coniunctionis, CW 14, 2nd ed., consulted paperback printing 1977, ¶439; digital PDF page 233. Source house `jung-1977-mysterium-coniunctionis-cw14`, p002. The square/circle/quintessence passage belongs to commentary on Ripley’s vessel and son; QL #5 and #5→#0 are native continuation.'}
for k,v in notes.items():note(k,v+' '+book_standing)
note('s01-dialog','Dell Cameron and Yulia Almazova, “Leak Exposes Members of Peter Thiel’s Secretive ‘Dialog’ Society,” WIRED, June 16, 2026, https://www.wired.com/story/leak-exposes-members-of-peter-thiels-secretive-dialog-society/; and Dell Cameron, Dhruv Mehrotra and Yulia Almazova, “How the Peter Thiel-Linked Dialog Club Secretly Ranks Its Members,” WIRED, June 18, 2026, https://www.wired.com/story/how-peter-thiels-private-dialog-club-secretly-ranks-its-members/. Source houses `wired-2026-dialog-exposed` and `wired-2026-dialog-rankings`, p001 in each. Primary publisher text and membership/guest distinction checked October 4, 2026; current offices/sectors wording is preserved. Novara remains a supplied corroborating lead, not a newly acquired witness in this pass.')
note('s01-mkultra','United States Senate, Project MKULTRA, the CIA’s Program of Research in Behavioral Modification, joint hearing, 95th Congress, 1st session, August 3, 1977, https://www.intelligence.senate.gov/sites/default/files/hearings/95mkultra.pdf. Source house `senate-1977-project-mkultra-hearing`, p001: Kennedy print p.3 (digital page 7) and Turner print pp.4–6 (digital pages 8–10), on the 1973 destruction order and surviving financial folders. The selected primary passages do not independently identify Cameron/Subproject 68; that specific historical attribution remains to be sourced separately.')
note('s01-mkultra-2026','House Committee on Oversight, Task Force on the Declassification of Federal Secrets, “Mind Control and Accountability: Uncovering the Truth of the CIA’s MKULTRA Project,” June 30, 2026, https://oversight.house.gov/hearing/mind-control-and-accountability-uncovering-the-truth-of-the-cias-mkultra-project/. Stephen Kinzer’s three-page submitted testimony is https://oversight.house.gov/wp-content/uploads/2026/06/Kinzer-Written-Testimony.pdf; source house `kinzer-2026-mkultra-house-testimony`, p001, especially p.2. The actual date is June 30 and title ends “Project”; current body/date correction is separately proposed, never silently applied. Oral proceedings, Poisoner in Chief, and the National Security Archive item are separate acquisitions; the written testimony does not contain the draft’s prosecution/compensation assertion.')
note('s01-epstein-redaction','Todd Blanche, December 19, 2025 letter to Congress on Epstein files production, United States Department of Justice, https://www.justice.gov/opa/media/1434851/dl, pp.1–4 (redaction categories p.2; EFTA Bates numbers p.3). Source house `doj-2025-epstein-production-letter`, p001. All six pages checked October 4, 2026. This source establishes the Department’s release process and attributed rationale; it does not by itself establish the current prose’s scale-of-redaction or protected-co-conspirator conclusions. M05’s Martin proposal is a separate exact record, EFTA01040587, whose official PDF remained behind the DOJ age-verification redirect during this pass.')
# Late locators stay in the review only; the canonical snapshot is already frozen.
note('s01-jung-shadow','Jung, Psychology and Religion: West and East, CW 11, 2nd ed. (1969; consulted printing 1973), ¶131; digital PDF page 71. Existing house `jung-1969-psychology-religion-cw11`. The shadow/embodiment passage and adjacent context were located in the actual PDF on October 4, 2026. Review-only pending p011 is supplied in S01-LATE-LOCATOR-PATCHES-UNAPPLIED.json; it was not appended to the already frozen canonical snapshot. '+book_standing)
note('s01-god-image','Jung, Psychology and Religion: West and East, CW 11, 2nd ed. (1969; consulted printing 1973), ¶¶144–148; digital PDF pages 80–82. Existing house `jung-1969-psychology-religion-cw11`. ¶144 distinguishes a man-made definition/image from its unknown referent; ¶¶145–148 discuss withdrawal of projections, the dying/self-transforming Christian archetype and those whose faith has faded. ¶102 (digital page 58) supplies the psychological-image/ontological-proof limit. Review-only pending p012 is in S01-LATE-LOCATOR-PATCHES-UNAPPLIED.json; it is unapplied to the frozen source snapshot. '+book_standing)
note('s01-jung-child','Jung, “The Psychology of the Child Archetype,” The Archetypes and the Collective Unconscious, CW 9i, 2nd ed., trans. R. F. C. Hull (Routledge, consulted carrier n.d.), ¶299, print p.178; digital PDF page 189. Source house `jung-cw9i-hull-routledge-second-edition`. Beginning/end and pre-/post-conscious essence were located in the actual scan; OCR drops the leading digit of adjacent paragraph labels. Review-only pending p003 is in S01-LATE-LOCATOR-PATCHES-UNAPPLIED.json, unapplied to the frozen source snapshot. '+book_standing)
(W/'S01-APPARATUS-OVERRIDES.json').write_text(json.dumps(overrides,ensure_ascii=False,indent=2)+'\n')
# Exact, bounded additions ready for the integrator's later source cycle.
from_source={Path(row['path']).stem:row for row in receipt['changes']}
late=[]
for sid,n,title,loc,topic,boundary,movement,marker,key in [
 ('jung-1969-psychology-religion-cw11',11,'Shadow and conscious embodiment','¶131; user-local PDF page 71','The shadow, its relation to conscious embodiment, and the opportunity of correction are located together.','The surrounding discussion distinguishes suppression from repression. The passage does not license labelling every other person’s conduct an unconscious shadow.','M05','s01-jung-shadow','cw11'),
 ('jung-1969-psychology-religion-cw11',12,'Death and transformation of a God-image','¶¶144–148; user-local PDF pages 80–82; psychological image/proof qualifier at ¶102, PDF page 58','Finite definition, withdrawal of projections, the Christian archetype and loss of living faith occur in a connected sequence.','The source treats a psychological relation and does not prove an ontological God from a psychic image. Its discussion of Christ is an archetypal interpretation; authorial God/Subject identity remains separate.','M04','s01-god-image','cw11'),
 ('jung-cw9i-hull-routledge-second-edition',3,'Child as beginning and end','¶299; user-local PDF page 189 (printed p.178)','The initial/terminal child and pre-conscious/post-conscious essence are located in the child-archetype discussion.','Jung calls the after-death aspect an anticipation by analogy. The passage is not empirical proof of survival after death. The scan drops leading digits in some paragraph labels and is not quotation-ready.','M05','s01-jung-child','cw9i')]:
 row=from_source[sid];wit=json.loads((W/'quotation-verification'/(key+'-selected-contexts.json')).read_text());pid=f'{sid}-p{n:03d}'
 target=ROOT/row['path'];consumer=W/(movement+'-REWRITE.md')
 import os
 append=f'\n<a id="{pid}"></a>\n### {pid} — {title}\n\n**Locator:** {loc}.\n\n**Located operation:** {topic}\n\n**Context and use boundary:** {boundary}\n\n**Status:** locator-verified; acquisition required before quotation admission.\n\n**Provenance:** Actual user-local carrier already identified in this house; SHA-256 `{wit["sha256"]}`; selected paragraph and adjacent page context read with pypdf extraction by s01-apparatus, 2026-10-04. Rights provenance remains unregistered; no new quotation transcription is admitted.\n\n**Relation:** source-specific locator support; the essay’s philosophical continuation remains authorial.\n\n**Consumer:** Current working [{movement}]({os.path.relpath(consumer,target.parent)}) note `{marker}`; authorial text is preserved.\n'
 late.append({'path':row['path'],'expected_frozen_sha256':row['postimage_sha256'],'operation':'append-after-integrator-release-only','passage_id':pid,'append_text':append})
(W/'S01-LATE-LOCATOR-PATCHES-UNAPPLIED.json').write_text(json.dumps({'date':'2026-10-04','standing':'REVIEW ONLY — UNAPPLIED; canonical source snapshot frozen','changes':late},ensure_ascii=False,indent=2)+'\n')
# Read existing native effects receipts, don't rebuild or mutate the canonical graph.
spec=importlib.util.spec_from_file_location('okf_workspace',ROOT/'tools/okf-workspace.py');mod=importlib.util.module_from_spec(spec)
import sys;sys.modules[spec.name]=mod;spec.loader.exec_module(mod)
checks=[]
for row in receipt['changes']:
 p=ROOT/row['path'];actual=sha(p);assert actual==row['postimage_sha256'],row['path']
 text=p.read_text(); links=[]
 for target,kind in mod.markdown_targets(text):
  if 'M0' in target and '-REWRITE.md' in target:
   local=urllib.parse.unquote(target.split('#')[0]);ok=(p.parent/local).resolve().is_file();assert ok,target;links.append({'target':target,'exists':ok})
 e=W/'quotation-verification'/(p.stem+'-effects-depth4-after.json');assert e.is_file(),str(e)
 checks.append({'path':row['path'],'sha256':actual,'receipt_matches':True,'working_consumer_links':links,'effects_depth4_receipt':str(e.relative_to(ROOT))})
protected=[]
for rel,old in receipt['protected_authorial_inputs'].items():
 now=sha(ROOT/rel);protected.append({'path':rel,'source_pass_capture_sha256':old,'current_sha256':now,'same_as_capture':old==now,'agent_wrote_this_input':False})
verification={'date':'2026-10-04','source_snapshot_frozen':True,'source_paths':checks,'effects_depth':4,'protected_authorial_inputs':protected,'authorial_input_change':'M02 active author revision observed after source patch capture; preserved, not reverted','canonical_source_readback':'all 19 exact hashes match the frozen receipt','global_builds':'parent-owned; no detector/test/gate edited'}
(W/'S01-QUOTATION-SOURCE-PATCH-VERIFICATION.json').write_text(json.dumps(verification,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'overrides':len(overrides),'source_hashes_verified':len(checks),'late_review_only_cards':len(late),'author_input_hash_drift':[x['path'] for x in protected if not x['same_as_capture']]},ensure_ascii=False))
