from pathlib import Path
import sys,yaml,os
sys.path.insert(0,str(Path('.').resolve()))
from tools.source_resolver import build_source_index
idx=build_source_index(Path('.'));raw=Path('working/p2-enrichment/raw/T21-baudrillard')
lens=Path('submission-package/essay/symbolon/episteme/lenses/baudrillard.md')
def link(p,target):return os.path.relpath(target,p.parent)
def card(sid,n,title,body,locator,verification):
 return f'''\n<a id="{sid}-q{n:03}"></a>\n## Passage card — `{sid}-q{n:03}` — {title}\n\n**Paraphrase:** {body}\n\n- **Locator:** {locator}\n- **Status:** source-matched paraphrase; not quotation-ready.\n- **Verification:** {verification}; consulted 2026-09-08.\n- **Source relation:** Paraphrased.\n- **Evidential action:** establishes this work's theoretical formulation, not an empirical finding or native QL derivation.\n- **Consumers:** Baudrillard lens; exact downstream proposals remain with T22.\n'''
def save(sid,edition,biblio,scholar,cards,dispositions,debt,local=None):
 p=idx[sid];old=p.read_text();meta=yaml.safe_load(old.split('---',2)[1]);meta.update(register='episteme',edition_status=edition,citation_status='citation-ready',quote_status='source-matched-paraphrases',chicago_ready=True,accessed='2026-09-08',main_source_for=['lens-baudrillard'])
 if local:meta['local_copy']=str(raw/local)
 text='---\n'+yaml.safe_dump(meta,allow_unicode=True,sort_keys=False)+'---\n# '+meta['title']+'\n\n## Bibliographic identity\n\n'+biblio+'\n\n## Source scholarship\n\n'+scholar+'\n\n<a id="passages"></a>\n## Passages\n'+''.join(cards)+f'\n## Essay uses\n\nThis source **sources** the [Baudrillard lens]({link(p,lens)}), which compares the selected operation with E4 Account/source return. A20/A24/A32 and C27/C33/C38/C55 retain their native derivations. These are lens proposals, not newly propagated consumer edges.\n\n## Superseded intake and retained research\n\n'+dispositions+'\n\n## Open acquisition and verification\n\n'+debt+'\n'
 p.write_text(text)
s='baudrillard-1976-symbolic-exchange-death'
save(s,'selected-2017-revised-digital-witness',
'''French work: *L’Échange symbolique et la mort* (Paris: Gallimard, 1976). Grant's English translation first appeared in 1993. The witness actually consulted here is the **2017 revised edition**, identified by its copyright/edition leaves, through [indexed primary PDF text](https://agorism.dev/book/philosophy/Baudrillard.%20Symbolic%20Exchange%20and%20Death.%20Revised%20edition..pdf). Its file pages are not the 1993 printed pagination. Direct download returned 404 and page-image retrieval failed; selected cached primary text, not an acquired complete scan, supports the cards.

**Full note:** Jean Baudrillard, *Symbolic Exchange and Death*, trans. Iain Hamilton Grant, rev. ed. (London: SAGE, 2017), Preface, digital witness file pp.36–40.

**Shortened note:** Baudrillard, *Symbolic Exchange and Death*, chapter/subsection and digital file page.

**Bibliography:** Baudrillard, Jean. *Symbolic Exchange and Death*. Translated by Iain Hamilton Grant. Revised edition. London: SAGE, 2017.

[UC Irvine's bibliography](https://www.lib.uci.edu/sites/all/docs/wellek/baudrillard/1993.html) separately locates the 1993 order-of-simulacra chapter at pp.50–86. That is a collation lead, not permission to substitute its pages for the 2017 witness.''',
'''Reversibility is central: gift/counter-gift and the undoing of accumulated value oppose a system that can circulate terms without receiving that challenge. The Preface also subjects its own theoretical terms to removal; the symbolic cannot simply become another guaranteed positive category. Death therefore cannot be reduced to the referent's disappearance: the book's programme includes the exchange of death and the separation of living and dead.

The three orders specify mutations in the law of value. Counterfeit belongs to the Renaissance/classical period through the Industrial Revolution; production to industrial organisation; simulation to the code. This is Baudrillard's historical construction, with independent historical corroboration still owed. Its own discussion warns against idealising the restricted, hierarchical circulation of earlier signs.''',[
card(s,1,'Reversibility and the symbolic','The Preface makes reversal, counter-gift and symbolic interruption antagonistic to cumulative value; even code and symbolic must remain removable terms of the theory.','2017 witness, Preface, file pp.36–40, especially p.40 n.2.','Cached primary text read with Preface context; no page-image collation'),
card(s,2,'Three historical orders','Counterfeit, production and simulation correspond to distinct historical regimes of value; counterfeit starts with the Renaissance rather than an undifferentiated premodern world.','Chapter2, The Three Orders of Simulacra and The Stucco Angel, file pp.94–98.','Cached primary text read; 1993 pp.50–55 are separate UC Irvine locator leads'),
card(s,3,'Referential and structural dimensions','The opening analysis separates a term’s reference from its relations within a system; structural autonomy allows prior references to persist as simulated alibis.','Chapter1, The Structural Revolution of Value, file pp.41–44.','Cached primary text read; no full-book reading claimed')],
'''The intake's description of symbolic exchange as irreversible is withdrawn. The four-values/four-falls mapping remains **unratified**; symbolic exchange is not installed as a fourth commensurable value. The code/occupied-measure comparison survives as a register-3 question. The death-of-referent reduction and attribution of the entire masses thesis to this book are not restored. *In the Shadow of the Silent Majorities* remains a separate work. Original intake prose survives in this batch's private before-image, not as current source evidence.''',
'''Acquire and visually collate the selected revised edition or deliberately bind a successor 1993 witness; preserve edition-specific pagination. Verify the proposed four-value account against its proper earlier work before quotation or mapping. Detailed anthropological and historical assertions require independent evidence. No full-book or quotation audit has been discharged.''')
s='baudrillard-1977-forget-foucault'
save(s,'selected-2007-scan',
'''French original: *Oublier Foucault* (Paris: Galilée, 1977). The [consulted scan](https://teddykw2.files.wordpress.com/2012/07/jean-baudrillard-forget-foucault.pdf) is Semiotext(e), **2007**, ISBN9781584350415: copyright and title leaves identify Nicole Dufresne's main translation. The [WPS preview](https://docshare.wps.com/document/jean-baudrillard-forget-foucault/40412/) carries the same edition metadata but stops in Lotringer's introduction. The scan supplies the selected main-text passages. Its contents place the main essay at p.27 and the interview at p.71. The latter credits Phil Beitchman, Lee Hildreth and Mark Polizzotti; it is not Dufresne's main essay. Lotringer pp.7–8 recounts the 1987 English publication and 1984 interview; those are separately attributed editorial testimony.

**Full note:** Jean Baudrillard, *Forget Foucault*, trans. Nicole Dufresne, introduction and interview by Sylvère Lotringer (Los Angeles: Semiotext(e), 2007), 29–31.

**Shortened note:** Baudrillard, *Forget Foucault*, page.

**Bibliography:** Baudrillard, Jean. *Forget Foucault*. Translated by Nicole Dufresne. Introduction and interview by Sylvère Lotringer. Los Angeles: Semiotext(e), 2007.''',
'''The opening tests discourse through what its own articulation does: the analysis of power can reproduce its object's operation. Baudrillard then asks whether analytical perfection arrives after the referent's exhaustion. He explicitly recognises Foucault's shift toward productive, immanent power before contesting the axiom that power remains the real term. Reducing their disagreement to external discipline versus newly discovered internal control misstates this sequence.

Production at pp.36–40 includes compulsory appearance, confession and calculability. The later reversible challenge is not private disbelief undoing an institution. These are Baudrillard's theoretical claims; his sweeping statements about cultures and fascism are not established historical evidence here.''',[
card(s,1,'Disposition of misplaced orgy lead','The former q001 orgy-opening lead belongs to Transparency of Evil, After the Orgy, p.3. This identifier preserves the correction rather than manufacturing a Forget Foucault quotation.','Former lead withdrawn; see baudrillard-1990-transparency-evil-q001.','2007 contents/main opening compared with 1993 Transparency primary preview'),
card(s,2,'Discourse participating in power','The analysis mirrors the powers it describes; the question about their disappearance contests their continued status as the explanatory referent.','Printed pp.29–31, scan file pp.25–27.','Selected scan text read; main author distinguished from introduction'),
card(s,3,'Production through the visible','Baudrillard recognises productive power, then connects compulsory sexual expression with the demand that bodies and activity become visible and calculable.','Printed pp.34–40, scan file pp.30–36.','Selected scan text read in sequence'),
card(s,4,'Reversible challenge','The text opposes cumulative irreversibility to reversible seduction and counterchallenge. Challenge exceeds a force contest and does not become a guaranteed technique of liberation.','Printed p.55 and pp.59–64, scan file p.51 and pp.54–59.','Selected scan text read with pp.55–67 context')],
'''The orgy opening is rehomed to Transparency q001; the satsang's sex/energy, happiness and individual-disbelief glosses are encounter provenance only. The former Sorbonne biographical claim is withheld pending a biographical source. The old external-Foucault/internal-Baudrillard sequence is withdrawn. Deleuze's control essay, Foucault's own works and care-of-self remain separately sourced research, not silently verified by this critique. No fourth QL posture is admitted.''',
'''Visually collate selected pages before exact quotation. Main-text reading covered pp.29–43,55–67; the intervening pages and full interview remain separate reading tasks. Neither complete-volume coverage nor an independent adjudication of Foucault's whole corpus is claimed.''','forget-2007-scan.pdf')
s='baudrillard-1981-simulacra-and-simulation'
save(s,'selected-Glaser-reflow-print-collation-open',
'''French original: *Simulacres et simulation* (Paris: Galilée, 1981). English selected translation: Sheila Faria Glaser, University of Michigan Press,1994, corroborated by the [publisher](https://doi.org/10.3998/MPUB.9904). The [locally acquired carrier](https://tanami.org/pub/docs/Baudrillard-Simulacra_and_Simulation.pdf) is a 108-file-page reflow. Its cover was visually inspected and identifies Glaser and Michigan; it lacks a consulted copyright leaf and original page layout. **The text is matched to the Glaser translation; the physical printing and printed locators remain uncollated.** Xenotheka's institutional PDF/TXT links returned401; its advertised object was not inspected. The 1983 *Simulations* selection is a different object.

**Full note:** Jean Baudrillard, *Simulacra and Simulation*, trans. Sheila Faria Glaser (Ann Arbor: University of Michigan Press,1994), “The Precession of Simulacra,” consulted digital reflow, file pp.3–6.

**Shortened note:** Baudrillard, *Simulacra and Simulation*, chapter and reflow file page.

**Bibliography:** Baudrillard, Jean. *Simulacra and Simulation*. Translated by Sheila Faria Glaser. Ann Arbor: University of Michigan Press,1994.''',
'''Baudrillard reverses the map/territory fable and then says even the inverted fable is inadequate: simulation threatens the difference that made representation possible. That is stronger than a model merely influencing an independently described event. The text's four image phases distinguish faithful reference, distortion, concealed absence and simulation without a referential relation. The last phase's two printed clauses belong together; reflow does not create a fifth phase.

This is a cultural-theoretical lens. A forecast's causal influence neither verifies its truth nor establishes Baudrillard's diagnosis at the scale of an entire society. Iconoclastic and ethnological examples in the chapter are source claims requiring their own historical tests.''',[
card(s,1,'Map inversion and its limit','The model precedes what it ostensibly depicts; Baudrillard reverses the fable and then exceeds its map/territory distinction. The inversion belongs to his argument, not Borges’s original telling.','The Precession of Simulacra, reflow file p.3 through opening p.4.','Acquired primary reflow read; cover visually inspected; printed pagination uncollated'),
card(s,2,'Four phases of the image','The four relations are disclosure, distortion, concealment of absent reference and a simulacrum without reference. They are distinct from the three historical orders.','The Divine Irreference of Images, reflow file pp.4–6, phases on p.6.','Whole selected subsection read; four cases confirmed by subsequent explanatory paragraph'),
card(s,3,'Hyperreal operational production','Models produce an operational real through combinatory control rather than merely copying an independently guaranteed original.','Precession opening, reflow file pp.3–4.','Primary reflow read; no blanket empirical or ontological conclusion adopted'),
card(s,4,'Historical orders source return','The counterfeit/production/simulation genealogy is sourced separately in Symbolic Exchange and Death q002. It is not a second name for the image-phase list.','Cross-work locator: baudrillard-1976-symbolic-exchange-death-q002.','Selected passages compared; no invented page in this book')],
'''Four phases/four falls remains **unratified**, including the proposed reverse itinerary. The Śaiva completion and sealed-prapañca comparisons remain Offered, with no claim that Baudrillard stopped at an equivalent Sanskrit doctrine. *The Matrix* anecdote and Butler/Poster/Norris/Kellner/Wolin reception leads remain unverified at their separate sources. No mathematical cohomology argument is established by this book.''',
'''Collate the selected Glaser text against a paginated1994 scan and verify any exact quotation. The acquired whole file is not a full-book reading claim: this batch read the opening and Divine Irreference subsection (file pp.3–6), plus surrounding Ramses discussion through p.9 as context. Institutional Xenotheka access and historical case verification remain open.''','simulacra-glaser.pdf')
s='baudrillard-1983-fatal-strategies'
save(s,'selected-2008-primary-text',
'''French original: *Les Stratégies fatales* (Paris: Grasset,1983). The [consulted primary scan-text carrier](https://www.scribd.com/document/603774005/Jean-Baudrillard-Fatal-Strategies-Semiotext-e-2008-1) identifies the **2008 Semiotext(e)** edition, ISBN9781584350613, with Dominic Pettman's introduction. Its title credits Philippe Beitchman and W. G. J. Niesluchowski (OCR corrupts the latter ending). Earlier1990 publication remains separate;2008 page numbers are not1990 locators. Pettman's “A Belated Invitation to the Orgy” is an introduction, not Baudrillard's main text or the opening of Forget Foucault.

**Full note:** Jean Baudrillard, *Fatal Strategies*, trans. Philippe Beitchman and W. G. J. Niesluchowski, introduction by Dominic Pettman (Los Angeles: Semiotext(e),2008),219–30.

**Shortened note:** Baudrillard, *Fatal Strategies*, page.

**Bibliography:** Baudrillard, Jean. *Fatal Strategies*. Translated by Philippe Beitchman and W. G. J. Niesluchowski. Introduction by Dominic Pettman. Los Angeles: Semiotext(e),2008.''',
'''The closing chapter places fatal theory on the side of an object whose response can exceed the subject's intended game. It also questions whether a fatal strategy can be secured as a strategy at all. This resists the intake's conversion into instructions for a subject to accelerate collapse. Yet the correction must retain the text's extremity: pp.222–25 develops worsening, spectacle and the deepening of negative conditions. Anti-programmatic does not mean moderate or conciliatory.

The lens may test an account's claim to master its object through this difference. Baudrillard's object and native Bimba retain distinct ontological offices. His speculation about nuclear spectacle is not an empirical safety guarantee.''',[
card(s,1,'Object and fatal theory','The proposed difference is whether theory assumes the subject more cunning than its object or lets the object’s ruses exceed that understanding.','For a Principle of Evil,2008 pp.219–21.','Public primary text read in full chapter context pp.219–30; OCR, not visually collated quotation'),
card(s,2,'Worsening and spectacle','The chapter retains the disturbing possibility of intensified negative conditions and spectacle; correcting the practical recipe must not erase these arguments.','2008 pp.222–26.','Public primary text read; claims retained as theory, not instructions or verified prediction'),
card(s,3,'No guaranteed strategy','The ending questions control of ends and the availability of a guaranteed fatal strategy; theory itself takes the risk of the hypothesis it advances.','2008 pp.227–30.','Complete closing sequence read; no full-book claim')],
'''The imperative to accelerate until collapse is withdrawn as a summary of this work. The candidate fourth posture remains unratified; the lens does not diagnose a newly admitted QL topology. The masses argument requires its own1978 carrier if selected. The1995 Perfect Crime motif is not retroactively authenticated here. Original candidate questions survive as research provenance in the immutable before-image.''',
'''Visually collate selected2008 pages and translator spelling before quotation. Read the earlier chapters for a whole-book study; do not treat the complete closing chapter as complete-volume coverage. No collapse forecast, political programme or guarantee of symbolic return is admitted.''','fatal-2008.html')
s='baudrillard-1990-transparency-evil'
save(s,'selected-1993-primary-preview',
'''French original: *La Transparence du mal: essai sur les phénomènes extrêmes* (Paris: Galilée,1990). The [consulted primary preview](https://pdfcoffee.com/baudrillard-the-transparency-of-evil-essays-on-extreme-phenomena-1993-pdf-free.html) reproduces title/copyright and contents identifying James Benedict's1993 Verso translation. “After the Orgy” starts at printed p.3. The browser tool exposes the primary text; direct download returned403, so no complete local scan is claimed.

**Full note:** Jean Baudrillard, *The Transparency of Evil: Essays on Extreme Phenomena*, trans. James Benedict (London: Verso,1993),3–6.

**Shortened note:** Baudrillard, *The Transparency of Evil*, page.

**Bibliography:** Baudrillard, Jean. *The Transparency of Evil: Essays on Extreme Phenomena*. Translated by James Benedict. London: Verso,1993.''',
'''The opening asks what follows the realised liberations of modernity. Continued reproduction can outlive its purposes; the fractal account then distinguishes dispersal from the earlier laws of value. It explicitly removes equivalence, rather than completing universal convertibility. Natural/use, commodity/exchange and structural/sign stages precede the proposed fractal stage; this is a value-stage account, distinct from both the image phases and historical orders.

The essay's transparency-without-trust comparison remains operationally useful, but the precise visibility passage is now independently located in Forget Foucault pp.36–40. This house does not borrow that passage under a new title.''',[
card(s,1,'After the Orgy — corrected home','The opening asks how a culture continues after its liberations have been accomplished, with replay and circulation replacing an unrealised goal.','After the Orgy,1993 pp.3–4.','Title/copyright/contents and primary preview text read; no visual scan collation'),
card(s,2,'Fractal value beyond equivalence','The fourth value-stage is dispersal without an anchoring reference or law of equivalence. Continued propagation can outlive the ideas and ends that originally oriented it.','After the Orgy,1993 pp.5–6.','Primary preview read with pp.3–6 context; no quotation transcription admitted')],
'''The old q001 generic-obscenity lead is superseded by the precisely located orgy passage; the visibility research route survives in Forget Foucault q003. Former q003 Perfect Crime is an unverified separate1995-work lead, not an admitted passage here. The fractal-as-total-convertibility account is withdrawn. Prakāśa-without-vimarśa and perfect-crime/cohomology remain unratified comparisons, not sourced doctrinal identities.''',
'''Acquire and visually collate the1993 volume for quotations and read the remaining essays before making whole-volume claims. Preserve radical-otherness chapters as distinct future research. Empirical transparency/trust effects need actual cases; no theorem that cohomology is always nonzero follows from these sources.''')
print('updated five SOURCE houses; no other canon')
